### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by Squet** [trakt/Plex-Trakt-Scrobbler#130]
I can sign in to the trakt website no problems, but when I try to put my username and password in the plugin it says "Error: Authentication failed" above Sync and About, and then when I press Sync it says "Syncing task already running, unable to start".
Username and password is correct in the preferences file.

**Comment by patricklewis** [comment]
Same problem here:

* Linux Plex Media Server 0.9.11.7

**Comment by reokue** [comment]
I changed my credentials to use the email associated with my account instead of the username and that fixed the error for me.

This is on a Synology running Plex Media Server 9.11.5 with Plex-Trakt-Scrobbler 0.9.1.2-beta.

**Comment by scottrobertson** [comment]
Changed to using email, worked. But like @patricklewis said, this could have just been because they changed something on their end.

**Comment by CherryCrunch** [comment]
Well I just tried to get it running and allways get the same problem. No matter if I use eMail or Username and my password, I get a Authentication failed error.

I use Plex Version 0.9.11.16 on a Synology and Plex Trakt 0.9.1.24. Can anyone help me?

**Comment by Tuumke** [comment]
@fuzeman why is this closed exactly?

**Comment by scottrobertson** [comment]
@Tuumke it's been a while since anyone complained about it. Seems to be sorted now.

**Comment by fuzeman** [comment]
The original issue report was over a year ago, please open a new issue if this is happening on the latest versions (stable or beta) of the plugin.

**Comment by jonnymd** [comment]
Happening for me. I tried both username and email. Reset password to alphanumeric only. Verify on trakt.tv website and login without issues.  Authorization error from channel plugin.

Plex server version 0.9.12.13
Plex web 2.4.23
Trakt plugin 0.9.1.29

**Comment by Xodus-CO** [comment]
Getting authentication failed as well when I noticed it was no longer updating trakt.




2015-10-21 10:01:29,977 (7fe406c77700) :  ERROR (logging_handler:46) - [plugin] Authentication failed: hostname 'api-v2launch.trakt.tv' doesn't match either$
Traceback (most recent call last):
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/trakttv.bundle/Contents/Code/__init__.py", line 211, in authenticate
    exceptions=True
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/trakttv.bundle/Contents/Libraries/Shared/trakt/interfaces/auth.py", $
    'password': password
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/trakttv.bundle/Contents/Libraries/Shared/trakt/core/http.py", line 9$
    return self.request('POST', path, params, data, **kwargs)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/trakttv.bundle/Contents/Libraries/Shared/trakt/core/http.py", line 6$
    response = self.session.send(prepared, timeout=timeout)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/trakttv.bundle/Contents/Libraries/Shared/requests/sessions.py", line$
    r = adapter.send(request, **kwargs)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/trakttv.bundle/Contents/Libraries/Shared/requests/adapters.py", line$
    raise SSLError(e, request=request)
SSLError: hostname 'api-v2launch.trakt.tv' doesn't match either of 'ssl276355.cloudflaressl.com', '*.altorendimientoacademico.com', '*.baseshare.com', '*.ca$
2015-10-21 10:01:29,985 (7fe406c77700) :  INFO (logging_handler:46) - [requests.packages.urllib3.connectionpool] Starting new HTTP connection (1): sentry.sk$
2015-10-21 10:01:30,149 (7fe406c77700) :  INFO (datakit:131) - Saved the dictionary file
2015-10-21 10:01:30,149 (7fe406c77700) :  WARNING (logging_handler:46) - [plugin] Unable to authentication with trakt.tv, will try again in 109 seconds
2015-10-21 10:01:30,153 (7fe406c77700) :  INFO (datakit:131) - Saved the dictionary file
