### ISSUE TITLE
Exception thrown during sync 

### ISSUE THREAD

**Issue by spacecowboy** [trakt/Plex-Trakt-Scrobbler#151]
When selecting *pull from Trakt*, a `JSONDecodeError`is thrown (see log below).

Running:
Trakt-plugin from Unsupported App Store (installed today)
Debian Jessie
Python 2.7.8
PMS 0.9.11.4

```
2014-12-17 12:23:21,385 (7f0c177fe700) :  DEBUG (logger:18) - [sync.pull] Processing "Girls" [('thetvdb', '220411')]
2014-12-17 12:23:21,386 (7f0c177fe700) :  DEBUG (logger:18) - [core.network] Requesting 'http://127.0.0.1:32400/library/metadata/2883/allLeaves' (xml) [cache_id: 1418815399.64]
2014-12-17 12:23:21,400 (7f0c177fe700) :  WARNING (logger:18) - [core.task] Exception raised in triggered function <bound method Show.run of <pull.Show object at 0x360b510>> (<class 'simplejson.scanner.JSONDecodeError'>) Expecting value: line 1 column 1 (char 0): Traceback (most recent call last):
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/trakttv.bundle/Contents/Code/core/task.py", line 59, in run
    self.result = self.target(*self.args, **self.kwargs)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 19, in _apply
    return apply(f, args, kwargs)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/trakttv.bundle/Contents/Code/sync/pull.py", line 154, in run
    p_episodes=self.plex.episodes(p_show.rating_key, p_show),
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/trakttv.bundle/Contents/Code/sync/sync_base.py", line 48, in episodes
    return PlexLibrary.fetch_episodes(key, parent, cache_id=cls.get_cache_id())
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/trakttv.bundle/Contents/Code/plex/plex_library.py", line 98, in fetch_episodes
    season, episodes = PlexMatcher.get_identifier(video)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/trakttv.bundle/Contents/Code/plex/plex_matcher.py", line 222, in get_identifier
    c_episodes.extend(cls.get_extended(video, p_season, p_episode))
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/trakttv.bundle/Contents/Code/plex/plex_matcher.py", line 187, in get_extended
    c_identifiers = cls.parse(file_name)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/trakttv.bundle/Contents/Code/plex/plex_matcher.py", line 154, in parse
    identifier = cls.lookup(file_hash)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/trakttv.bundle/Contents/Code/plex/plex_matcher.py", line 138, in lookup
    cls.load()
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/trakttv.bundle/Contents/Code/plex/plex_matcher.py", line 113, in load
    cls.cache = json_decode(Data.Load(cls.cache_key))
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/trakttv.bundle/Contents/Code/core/helpers.py", line 86, in json_decode
    return JSON.loads(s)
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/site-packages/simplejson/__init__.py", line 488, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/site-packages/simplejson/decoder.py", line 389, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

2014-12-17 12:23:21,404 (7f0c149d9700) :  INFO (datakit:131) - Saved the dictionary file
2014-12-17 12:23:21,404 (7f0c149d9700) :  INFO (logger:18) - [sync.sync_base] Task "pull" finished - success: False, start: 2014-12-17 11:23:19.637974, elapsed: 0:00:01.763602
2014-12-17 12:23:21,404 (7f0c149d9700) :  WARNING (logger:18) - [sync.manager] Error occurred while running work
2014-12-17 12:23:21,405 (7f0c149d9700) :  DEBUG (logger:18) - [sync.manager] Work finished
2014-12-17 12:23:29,183 (7f0c177fe700) :  DEBUG (runtime:717) - Handling request GET /applications/trakttv
2014-12-17 12:23:29,185 (7f0c177fe700) :  DEBUG (runtime:814) - Found route matching /applications/trakttv
2014-12-17 12:23:29,186 (7f0c177fe700) :  DEBUG (base:125) - Checking if com.plexapp.plugins.trakttv is broken
2014-12-17 12:23:29,187 (7f0c177fe700) :  DEBUG (networking:172) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X1N0b3JlU2VydmljZTpJc0NoYW5uZWxCcm9rZW4_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMQpzMjcKY29tLnBsZXhhcHAucGx1Z2lucy50cmFrdHR2czEwCmlkZW50aWZpZXJyMAo_'
2014-12-17 12:23:29,197 (7f0c177fe700) :  DEBUG (runtime:106) - Sending packed state data (108 bytes)
2014-12-17 12:23:29,197 (7f0c177fe700) :  DEBUG (runtime:918) - Response: [200] MediaContainer, 1134 bytes
2014-12-17 12:23:29,236 (7f0c177fe700) :  DEBUG (runtime:717) - Handling request GET /applications/trakttv/sync?refresh=1418815400
2014-12-17 12:23:29,238 (7f0c177fe700) :  DEBUG (runtime:814) - Found route matching /applications/trakttv/sync
2014-12-17 12:23:29,239 (7f0c177fe700) :  DEBUG (logger:18) - [core.network] Requesting 'http://127.0.0.1:32400/library/sections' (xml) 
2014-12-17 12:23:29,243 (7f0c177fe700) :  DEBUG (runtime:106) - Sending packed state data (108 bytes)
2014-12-17 12:23:29,243 (7f0c177fe700) :  DEBUG (runtime:918) - Response: [200] MediaContainer, 1925 bytes
```

**Comment by intel352** [comment]
@fuzeman, I'm still experiencing this issue. Is trakt scrobble working for others? Just wondering if something in my setup rather than assuming a trakt server issue...

**Comment by h0bd0b1in** [comment]
I'm experiencing the issue too, and I've trashed all related files a number of times just to check. Must be the servers.

**Comment by fuzeman** [comment]
v0.9.1.1 is available now: https://forums.plex.tv/index.php/topic/102818-rel-trakt/?p=810730

Please post updated logs if you are still experiencing issues with scrobbling.

**Comment by intel352** [comment]
@fuzeman, awesome, that worked, thanks for the 2.0 update :-)

**Comment by intel352** [comment]
@fuzeman, I'm not home, so I can't check the logs, but I'm seeing all trakt activities fail (sync, push, pull, etc). Dunno how long it's been failing. It definitely successfully pushed, after I upgraded to the beta you noted in this thread, but I hadn't checked the status again until just now, for which everything shows failed, and re-running manually fails.

**Comment by fuzeman** [comment]
@intel352 possibly related to https://github.com/trakt/Plex-Trakt-Scrobbler/issues/157, I'm unable to sync currently as well.
