### ISSUE TITLE
Exception when pushing to trakt

### ISSUE THREAD

**Issue by shadone** [trakt/Plex-Trakt-Scrobbler#156]
I set a filter to only push one plex library (due to #155), however I got another exception, possibly also related to non-ascii characters in media items names:
```
2015-01-01 20:29:36,717 (112b8a000) :  DEBUG (logging_handler:16) - [trakt.client] "user/library/movies/watched.json" - data: None
2015-01-01 20:29:37,841 (112b8a000) :  DEBUG (logging_handler:16) - [requests.packages.urllib3.connectionpool] "POST /user/library/movies/watched.json/ba5aa61249c02dc5406232da20f6e768f3c82b28/shadone/min HTTP/1.1" 200 None
2015-01-01 20:29:37,843 (112b8a000) :  DEBUG (logging_handler:16) - [trakt.client] "user/ratings/movies.json" - data: None
2015-01-01 20:29:38,109 (112b8a000) :  DEBUG (logging_handler:16) - [requests.packages.urllib3.connectionpool] "POST /user/ratings/movies.json/ba5aa61249c02dc5406232da20f6e768f3c82b28/shadone/all/min HTTP/1.1" 404 None
2015-01-01 20:29:38,111 (112b8a000) :  WARNING (logger:18) - [core.task] Exception raised in triggered function <bound method Movie.run of <push.Movie object at 0x112487810>> (<class 'simplejson.scanner.JSONDecodeError'>) Expecting value: line 1 column 1 (char 0): Traceback (most recent call last):
  File "/Users/media/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code/core/task.py", line 59, in run
    self.result = self.target(*self.args, **self.kwargs)
  File "/Users/media/Library/Application Support/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 19, in _apply
    return apply(f, args, kwargs)
  File "/Users/media/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code/sync/push.py", line 275, in run
    collected='collected' in enabled_funcs
  File "/Users/media/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code/sync/sync_base.py", line 118, in merged
    if Trakt['user/ratings'].get(media, extended=extended, store=items) is None:
  File "/Users/media/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/trakt/interfaces/base/__init__.py", line 21, in wrap
    return func(*args, **kwargs)
  File "/Users/media/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/trakt/interfaces/user/ratings.py", line 19, in get
    items = self.get_data(response)
  File "/Users/media/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/trakt/interfaces/base/__init__.py", line 97, in get_data
    data = response.json()
  File "/Users/media/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/requests/models.py", line 759, in json
    return json.loads(self.text, **kwargs)
  File "/Users/admin/jenkins/pms-deps-universal-v2/BUILD_TAG/darwin-x86_64/output/pms-depends-darwin-x86_64-release-c298a27/lib/python2.7/site-packages/simplejson/__init__.py", line 488, in loads
  File "/Users/admin/jenkins/pms-deps-universal-v2/BUILD_TAG/darwin-x86_64/output/pms-depends-darwin-x86_64-release-c298a27/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
  File "/Users/admin/jenkins/pms-deps-universal-v2/BUILD_TAG/darwin-x86_64/output/pms-depends-darwin-x86_64-release-c298a27/lib/python2.7/site-packages/simplejson/decoder.py", line 389, in raw_decode
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by fuzeman** [comment]
Try updating to the latest beta release (which supports trakt 2.0): https://forums.plex.tv/index.php/topic/102818-rel-trakt/page-23#entry812374

**Comment by shadone** [comment]
That fixed that issue, thanks!

(plex-trakt sync still fails though, this time due to missing authentication token it seems - https://gist.github.com/shadone/c52af191a614b708cc58 - I have username/password provided in the plugin settings)

**Comment by fuzeman** [comment]
That 401 error was reported here as well: https://github.com/trakt/Plex-Trakt-Scrobbler/issues/153#issuecomment-68632688

I've opened a new issue here https://github.com/trakt/Plex-Trakt-Scrobbler/issues/157 to track this specific problem.
