### ISSUE TITLE
Max retries exceeded when trying to sync

### ISSUE THREAD

**Issue by claytron** [trakt/Plex-Trakt-Scrobbler#185]
I upgraded to the latest version (`v0.9.1.24`) and got the following errors when trying to sync:

```
2015-03-31 10:04:20,036 (10554a000) :  INFO (logging_handler:46) - [requests.packages.urllib3.connectionpool] Starting new HTTP connection (1): sentry.skipthe.net
2015-03-31 10:04:25,608 (105107000) :  ERROR (logging_handler:46) - [plugin.core.task] Exception raised in triggered function 'sync.pull.movie': HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /sync/watched/movies (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Read timed out. (read timeout=24)",))
Traceback (most recent call last):
  File "/Users/clayton/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code/core/task.py", line 65, in run
    self.result = self.target(*self.args, **self.kwargs)
  File "/Users/clayton/Library/Application Support/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 19, in _apply
    return apply(f, args, kwargs)
  File "/Users/clayton/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code/sync/pull.py", line 290, in run
    t_movies, t_movies_table = self.trakt.merged('movies', ratings='ratings' in enabled_funcs, collected=True)
  File "/Users/clayton/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code/sync/sync_base.py", line 86, in merged
    if watched and Trakt['sync/watched'].get(media, **params) is None:
  File "/Users/clayton/Library/Application Support/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 19, in _apply
    return apply(f, args, kwargs)
  File "/Users/clayton/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/trakt/interfaces/base/__init__.py", line 17, in wrap
    return func(*args, **kwargs)
  File "/Users/clayton/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/trakt/interfaces/sync/core/mixins.py", line 16, in get
    params=r_params
  File "/Users/clayton/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/trakt/core/http.py", line 89, in get
    return self.request('GET', path, params, data, **kwargs)
  File "/Users/clayton/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/trakt/core/http.py", line 69, in request
    response = self.session.send(prepared, timeout=timeout)
  File "/Users/clayton/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Users/clayton/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/requests/adapters.py", line 424, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /sync/watched/movies (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Read timed out. (read timeout=24)",))
2015-03-31 10:04:25,635 (105107000) :  INFO (logging_handler:46) - [requests.packages.urllib3.connectionpool] Starting new HTTP connection (1): sentry.skipthe.net
2015-03-31 10:04:25,832 (1069dc000) :  INFO (logging_handler:46) - [plugin.sync.sync_base] Task "pull" finished - success: False, start: 2015-03-31 14:03:50.748359, elapsed: 0:00:35.083079, exceptions: [ConnectionError(MaxRetryError('HTTPSConnectionPool(host=\'api-v2launch.trakt.tv\', port=443): Max retries exceeded with url: /sync/watched/movies (Caused by ReadTimeoutError("HTTPSConnectionPool(host=\'api-v2launch.trakt.tv\', port=443): Read timed out. (read timeout=24)",))',),), ConnectionError(MaxRetryError('HTTPSConnectionPool(host=\'api-v2launch.trakt.tv\', port=443): Max retries exceeded with url: /sync/watched/shows (Caused by ReadTimeoutError("HTTPSConnectionPool(host=\'api-v2launch.trakt.tv\', port=443): Read timed out. (read timeout=24)",))',),)]
2015-03-31 10:04:25,833 (1069dc000) :  WARNING (logging_handler:46) - [plugin.sync.synchronize] Pull handler failed
2015-03-31 10:04:25,835 (1069dc000) :  INFO (logging_handler:46) - [plugin.sync.sync_base] Task "synchronize" finished - success: False, start: 2015-03-31 14:03:50.748251, elapsed: 0:00:35.085678, exceptions: [ConnectionError(MaxRetryError('HTTPSConnectionPool(host=\'api-v2launch.trakt.tv\', port=443): Max retries exceeded with url: /sync/watched/movies (Caused by ReadTimeoutError("HTTPSConnectionPool(host=\'api-v2launch.trakt.tv\', port=443): Read timed out. (read timeout=24)",))',),), ConnectionError(MaxRetryError('HTTPSConnectionPool(host=\'api-v2launch.trakt.tv\', port=443): Max retries exceeded with url: /sync/watched/shows (Caused by ReadTimeoutError("HTTPSConnectionPool(host=\'api-v2launch.trakt.tv\', port=443): Read timed out. (read timeout=24)",))',),)]
2015-03-31 10:04:27,815 (1069dc000) :  WARNING (logging_handler:46) - [plugin.sync.manager] Error occurred while running work
2015-03-31 10:04:38,627 (10554a000) :  INFO (logging_handler:46) - [requests.packages.urllib3.connectionpool] Resetting dropped connection: 127.0.0.1
2015-03-31 10:04:54,852 (10554a000) :  INFO (logging_handler:46) - [requests.packages.urllib3.connectionpool] Resetting dropped connection: 127.0.0.1
2015-03-31 10:04:54,855 (107b28000) :  INFO (logging_handler:46) - [requests.packages.urllib3.connectionpool] Resetting dropped connection: 127.0.0.1
2015-03-31 10:04:54,868 (107b28000) :  INFO (logging_handler:46) - [requests.packages.urllib3.connectionpool] Resetting dropped connection: 127.0.0.1
2015-03-31 10:04:56,016 (107b28000) :  INFO (logging_handler:46) - [requests.packages.urllib3.connectionpool] Resetting dropped connection: 127.0.0.1
2015-03-31 10:04:56,217 (107b28000) :  INFO (logging_handler:46) - [requests.packages.urllib3.connectionpool] Starting new HTTPS connection (3): api-v2launch.trakt.tv
2015-03-31 10:05:20,433 (107b28000) :  ERROR (logging_handler:46) - [plugin.core.task] Exception raised in triggered function 'sync.push.show': HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /sync/watched/shows (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Read timed out. (read timeout=24)",))
Traceback (most recent call last):
  File "/Users/clayton/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code/core/task.py", line 65, in run
    self.result = self.target(*self.args, **self.kwargs)
  File "/Users/clayton/Library/Application Support/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 19, in _apply
    return apply(f, args, kwargs)
  File "/Users/clayton/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code/sync/push.py", line 311, in run
    collected='collected' in enabled_funcs
  File "/Users/clayton/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code/sync/sync_base.py", line 86, in merged
    if watched and Trakt['sync/watched'].get(media, **params) is None:
  File "/Users/clayton/Library/Application Support/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 19, in _apply
    return apply(f, args, kwargs)
  File "/Users/clayton/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/trakt/interfaces/base/__init__.py", line 17, in wrap
    return func(*args, **kwargs)
  File "/Users/clayton/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/trakt/interfaces/sync/core/mixins.py", line 16, in get
    params=r_params
  File "/Users/clayton/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/trakt/core/http.py", line 89, in get
    return self.request('GET', path, params, data, **kwargs)
  File "/Users/clayton/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/trakt/core/http.py", line 69, in request
    response = self.session.send(prepared, timeout=timeout)
  File "/Users/clayton/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Users/clayton/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/requests/adapters.py", line 424, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /sync/watched/shows (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Read timed out. (read timeout=24)",))
2015-03-31 10:05:20,460 (107b28000) :  INFO (logging_handler:46) - [requests.packages.urllib3.connectionpool] Starting new HTTP connection (1): sentry.skipthe.net
2015-03-31 10:05:20,653 (1069dc000) :  INFO (logging_handler:46) - [plugin.sync.sync_base] Task "('push', '2')" finished - success: False, start: 2015-03-31 14:04:54.849215, elapsed: 0:00:25.802425, exceptions: [ConnectionError(MaxRetryError('HTTPSConnectionPool(host=\'api-v2launch.trakt.tv\', port=443): Max retries exceeded with url: /sync/watched/shows (Caused by ReadTimeoutError("HTTPSConnectionPool(host=\'api-v2launch.trakt.tv\', port=443): Read timed out. (read timeout=24)",))',),)]
2015-03-31 10:05:20,729 (1069dc000) :  WARNING (logging_handler:46) - [plugin.sync.manager] Error occurred while running work
```

I can provide more log information if needed.

**Comment by claytron** [comment]
I will also note that after downgrading to `v0.9.1.23`, it works fine.

**Comment by fuzeman** [comment]
This error is raised when the trakt.tv API hasn't returned a response after waiting 24 seconds, this happens quite often when it's under heavy load. Previously we retried these requests to eventually get a response, a few versions back this was disabled as it was causing scrobble duplication in some cases.

I'll need to look into this issue again to see if we can enable retrying again but ensure we don't cause any more scrobble duplication issues.

----------------------

**Note:** Nothing was changed in v0.9.1.24 that would cause this error to happen more often (https://github.com/trakt/Plex-Trakt-Scrobbler/compare/v0.9.1.23...v0.9.1.24).

**Comment by claytron** [comment]
Thanks for the clarification, I upgraded back to the latest and it worked fine.

**Comment by badnetmask** [comment]
I'm sorry, not sure if related, but I got here after a quick search for this error message:

com.plexapp.plugins.trakttv      (7f8ff69d0700) :  INFO (logging_handler:46) - [requests.packages.urllib3.connectionpool] Resetting dropped connection: 127.0.0.1
com.plexapp.plugins.trakttv      (7f8ff69d0700) :  WARNING (logging_handler:46) - [plex.objects.core.base] Detail - Omitted attributes: allowmediadeletion, allowsync, certificate

Running 0.9.1.26-master
