### ISSUE TITLE
v.0.9.9 beta fails to initialize

### ISSUE THREAD

**Issue by rectifyer** [trakt/Plex-Trakt-Scrobbler#195]
Clean install of the v.0.9.9 beta fails to load up and gets the error log below. The error is pointing to shared code which seems weird. I'm running this on Unraid 6.0.1 using PMS Version 0.9.12.4. Let me know if you need more info or logs and thanks for all the work on this!

```
2015-07-03 16:59:56,664 (2b77293ebf00) :  INFO (core:347) - Starting framework core - Version: 2.6.2, Build: 9b6935b (Wed May 20 03:15:08 UTC 2015)
2015-07-03 16:59:56,664 (2b77293ebf00) :  DEBUG (core:359) - Using the elevated policy
2015-07-03 16:59:56,665 (2b77293ebf00) :  DEBUG (core:448) - Starting runtime component.
2015-07-03 16:59:56,667 (2b77293ebf00) :  DEBUG (core:448) - Starting caching component.
2015-07-03 16:59:56,667 (2b77293ebf00) :  DEBUG (core:448) - Starting data component.
2015-07-03 16:59:56,667 (2b77293ebf00) :  DEBUG (core:448) - Starting networking component.
2015-07-03 16:59:56,668 (2b77293ebf00) :  DEBUG (networking:288) - Loaded HTTP cookies
2015-07-03 16:59:56,701 (2b77293ebf00) :  DEBUG (networking:458) - Setting the default network timeout to 20.0
2015-07-03 16:59:56,702 (2b77293ebf00) :  DEBUG (core:448) - Starting localization component.
2015-07-03 16:59:56,702 (2b77293ebf00) :  INFO (localization:408) - Setting the default locale to en-us
2015-07-03 16:59:56,703 (2b77293ebf00) :  DEBUG (localization:426) - Loaded en strings
2015-07-03 16:59:56,703 (2b77293ebf00) :  DEBUG (core:448) - Starting messaging component.
2015-07-03 16:59:56,704 (2b77293ebf00) :  DEBUG (core:448) - Starting debugging component.
2015-07-03 16:59:56,704 (2b77293ebf00) :  DEBUG (core:448) - Starting services component.
2015-07-03 16:59:56,704 (2b77293ebf00) :  DEBUG (core:448) - Starting myplex component.
2015-07-03 16:59:56,704 (2b77293ebf00) :  DEBUG (core:448) - Starting notifications component.
2015-07-03 16:59:56,719 (2b7731b09700) :  DEBUG (networking:172) - Requesting 'http://127.0.0.1:32400/system/messaging/clear_events/com.plexapp.plugins.trakttv'
2015-07-03 16:59:56,863 (2b77293ebf00) :  DEBUG (accessor:68) - Creating a new model access point for provider com.plexapp.plugins.trakttv in namespace 'metadata'
2015-07-03 16:59:56,869 (2b77293ebf00) :  DEBUG (networking:172) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes'
2015-07-03 16:59:57,301 (2b7731b09700) :  DEBUG (services:265) - Plug-in is not daemonized - loading services from system
2015-07-03 16:59:57,301 (2b77293ebf00) :  DEBUG (runtime:1111) - Created a thread named 'load_all_services'
2015-07-03 16:59:57,303 (2b7731b09700) :  DEBUG (networking:172) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMA
pyMAo_'
2015-07-03 16:59:57,303 (2b77293ebf00) :  DEBUG (runtime:1111) - Created a thread named 'get_server_info'
2015-07-03 16:59:57,304 (2b77293ebf00) :  DEBUG (core:150) - Finished starting framework core
2015-07-03 16:59:57,305 (2b77293ebf00) :  DEBUG (core:558) - Loading plug-in code
2015-07-03 16:59:57,309 (2b7731f0b700) :  DEBUG (networking:172) - Requesting 'http://127.0.0.1:32400'
2015-07-03 16:59:57,338 (2b77293ebf00) :  DEBUG (core:564) - Finished loading plug-in code
2015-07-03 16:59:57,342 (2b77293ebf00) :  DEBUG (__init__:18) - Using locale: en_GB.UTF-8
2015-07-03 16:59:57,429 (2b7731f0b700) :  DEBUG (core:536) - Machine identifier is 037fa9a5dcf9306202cefb54a240c5384049e288
2015-07-03 16:59:57,457 (2b7731f0b700) :  DEBUG (core:537) - Server version is 0.9.12.4.1192-9a47d21
2015-07-03 16:59:57,867 (2b7731b09700) :  DEBUG (services:362) - Loaded services
2015-07-03 16:59:57,894 (2b7731d0a700) :  DEBUG (services:438) - No shared code to load
2015-07-03 16:59:58,431 (2b77293ebf00) :  CRITICAL (core:613) - Exception starting plug-in (most recent call last):
  File "/config/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/core.py", line 606, in start
    self.sandbox.execute(self.init_code)
  File "/config/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 256, in execute
    exec(code) in self.environment
  File "/config/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code/__init__.py", line 25, in <module>
    import interface
  File "/config/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 333, in __import__
    return mod.load_module(_name)
  File "/config/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 44, in load_module
    module = RestrictedModule(name, path, sandbox)
  File "/config/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/loader.py", line 30, in __init__
    exec(code) in self.__dict__
  File "/config/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code/interface/__init__.py", line 4, in <module>
    import m_sync
  File "/config/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 333, in __import__
    return mod.load_module(_name)
  File "/config/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 44, in load_module
    module = RestrictedModule(name, path, sandbox)
  File "/config/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/loader.py", line 30, in __init__
    exec(code) in self.__dict__
  File "/config/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code/interface/m_sync.py", line 8, in <module>
    from plugin.managers import AccountManager
  File "/config/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 345, in __import__
    raise e
ImportError: libicui18n.so.48: cannot open shared object file: No such file or directory
```

**Comment by fuzeman** [comment]
I've recompiled apsw (sqlite) without the ICU extension, try testing the develop branch ([develop.zip](https://github.com/trakt/Plex-Trakt-Scrobbler/archive/develop.zip)).

**Comment by rectifyer** [comment]
Cool, the development version allows the plugin to initialize and show up correctly now! However, this uncovered another error when trying to do a full sync which prevents it from working.

```
2015-07-03 22:04:19,306 - plugin.sync.modes.fast_pull      (2ac8bca04700) :  INFO (plugin.sync.modes.fast_pull:145) - [154] GUID agent u'local' is not supported
2015-07-03 22:04:19,317 - plugin.sync.modes.fast_pull      (2ac8bca04700) :  INFO (plugin.sync.modes.fast_pull:145) - [194] GUID agent u'local' is not supported
2015-07-03 22:04:21,921 - plugin.sync.modes.fast_pull      (2ac8bca04700) :  INFO (plugin.sync.modes.fast_pull:145) - [7542] GUID agent u'local' is not supported
2015-07-03 22:04:30,905 - plugin.sync.main                 (2ac8bca04700) :  WARNING (plugin.sync.main:141) - Exception raised in run(): 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/config/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/sync/main.py", line 137, in run_wrapper
    self.run()
  File "/config/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/sync/main.py", line 168, in run
    self.modes[self.current.mode].run()
  File "/config/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/sync/modes/full.py", line 16, in run
    self.modes[SyncMode.FastPull].execute_children()
  File "/config/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/sync/modes/core/base.py", line 82, in execute_children
    c.run()
  File "/config/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/sync/modes/fast_pull.py", line 138, in run
    for ids, p_guid, (season_num, episode_num), p_show, p_season, p_episode in p_episodes:
  File "/config/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plex_database/library.py", line 422, in episodes_iterator
    guid, show = shows.get(sh_id)
TypeError: 'NoneType' object is not iterable
2015-07-03 22:04:31,097 - plugin.sync.core.task.state.main (2ac8bca04700) :  DEBUG (plugin.sync.core.task.state.main:17) - Flushing caches...
```

**Comment by fuzeman** [comment]
ed35d4d should fix that issue, not sure why the plex database has episodes stored without a valid show though..

**Comment by rectifyer** [comment]
Sweet, yes that fixed the issue and allowed it to sync correctly for watched and collected items.

Unrelated to this original bug, but I'm looking into another issue with the collection metadata. It appears to send the incorrect date for the **collected_at** field. For example, an episode collected just 1 day ago sent a date from 2013 along. Looking over the code this seems like a Plex issue where it's reporting the wrong added date, but I haven't looked any deeper than that yet.

**Comment by newloran2** [comment]
I had a similar issue.
My sistem is a PMS 0.9.12.4 running on a mac osx 10.7.4.
I tried to use the the release v0.9.9.0-beta and the develop branch, both has same issue
My log:

2015-07-05 15:03:39,134 (7fff7cd0e960) :  INFO (core:347) - Starting framework core - Version: 2.6.2, Build: 9b6935b (Wed May 20 03:15:08 UTC 2015)
2015-07-05 15:03:39,134 (7fff7cd0e960) :  DEBUG (core:359) - Using the elevated policy
2015-07-05 15:03:39,134 (7fff7cd0e960) :  DEBUG (core:448) - Starting runtime component.
2015-07-05 15:03:39,136 (7fff7cd0e960) :  DEBUG (core:448) - Starting caching component.
2015-07-05 15:03:39,136 (7fff7cd0e960) :  DEBUG (core:448) - Starting data component.
2015-07-05 15:03:39,137 (7fff7cd0e960) :  DEBUG (core:448) - Starting networking component.
2015-07-05 15:03:39,138 (7fff7cd0e960) :  DEBUG (networking:288) - Loaded HTTP cookies
2015-07-05 15:03:39,138 (7fff7cd0e960) :  DEBUG (networking:458) - Setting the default network timeout to 20.0
2015-07-05 15:03:39,142 (7fff7cd0e960) :  DEBUG (core:448) - Starting localization component.
2015-07-05 15:03:39,142 (7fff7cd0e960) :  INFO (localization:408) - Setting the default locale to en-us
2015-07-05 15:03:39,143 (7fff7cd0e960) :  DEBUG (localization:426) - Loaded en strings
2015-07-05 15:03:39,143 (7fff7cd0e960) :  DEBUG (core:448) - Starting messaging component.
2015-07-05 15:03:39,144 (7fff7cd0e960) :  DEBUG (core:448) - Starting debugging component.
2015-07-05 15:03:39,145 (7fff7cd0e960) :  DEBUG (core:448) - Starting services component.
2015-07-05 15:03:39,145 (7fff7cd0e960) :  DEBUG (core:448) - Starting myplex component.
2015-07-05 15:03:39,146 (10c5fc000) :  DEBUG (networking:172) - Requesting 'http://127.0.0.1:32400/system/messaging/clear_events/com.plexapp.plugins.trakttv'
2015-07-05 15:03:39,146 (7fff7cd0e960) :  DEBUG (core:448) - Starting notifications component.
2015-07-05 15:03:39,334 (7fff7cd0e960) :  DEBUG (accessor:68) - Creating a new model access point for provider com.plexapp.plugins.trakttv in namespace 'metadata'
2015-07-05 15:03:39,341 (7fff7cd0e960) :  DEBUG (networking:172) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes'
2015-07-05 15:03:39,696 (10c5fc000) :  DEBUG (services:265) - Plug-in is not daemonized - loading services from system
2015-07-05 15:03:39,697 (7fff7cd0e960) :  DEBUG (runtime:1111) - Created a thread named 'load_all_services'
2015-07-05 15:03:39,698 (10c5fc000) :  DEBUG (networking:172) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_'
2015-07-05 15:03:39,698 (7fff7cd0e960) :  DEBUG (runtime:1111) - Created a thread named 'get_server_info'
2015-07-05 15:03:39,700 (7fff7cd0e960) :  DEBUG (core:150) - Finished starting framework core
2015-07-05 15:03:39,700 (7fff7cd0e960) :  DEBUG (core:558) - Loading plug-in code
2015-07-05 15:03:39,701 (10cec2000) :  DEBUG (networking:172) - Requesting 'http://127.0.0.1:32400'
2015-07-05 15:03:39,751 (7fff7cd0e960) :  DEBUG (core:564) - Finished loading plug-in code
2015-07-05 15:03:39,755 (7fff7cd0e960) :  DEBUG (__init__:18) - Using locale: en_US.UTF-8
2015-07-05 15:03:39,908 (10c5fc000) :  DEBUG (services:362) - Loaded services
2015-07-05 15:03:39,909 (10cec2000) :  DEBUG (core:536) - Machine identifier is 836bce27a7cc2ae108939b16de14ed84aae93b1d
2015-07-05 15:03:39,911 (10cec2000) :  DEBUG (core:537) - Server version is 0.9.12.4.1192-9a47d21
2015-07-05 15:03:39,917 (10cabf000) :  DEBUG (services:438) - No shared code to load
2015-07-05 15:03:39,918 (7fff7cd0e960) :  DEBUG (libraries:41) - System: 'Darwin', Architecture: 'x86_64'
2015-07-05 15:03:39,919 (7fff7cd0e960) :  DEBUG (libraries:57) - Inserted path: '/Users/newloran2/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Darwin/x86_64' (for compiled libraries)
2015-07-05 15:03:40,359 (7fff7cd0e960) :  CRITICAL (core:613) - Exception starting plug-in (most recent call last):
  File "/Users/newloran2/Library/Application Support/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/core.py", line 606, in start
    self.sandbox.execute(self.init_code)
  File "/Users/newloran2/Library/Application Support/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 256, in execute
    exec(code) in self.environment
  File "/Users/newloran2/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code/__init__.py", line 31, in <module>
    import interface
  File "/Users/newloran2/Library/Application Support/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 333, in __import__
    return mod.load_module(_name)
  File "/Users/newloran2/Library/Application Support/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 44, in load_module
    module = RestrictedModule(name, path, sandbox)
  File "/Users/newloran2/Library/Application Support/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/loader.py", line 30, in __init__
    exec(code) in self.__dict__
  File "/Users/newloran2/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code/interface/__init__.py", line 4, in <module>
    import m_sync
  File "/Users/newloran2/Library/Application Support/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 333, in __import__
    return mod.load_module(_name)
  File "/Users/newloran2/Library/Application Support/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 44, in load_module
    module = RestrictedModule(name, path, sandbox)
  File "/Users/newloran2/Library/Application Support/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/loader.py", line 30, in __init__
    exec(code) in self.__dict__
  File "/Users/newloran2/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code/interface/m_sync.py", line 8, in <module>
    from plugin.managers import AccountManager
  File "/Users/newloran2/Library/Application Support/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 345, in __import__
    raise e
ImportError: dlopen(/Users/newloran2/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/MacOSX/i386/apsw.so, 2): Symbol not found: _PyUnicodeUCS2_AsUTF8String
  Referenced from: /Users/newloran2/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/MacOSX/i386/apsw.so
  Expected in: flat namespace
 in /Users/newloran2/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/MacOSX/i386/apsw.so

**Comment by fuzeman** [comment]
@newloran2 I'll have a look at that bug now, looks like I need to compile some libraries that are compatible with your system.

**Comment by fuzeman** [comment]
@newloran2 Just pushed a fix to the development branch ([develop.zip](https://github.com/trakt/Plex-Trakt-Scrobbler/archive/develop.zip)). I've tested it on OSX 10.10.3, but it should be compatible with everything *(excluding the old PowerPC machines)*.

**Comment by fuzeman** [comment]
@rectifyer seeing a similar issue here, my guess is the timestamp of when the show was added to plex is being sent instead. Will start working on a fix now.

**Comment by Benni-chan** [comment]
ImportError: libicui18n.so.48: cannot open shared object file: No such file or directory
This bug seems to be back with the current developer version
(I'm running PlexMediaServer inside a Docker Container on UnRaid (64bit))

**Comment by fuzeman** [comment]
@Benni-chan do you know which template you are using for the plex container? or more specifically which distro is the container built with?

I've found the native libraries for FreeBSD are still built with ```libicui18n.so.48```, so will recompile them and update the develop branch with them tonight.

**Comment by Benni-chan** [comment]
im using https://registry.hub.docker.com/u/needo/plex/
this container uses phusion (based on ubuntu)

**Comment by fuzeman** [comment]
Not sure where the ```libicui18n.so.48``` dependency would be coming from then..

Could you check the libraries you have match these md5 sums:
```
$ md5sum Trakttv.bundle/Contents/Libraries/Linux/i386/* Trakttv.bundle/Contents/Libraries/Linux/x86_64/*
18d9e9931e6bcb287ee0462984bb9f33  Trakttv.bundle/Contents/Libraries/Linux/i386/apsw.so
cd730ca8ac4bd9b97a1697fa4409d202  Trakttv.bundle/Contents/Libraries/Linux/i386/llist.so
460c67399a5409c9531c5c5d88db59ab  Trakttv.bundle/Contents/Libraries/Linux/x86_64/apsw.so
031185f0e863656bc6dad6c2182c3685  Trakttv.bundle/Contents/Libraries/Linux/x86_64/llist.so
```

and find messages similar to these from your log file:
```
DEBUG (logkit:13) - System: 'Windows', Architecture: 'i386'
DEBUG (logkit:13) - [PATH] Libraries\Shared
DEBUG (logkit:13) - [PATH] Libraries\Windows\i386
```

**Comment by Benni-chan** [comment]
ok, i checked the plugin folder and for some reason the x86_64 libraries were missing (even though I deleted the old Bundle folder and unpacked the zip.
did the same again and now the libraries are back and the plugin works again

**Comment by hackedbellini** [comment]
I'm suffering from this bug on a raspberry pi 2 installation:

```
2015-11-28 13:13:21,742 (76f01210) :  CRITICAL (core:613) - Exception starting plug-in (most recent call last):
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/Framework/core.py", line 606, in start
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 256, in execute
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code/__init__.py", line 31, in <module>
    import interface
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 333, in __import__
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 44, in load_module
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/Framework/code/loader.py", line 30, in __init__
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code/interface/__init__.py", line 4, in <module>
    import m_sync
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 333, in __import__
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 44, in load_module
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/Framework/code/loader.py", line 30, in __init__
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code/interface/m_sync.py", line 8, in <module>
    from plugin.managers import AccountManager
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 345, in __import__
ImportError: /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-in Support/Data/com.plexapp.plugins.trakttv/Libraries/Linux/i386/ucs4/apsw.so: cannot open shared object file: No such file or directory
```
