### ISSUE TITLE
0.9.9.1 (develop) Full sync is failing and/or getting stuck.

### ISSUE THREAD

**Issue by xzKinGzxBuRnzx** [trakt/Plex-Trakt-Scrobbler#200]
This is probably related to the latest changes from my other issue (which was quite long so I created this new issue). 40 minutes now and it is still stuck/broken. (see image) https://drive.google.com/file/d/0B-Oiqfh6qsDrWlVsTEhMU2pBVGc/view?usp=sharing

Here is another log, quite long though from normal usage, so long in fact that Github and Pastebin both disapprove of its length. Here is an external link to the log. https://drive.google.com/file/d/0B-Oiqfh6qsDrRllsMVh1MEpGRnc/view?usp=sharing

For quick view here is the new error being thrown that is probably the cause, at least I assume so...

```
2015-07-13 02:00:06,597 - plugin.sync.main                 (7f612b5e3700) :  ERROR (plugin.sync.main:150) - Unable to run final sync tasks: 'rawunicodeescape' codec can't decode bytes in position 599-600: truncated \uXXXX
Traceback (most recent call last):
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/sync/main.py", line 148, in run_wrapper
    self.finish()
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/sync/main.py", line 155, in finish
    current.finish()
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/sync/core/task/main.py", line 64, in finish
    self.state.flush()
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/sync/core/task/state/main.py", line 19, in flush
    self.trakt.flush()
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/sync/core/task/state/trakt_.py", line 95, in flush
    store.flush()
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/trakt_sync/cache/backends/stash_.py", line 22, in flush
    return self.stash.flush()
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/stash/main.py", line 24, in flush
    self.archive.update(self.cache)
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/_abcoll.py", line 494, in update
    self[key] = other[key]
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/stash/archives/a_apsw.py", line 140, in __setitem__
    value = self.dumps(value)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/stash/archives/core/base.py", line 14, in dumps
    return self.serializer.dumps(value)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/stash/serializers/s_pickle.py", line 28, in dumps
    value = unicode(value, 'raw_unicode_escape')
UnicodeDecodeError: 'rawunicodeescape' codec can't decode bytes in position 599-600: truncated \uXXXX
```

**Comment by fuzeman** [comment]
This should be fixed on the development branch now.

I've also increased the database timeout to hopefully fix the ```BusyError: BusyError: database is locked``` error in your log as well.

**Comment by xzKinGzxBuRnzx** [comment]
Tested and working! Thanks! 

```
Last run 3 minutes ago, taking 46 seconds, was successful.

2015-07-13 10:01:20,485 - plugin.sync.main                 (7f4e737fe700) :  INFO (plugin.sync.main:158) - (0) Done
```
