### ISSUE TITLE
Feature Request, connect to trakt servers using SOCKS proxy.

### ISSUE THREAD

**Issue by aaomidi** [trakt/Plex-Trakt-Scrobbler#212]
Title

**Comment by fuzeman** [comment]
Implemented on the [develop](https://github.com/trakt/Plex-Trakt-Scrobbler/archive/develop.zip) branch, will be included in the next release.

**Comment by fuzeman** [comment]
Released in [v1.2.0](https://github.com/trakt/Plex-Trakt-Scrobbler/releases/tag/v1.2.0)

**Comment by bhogan4** [comment]
I am having an issue when using this new proxy feature. Not sure where I should make this comment so please let me know where to post this if it should not be here.

Running Version 1.3.0 of Track.tv bundle and version 3.6.0 python. Using PIA as proxy, confirmed credentials. Below is the error I am seeing:

2017-01-08 15:03:38,171 - plex_activity.sources.s_logging.main (e14) :  INFO (plex_activity.sources.s_logging.main:1159) - Opened file path: "X:\Users\USER\AppData\Local\Plex Media Server\Logs\Plex Media Server.log"
2017-01-08 15:03:38,960 - com.plexapp.plugins.trakttv      (1df0) :  CRITICAL (com.plexapp.plugins.trakttv:574) - Exception in thread named 'run' (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-b38628e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\runtime.py", line 1126, in _start_thread
    f(*args, **kwargs)
  File "X:\Users\USER\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Code\core\update_checker.py", line 66, in run
    response = self.request(first_run)
  File "X:\Users\USER\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Code\core\update_checker.py", line 51, in request
    response = requests.post(self.server + '/api/ping', data=json.dumps(data))
  File "X:\Users\USER\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "X:\Users\USER\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "X:\Users\USER\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "X:\Users\USER\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\raven\breadcrumbs.py", line 297, in send
    resp = real_send(self, request, *args, **kwargs)
  File "X:\Users\USER\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "X:\Users\USER\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
ConnectionError: ProtocolError: Connection aborted.

2017-01-08 15:03:40,463 - sentry.errors                    (29f8) :  ERROR (sentry.errors:671) - Sentry responded with an error: ProtocolError: Connection aborted. (url: https://sentry.skipthe.net/api/1/store/)
Traceback (most recent call last):
  File "X:\Users\USER\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\raven\transport\threaded_requests.py", line 26, in send_sync
    super(ThreadedRequestsHTTPTransport, self).send(data, headers)
  File "X:\Users\USER\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\raven\transport\requests.py", line 41, in send
    timeout=self.timeout
  File "X:\Users\USER\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "X:\Users\USER\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "X:\Users\USER\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "X:\Users\USER\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\raven\breadcrumbs.py", line 297, in send
    resp = real_send(self, request, *args, **kwargs)
  File "X:\Users\USER\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "X:\Users\USER\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
ConnectionError: ProtocolError: Connection aborted.

**Comment by fuzeman** [comment]
@bhogan4 Just pushed a fix to the development branch, download here: https://github.com/trakt/Plex-Trakt-Scrobbler/archive/develop.zip

**Comment by bhogan4** [comment]
@fuzeman Thank you! Confirmed working in v1.3.1.
