### ISSUE TITLE
Unable to retrieve account libraries/sections: Plex account hasn't been authenticated

### ISSUE THREAD

**Issue by Izzmo** [trakt/Plex-Trakt-Scrobbler#219]
Can't seem to get my account to authenticate.

I will do the pin, add it to the settings, the log shows it authenticates and gets my name, but when I try to sync it just fubars.

This is beta5.

Log:
```
2015-08-12 17:26:56,658 - plugin.interface.m_sync          (219c) :  WARNING (plugin.interface.m_sync:19) - Unable to retrieve account libraries/sections: Plex account hasn't been authenticated
Traceback (most recent call last):
  File "C:\Users\Me\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Code\interface\m_sync.py", line 123, in ControlsMenu
    with p_account.authorization():
  File "C:\Users\Me\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\models\m_plex\account.py", line 61, in authorization
    raise AccountAuthenticationError("Plex account hasn't been authenticated")
AccountAuthenticationError: Plex account hasn't been authenticated
2015-08-12 17:26:56,660 - root                             (219c) :  INFO (root:840) - 304 GET /video/trakt/sync (127.0.0.1) 7.00ms
2015-08-12 17:26:56,671 - root                             (17bc) :  INFO (root:840) - 200 GET /video/trakt/sync?message=Plex+account+hasn%27t+been+authenticated&account_id=1&message_only=True&title=Error (127.0.0.1) 4.00ms
2015-08-12 17:26:56,697 - requests.packages.urllib3.connectionpool (600) :  INFO (requests.packages.urllib3.connectionpool:700) - Starting new HTTPS connection (1): walter.trakt.us
```

**Comment by Izzmo** [comment]
So doing a little more research, looks like scrobbling works, but the plugin just exceptions on the sync.

Also, seeking causes another exception to occur in scrobbling.

**Comment by fuzeman** [comment]
Could you restart Plex Media Server, wait a few minutes *(to ensure the plugin has finished starting up)* and then upload the latest plugin log file.

On startup the plugin should automatically link your plex account *(this clearly isn't working though)*, scrobbling still works because it doesn't require access to your plex account.

**Comment by rectifyer** [comment]
I'm getting the same error as above. Just to test it out, I did a fresh install on the latest beta (removed the various support files) and here is the initial error I received.

```
2015-08-12 23:18:30,819 - requests.packages.urllib3.connectionpool (2b752fa85700) :  INFO (requests.packages.urllib3.connectionpool:223) - Resetting dropped connection: 127.0.0.1
2015-08-12 23:18:48,879 - plugin.modules.migrations.account (2b752ee58700) :  WARNING (plugin.modules.migrations.account:80) - Unable to refresh trakt account (not authenticated?)
Traceback (most recent call last):
  File "/config/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/modules/migrations/account.py", line 78, in create_administrator_account
    t_refreshed = t_account.refresh(force=t_created)
  File "/config/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/models/m_trakt/account.py", line 102, in refresh
    with self.authorization().http(retry=force):
  File "/config/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/models/m_trakt/account.py", line 74, in authorization
    raise AccountAuthenticationError("Trakt account hasn't been authenticated")
AccountAuthenticationError: Trakt account hasn't been authenticated
```
Then after going into the Sync menu, I get the same error as in the 1st post.

**Comment by fuzeman** [comment]
I've fixed a few authentication issues on the development branch ([develop.zip](https://github.com/trakt/Plex-Trakt-Scrobbler/archive/develop.zip)), after installing this version try setting a new trakt authentication pin in the settings to ensure the plugin is authenticated correctly.

**Note:** You need to be logged into your plex.tv account on Plex/Web for the plugin to configure everything correctly.

-----------------------------------

I'll release a new version with these fixes later tonight after some more testing.

**Comment by rectifyer** [comment]
Working! I got a new PIN and it authenticated correctly. Just ran a sync which also worked. Thanks!

**Comment by fuzeman** [comment]
Will close this now, fix was released in v0.9.10.6-beta

**Comment by Izzmo** [comment]
I'm still running into this on v0.9.10.8.

**Comment by Izzmo** [comment]
Here's the latest in the log if this helps:

2015-08-26 19:31:10,536 - root                             (1c2c) :  INFO (root:840) - 302 GET /video/trakt/sync (127.0.0.1) 6.00ms
2015-08-26 19:31:10,542 - root                             (1b90) :  INFO (root:840) - 200 GET /video/trakt/sync?message=Plex+account+hasn%27t+been+authenticated&account_id=1&message_only=True&title=Error (127.0.0.1) 3.00ms
2015-08-26 19:31:10,568 - requests.packages.urllib3.connectionpool (191c) :  INFO (requests.packages.urllib3.connectionpool:700) - Starting new HTTPS connection (1): walter.trakt.us
2015-08-26 19:31:11,217 - root                             (191c) :  INFO (root:840) - 200 GET /video/trakt/:/function/Cover.png?function_args=Y2VyZWFsMQoxCmRpY3QKMgppMQpzMTAKYWNjb3VudF9pZHMxMwoxNDQwNjM1NDcwLjU0czcKcmVmcmVzaHIwCg__ (127.0.0.1) 654.00ms
2015-08-26 19:31:43,486 - requests.packages.urllib3.connectionpool (4c4) :  INFO (requests.packages.urllib3.connectionpool:223) - Resetting dropped connection: 127.0.0.1
2015-08-26 19:32:14,894 - requests.packages.urllib3.connectionpool (4c4) :  INFO (requests.packages.urllib3.connectionpool:223) - Resetting dropped connection: 127.0.0.1
2015-08-26 19:32:46,105 - requests.packages.urllib3.connectionpool (4c4) :  INFO (requests.packages.urllib3.connectionpool:223) - Resetting dropped connection: 127.0.0.1
2015-08-26 19:33:17,392 - requests.packages.urllib3.connectionpool (4c4) :  INFO (requests.packages.urllib3.connectionpool:223) - Resetting dropped connection: 127.0.0.1
2015-08-26 19:33:48,855 - requests.packages.urllib3.connectionpool (4c4) :  INFO (requests.packages.urllib3.connectionpool:223) - Resetting dropped connection: 127.0.0.1
2015-08-26 19:34:20,233 - requests.packages.urllib3.connectionpool (4c4) :  INFO (requests.packages.urllib3.connectionpool:223) - Resetting dropped connection: 127.0.0.1
2015-08-26 19:34:51,621 - requests.packages.urllib3.connectionpool (4c4) :  INFO (requests.packages.urllib3.connectionpool:223) - Resetting dropped connection: 127.0.0.1
2015-08-26 19:35:23,029 - requests.packages.urllib3.connectionpool (4c4) :  INFO (requests.packages.urllib3.connectionpool:223) - Resetting dropped connection: 127.0.0.1
2015-08-26 19:35:54,552 - requests.packages.urllib3.connectionpool (4c4) :  INFO (requests.packages.urllib3.connectionpool:223) - Resetting dropped connection: 127.0.0.1
2015-08-26 19:36:26,091 - requests.packages.urllib3.connectionpool (4c4) :  INFO (requests.packages.urllib3.connectionpool:223) - Resetting dropped connection: 127.0.0.1
2015-08-26 19:36:35,930 - root                             (914) :  INFO (root:840) - 200 GET /:/plugins/com.plexapp.plugins.trakttv/prefs (127.0.0.1) 10.00ms
2015-08-26 19:36:52,413 - plugin                           (d88) :  ERROR (plugin:19) - No plex token found in environment and request
2015-08-26 19:36:52,414 - requests.packages.urllib3.connectionpool (d88) :  INFO (requests.packages.urllib3.connectionpool:188) - Starting new HTTP connection (1): sentry.skipthe.net
2015-08-26 19:36:52,628 - plugin.modules.migrations.account (d88) :  WARNING (plugin.modules.migrations.account:148) - No plex token available, unable to authenticate plex account
2015-08-26 19:36:52,642 - requests.packages.urllib3.connectionpool (d88) :  INFO (requests.packages.urllib3.connectionpool:223) - Resetting dropped connection: api-v2launch.trakt.tv
2015-08-26 19:36:53,062 - requests.packages.urllib3.connectionpool (d88) :  INFO (requests.packages.urllib3.connectionpool:700) - Starting new HTTPS connection (1): secure.gravatar.com
2015-08-26 19:36:53,252 - plugin.managers.m_trakt.account  (d88) :  INFO (plugin.managers.m_trakt.account:152) - Updated account authorization for <TraktAccount username: u'izzmo'>
2015-08-26 19:36:53,269 - root                             (d88) :  INFO (root:840) - 200 GET /:/plugins/com.plexapp.plugins.trakttv/prefs/set?pin=7D8D4826 (127.0.0.1) 858.00ms
2015-08-26 19:36:55,270 - root                             (1c84) :  INFO (root:840) - 304 GET /video/trakt (127.0.0.1) 10.00ms
2015-08-26 19:36:56,239 - root                             (1be0) :  INFO (root:840) - 304 GET /video/trakt (127.0.0.1) 10.00ms
2015-08-26 19:36:56,249 - plugin.interface.m_sync          (a14) :  WARNING (plugin.interface.m_sync:19) - Unable to retrieve account libraries/sections: Plex account hasn't been authenticated
Traceback (most recent call last):
  File "C:\Users\Me\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Code\interface\m_sync.py", line 123, in ControlsMenu
    with p_account.authorization():
  File "C:\Users\Me\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\models\m_plex\account.py", line 62, in authorization
    raise AccountAuthenticationError("Plex account hasn't been authenticated")
AccountAuthenticationError: Plex account hasn't been authenticated
2015-08-26 19:36:56,250 - root                             (a14) :  INFO (root:840) - 302 GET /video/trakt/sync (127.0.0.1) 6.00ms
2015-08-26 19:36:56,256 - root                             (1b14) :  INFO (root:840) - 200 GET /video/trakt/sync?message=Plex+account+hasn%27t+been+authenticated&account_id=1&message_only=True&title=Error (127.0.0.1) 4.00ms
2015-08-26 19:36:56,280 - requests.packages.urllib3.connectionpool (1050) :  INFO (requests.packages.urllib3.connectionpool:700) - Starting new HTTPS connection (1): walter.trakt.us
2015-08-26 19:36:56,747 - root                             (1050) :  INFO (root:840) - 200 GET /video/trakt/:/function/Cover.png?function_args=Y2VyZWFsMQoxCmRpY3QKMgppMQpzMTAKYWNjb3VudF9pZHMxMwoxNDQwNjM1ODE2LjI2czcKcmVmcmVzaHIwCg__ (127.0.0.1) 471.00ms

**Comment by fuzeman** [comment]
@Izzmo sounds like a similar issue to #222, have you logged into Plex/Web with your plex.tv account?

**Comment by khdaze** [comment]
Just had to sign up to mention I also had to generate a second PIN as well to resolve the issue.  First PIN did not work.  Latest files as of 5/15/16.
