### ISSUE TITLE
Scrobble not working under 0.9.10.13-beta

### ISSUE THREAD

**Issue by richipargo** [trakt/Plex-Trakt-Scrobbler#246]
I have issues scrobbling since updated to latest beta, logs throw this exception

```
2015-12-15 10:39:15,013 - pyemitter                        (7f3273fff700) :  WARNING (pyemitter:180) - Exception raised in callback <bound method WebSocket.on_playing of <plugin.scrobbler.methods.s_websocket.WebSocket object at 0x340e810>> for event "websocket.playing" - Traceback (most recent call last):
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/trakttv.bundle/Contents/Libraries/Shared/pyemitter.py", line 176, in __call_sync
    callback(*args, **kwargs)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/trakttv.bundle/Contents/Libraries/Shared/plugin/scrobbler/methods/s_websocket.py", line 49, in on_playing
    for action, payload in actions:
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/trakttv.bundle/Contents/Libraries/Shared/plugin/scrobbler/core/engine.py", line 19, in process
    for item in result:
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/trakttv.bundle/Contents/Libraries/Shared/plugin/scrobbler/core/engine.py", line 26, in process_one
    raise Exception('No handlers found for %r event' % key)
Exception: No handlers found for u'buffering' event
```

**Comment by fuzeman** [comment]
This message isn't a critical error, it just means the "buffering" event is ignored.

Could you send me the latest plugin log file (after watching something in plex again), either post a link here, or email me a link (me@dgardiner.net) if you don't want the log file public.

**Comment by richipargo** [comment]
Attaching log,

Thanks for the help
[com.plexapp.plugins.trakttv.log.zip](https://github.com/trakt/Plex-Trakt-Scrobbler/files/63580/com.plexapp.plugins.trakttv.log.zip)

**Comment by fuzeman** [comment]
It appears two users aren't being matched against any accounts:
```
2015-12-15 22:15:23,051 - INFO - Unable to match user 'richipargo' against any account
```

```
2015-12-15 22:59:06,059 - INFO - Unable to match user 'Rogarad' against any account
```

You can link these users to an account at http://trakt-for-plex.github.io/configuration on the "Rules" page. Let me know if you have any issues setting this up.

**Comment by richipargo** [comment]
Had to re add users to configuration, thanks
