### ISSUE TITLE
Syncing - Error messages - fresh log after scan attache

### ISSUE THREAD

**Issue by Paradoxum** [trakt/Plex-Trakt-Scrobbler#300]
[com.plexapp.plugins.trakttv.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/201499/com.plexapp.plugins.trakttv.txt)

Upgraded from last stable to the newest master, all seems to work fine scrobbling wise except these error messages,

**Comment by fuzeman** [comment]
This error is interesting:
```
Traceback (most recent call last):
  File "/usr/local/plexdata-plexpass/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/core/helpers/thread.py", line 93, in module_start
    f_start()
  File "/usr/local/plexdata-plexpass/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/modules/migrations/main.py", line 32, in start
    m.run()
  File "/usr/local/plexdata-plexpass/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/modules/migrations/preferences.py", line 19, in run
    Preferences.migrate(account=1)
  File "/usr/local/plexdata-plexpass/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/preferences/main.py", line 42, in migrate
    success = Preferences.on_plex_changed(key, Environment.prefs[key], account=account)
  File "/usr/local/share/plexmediaserver-plexpass/Resources/Plug-ins-cece46d/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/runtimekit.py", line 498, in __getitem__
    return self._sandbox.preferences.get()[name]
  File "/usr/local/share/plexmediaserver-plexpass/Resources/Plug-ins-cece46d/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/preferences.py", line 332, in __getitem__
    raise KeyError("No preference named '%s' found." % name)
KeyError: "No preference named 'sync_watchlist' found."
```

Not sure what would cause this though.. it appears to be an issue with the Plex Plugin Framework.

----------------------

The ```Unsupported service: none``` warnings just mean you have some unmatched media in your libraries, these items can't be added to your Trakt.tv profile.
