### ISSUE TITLE
V1.0.2.0 File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plex/core/configuration.py", line 109, in __exit__     assert item == self

### ISSUE THREAD

**Issue by waresfamily** [trakt/Plex-Trakt-Scrobbler#311]
Updated to the above version today but not syncing and receiving the above error message. I have searched on the above error message but have not found a recent solution. 

I have made plex owner of Trakttv.bundle and change Trakt pin

_Here are last 30 log entries_
2016-04-27 18:46:38,115 - requests.packages.urllib3.connectionpool (6f1b0470) :  INFO (requests.packages.urllib3.connectionpool:207) - Starting new HTTP connection (2): 127.0.0.1
2016-04-27 18:46:38,610 - plugin.sync.modes.core.base.mode (6e1b0470) :  INFO (plugin.sync.modes.core.base.mode:123) - Executing construct() on child: <plugin.sync.modes.push.shows.Shows object at 0x232d550>
2016-04-27 18:46:38,695 - requests.packages.urllib3.connectionpool (6e1b0470) :  INFO (requests.packages.urllib3.connectionpool:758) - Starting new HTTPS connection (4): api-v2launch.trakt.tv
2016-04-27 18:46:38,818 - plugin.sync.main                 (6e1b0470) :  WARNING (plugin.sync.main:133) - Exception raised in run():
Traceback (most recent call last):
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/sync/main.py", line 129, in run_wrapper
    self.run()
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plex/core/configuration.py", line 109, in __exit__
    assert item == self
AssertionError
2016-04-27 18:46:38,926 - plugin.core.backup.sources.database (6e1b0470) :  INFO (plugin.core.backup.sources.database:25) - [trakt/1] Backing up database to '/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-in Support/Data/com.plexapp.plugins.trakttv/Backups/trakt/1.bgr/2016/04/27_184638_14.db'
2016-04-27 18:46:38,958 - plugin.sync.main                 (6e1b0470) :  INFO (plugin.sync.main:150) - (2) Done
2016-04-27 18:46:40,121 - plugin.interface.m_sync          (6f1b0470) :  WARNING (plugin.interface.m_sync:19) - Unable to retrieve account libraries/sections:
Traceback (most recent call last):
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code/interface/m_sync.py", line 124, in ControlsMenu
    sections = Plex['library'].sections()
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plex/core/configuration.py", line 109, in __exit__
    assert item == self
AssertionError
2016-04-27 18:46:40,170 - root                             (6f1b0470) :  INFO (root:840) - 304 GET /video/trakt/sync?account_id=1 (127.0.0.1) 2136.52ms
2016-04-27 18:46:40,406 - root                             (6f1b0470) :  INFO (root:840) - 200 GET /video/trakt/sync?message=&account_id=1&message_only=True&title=Error (127.0.0.1) 203.28ms
2016-04-27 18:46:47,591 - root                             (6f1b0470) :  INFO (root:840) - 200 GET /video/trakt (127.0.0.1) 111.66ms
2016-04-27 18:46:49,332 - root                             (6f1b0470) :  INFO (root:840) - 200 GET /video/trakt/sync (127.0.0.1) 1686.75ms
2016-04-27 18:46:53,124 - root                             (6f1b0470) :  INFO (root:840) - 304 GET /video/trakt (127.0.0.1) 126.96ms
2016-04-27 18:46:55,187 - root                             (6f1b0470) :  INFO (root:840) - 304 GET /video/trakt (127.0.0.1) 116.64ms
2016-04-27 18:46:55,261 - root                             (6f1b0470) :  INFO (root:840) - 200 GET /video/trakt/messages/list?viewed=False (127.0.0.1) 45.68ms
2016-04-27 18:46:57,786 - root                             (6f1b0470) :  INFO (root:840) - 304 GET /video/trakt (127.0.0.1) 90.03ms
2016-04-27 18:46:57,922 - root                             (6f1b0470) :  INFO (root:840) - 200 GET /video/trakt/messages/view?error_id=1 (127.0.0.1) 108.05ms
2016-04-27 18:46:59,806 - root                             (6f1b0470) :  INFO (root:840) - 200 GET /video/trakt (127.0.0.1) 107.05ms
2016-04-27 18:46:59,895 - root                             (6f1b0470) :  INFO (root:840) - 200 GET /video/trakt/exceptions/view?exception_id=14 (127.0.0.1) 39.42ms

**Comment by fuzeman** [comment]
I'm not really sure what causes this issue yet (have never seen it happen on my server). Will need to do some further testing to work out what is causing this issue.
