### ISSUE TITLE
Trakt not showing up - All-winner 64bit ARM cpu

### ISSUE THREAD

**Issue by sandrosdj** [trakt/Plex-Trakt-Scrobbler#319]
I have a Pine64 Plus with an All-winner arm64 4 core cpu and the trakt plugin does not work.

```
2016-05-19 21:14:10,051 (-8c56df0) :  INFO (core:349) - Starting framework core - Version: 2.6.3, Build: 5089475 (Fri Apr 22 21:44:21 UTC 2016)
2016-05-19 21:14:10,053 (-8c56df0) :  DEBUG (core:361) - Using the elevated policy
2016-05-19 21:14:10,054 (-8c56df0) :  DEBUG (core:450) - Starting runtime component.
2016-05-19 21:14:10,060 (-8c56df0) :  DEBUG (core:450) - Starting caching component.
2016-05-19 21:14:10,061 (-8c56df0) :  DEBUG (core:450) - Starting data component.
2016-05-19 21:14:10,062 (-8c56df0) :  DEBUG (core:450) - Starting networking component.
2016-05-19 21:14:10,276 (-8c56df0) :  DEBUG (networking:282) - Loaded HTTP cookies
2016-05-19 21:14:10,495 (-8c56df0) :  DEBUG (networking:450) - Setting the default network timeout to 20.0
2016-05-19 21:14:10,499 (-8c56df0) :  DEBUG (core:450) - Starting localization component.
2016-05-19 21:14:10,500 (-8c56df0) :  INFO (localization:409) - Setting the default locale to en-us
2016-05-19 21:14:10,501 (-8c56df0) :  DEBUG (localization:427) - Loaded en strings
2016-05-19 21:14:10,502 (-8c56df0) :  DEBUG (core:450) - Starting messaging component.
2016-05-19 21:14:10,504 (-8c56df0) :  DEBUG (core:450) - Starting debugging component.
2016-05-19 21:14:10,505 (-8c56df0) :  DEBUG (core:450) - Starting services component.
2016-05-19 21:14:10,506 (-8c56df0) :  DEBUG (core:450) - Starting myplex component.
2016-05-19 21:14:10,507 (-8c56df0) :  DEBUG (core:450) - Starting notifications component.
2016-05-19 21:14:10,820 (-e700b90) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/system/messaging/clear_events/com.plexapp.plugins.trakttv'
2016-05-19 21:14:11,412 (-8c56df0) :  DEBUG (accessor:68) - Creating a new model access point for provider com.plexapp.plugins.trakttv in namespace 'metadata'
2016-05-19 21:14:11,559 (-8c56df0) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes'
2016-05-19 21:14:21,576 (-8c56df0) :  CRITICAL (runtime:1299) - Exception getting hosted resource hashes (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-5089475/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 1293, in get_resource_hashes
    json = self._core.networking.http_request("http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes", timeout=10).content
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-5089475/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 263, in content
    return self.__str__()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-5089475/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 241, in __str__
    self.load()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-5089475/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 181, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-5089475/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 438, in open
    response = self._open(req, data)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-5089475/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 456, in _open
    '_open', req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-5089475/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 416, in _call_chain
    result = func(*args)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-5089475/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1217, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-5089475/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1192, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>

2016-05-19 21:14:21,635 (-e700b90) :  DEBUG (services:265) - Plug-in is not daemonized - loading services from system
2016-05-19 21:14:21,636 (-8c56df0) :  DEBUG (runtime:1117) - Created a thread named 'load_all_services'
2016-05-19 21:14:21,640 (-8c56df0) :  DEBUG (runtime:1117) - Created a thread named 'get_server_info'
2016-05-19 21:14:21,641 (-8c56df0) :  DEBUG (core:150) - Finished starting framework core
2016-05-19 21:14:21,642 (-8c56df0) :  DEBUG (core:560) - Loading plug-in code
2016-05-19 21:14:21,793 (-8c56df0) :  DEBUG (core:566) - Finished loading plug-in code
2016-05-19 21:14:22,067 (-e700b90) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_'
2016-05-19 21:14:22,070 (-f700b90) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400'
2016-05-19 21:14:22,074 (-8c56df0) :  DEBUG (__init__:18) - Using locale: en_US.UTF-8
2016-05-19 21:14:22,522 (-8c56df0) :  DEBUG (fs_migrator:19) - Running migration: <fs_migrator.Clean object at 0x889890>
2016-05-19 21:14:22,546 (-8c56df0) :  DEBUG (fs_migrator:19) - Running migration: <fs_migrator.ForceLegacy object at 0x8898b0>
2016-05-19 21:14:22,611 (-8c56df0) :  ERROR (fs_migrator:382) - Unable to find preferences file at "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-in Support/Preferences/com.plexapp.plugins.trakttv.xml", unable to run migration
2016-05-19 21:14:22,612 (-8c56df0) :  DEBUG (fs_migrator:19) - Running migration: <fs_migrator.SelectiveSync object at 0x8897d0>
2016-05-19 21:14:22,614 (-8c56df0) :  ERROR (fs_migrator:46) - Unable to find preferences file at "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-in Support/Preferences/com.plexapp.plugins.trakttv.xml", unable to run migration
2016-05-19 21:14:30,372 - com.plexapp.plugins.trakttv      (-f700b90) :  DEBUG (com.plexapp.plugins.trakttv:538) - Machine identifier is 2dce4492b7b2753b2356010f77132ebbd864550b
2016-05-19 21:14:30,373 - com.plexapp.plugins.trakttv      (-f700b90) :  DEBUG (com.plexapp.plugins.trakttv:539) - Server version is 0.9.16.6.1993-5089475
2016-05-19 21:14:30,376 - plugin.core.logger.handlers.error_reporter.ErrorReporter (-8c56df0) :  DEBUG (plugin.core.logger.handlers.error_reporter.ErrorReporter:201) - Configuring Raven for host: threaded+requests+http://28ed2a0ee4c5468e92e0990ce41bc517:68d8a73d90e54b67a3a73b50f9dbadba@sentry.skipthe.net:/1
2016-05-19 21:14:34,275 - plugin.core.logger.main          (-8c56df0) :  DEBUG (plugin.core.logger.main:72) - Initialized logging (report: True, storage: False)
2016-05-19 21:14:47,199 - plugin.core.configuration        (-8c56df0) :  DEBUG (plugin.core.configuration:33) - Parsing configuration file: 'Data/com.plexapp.plugins.trakttv/advanced.ini'
2016-05-19 21:14:47,516 - com.plexapp.plugins.trakttv      (-e700b90) :  DEBUG (com.plexapp.plugins.trakttv:362) - Loaded services
2016-05-19 21:14:47,552 - com.plexapp.plugins.trakttv      (-ef00b90) :  DEBUG (com.plexapp.plugins.trakttv:438) - No shared code to load
2016-05-19 21:14:48,233 - plugin.core.libraries.main       (-8c56df0) :  INFO (plugin.core.libraries.main:168) - Cached libraries to 'Plug-in Support/Data/com.plexapp.plugins.trakttv/Libraries'
2016-05-19 21:14:48,234 - plugin.core.libraries.main       (-8c56df0) :  INFO (plugin.core.libraries.main:36) - Using native libraries at 'Plug-in Support/Data/com.plexapp.plugins.trakttv/Libraries'
2016-05-19 21:14:48,236 - plugin.core.libraries.helpers.path (-8c56df0) :  DEBUG (plugin.core.libraries.helpers.path:45) - Removed path: 'Plug-ins/Trakttv.bundle/Contents/Libraries/Linux/aarch64'
2016-05-19 21:14:48,237 - plugin.core.libraries.main       (-8c56df0) :  DEBUG (plugin.core.libraries.main:177) - Bits: '32bit', Machine: 'aarch64'
2016-05-19 21:14:48,238 - plugin.core.libraries.main       (-8c56df0) :  DEBUG (plugin.core.libraries.main:186) - System: 'Linux', Architecture: 'i386'
2016-05-19 21:14:48,239 - plugin.core.libraries.helpers.path (-8c56df0) :  DEBUG (plugin.core.libraries.helpers.path:30) - Inserted path: 'Plug-in Support/Data/com.plexapp.plugins.trakttv/Libraries/Linux/i386'
2016-05-19 21:14:48,241 - plugin.core.libraries.main       (-8c56df0) :  DEBUG (plugin.core.libraries.main:220) - UCS: 'ucs4'
2016-05-19 21:14:48,253 - plugin.core.libraries.helpers.path (-8c56df0) :  DEBUG (plugin.core.libraries.helpers.path:30) - Inserted path: 'Plug-in Support/Data/com.plexapp.plugins.trakttv/Libraries/Linux/i386/ucs4'
2016-05-19 21:14:48,255 - plugin.core.libraries.helpers.arm (-8c56df0) :  DEBUG (plugin.core.libraries.helpers.arm:115) - Fetching processor information from "/proc/cpuinfo"...
2016-05-19 21:14:48,258 - plugin.core.libraries.helpers.system (-8c56df0) :  INFO (plugin.core.libraries.helpers.system:198) - Executable at '' doesn't exist, using '/bin/ls' instead
2016-05-19 21:14:48,279 - plugin.core.libraries.helpers.system (-8c56df0) :  INFO (plugin.core.libraries.helpers.system:221) - Unable to find attributes section in ELF: '/bin/ls'
2016-05-19 21:14:48,283 - plugin.core.libraries.main       (-8c56df0) :  DEBUG (plugin.core.libraries.main:229) - CPU Type: None
2016-05-19 21:14:48,284 - plugin.core.libraries.main       (-8c56df0) :  DEBUG (plugin.core.libraries.main:230) - Page Size: '4k'
2016-05-19 21:14:48,285 - plugin.core.libraries.main       (-8c56df0) :  INFO (plugin.core.libraries.main:51) - [PATH] Plug-in Support/Data/com.plexapp.plugins.trakttv/Libraries/Linux/i386/ucs4
2016-05-19 21:14:48,287 - plugin.core.libraries.main       (-8c56df0) :  INFO (plugin.core.libraries.main:51) - [PATH] Plug-in Support/Data/com.plexapp.plugins.trakttv/Libraries/Linux/i386
2016-05-19 21:14:48,288 - plugin.core.libraries.main       (-8c56df0) :  INFO (plugin.core.libraries.main:51) - [PATH] Plug-ins/Trakttv.bundle/Contents/Libraries/Shared
2016-05-19 21:14:48,289 - plugin.core.libraries.main       (-8c56df0) :  INFO (plugin.core.libraries.main:56) - Testing native library support...
2016-05-19 21:14:48,294 - plugin.core.libraries.main       (-8c56df0) :  ERROR (plugin.core.libraries.main:66) - apsw: unavailable - Exception raised in 'test_import': /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-in Support/Data/com.plexapp.plugins.trakttv/Libraries/Linux/i386/ucs4/apsw.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/core/libraries/tests/core/base.py", line 33, in run
    result = func()
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/core/libraries/tests/apsw_.py", line 9, in test_import
    import apsw
ImportError: /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-in Support/Data/com.plexapp.plugins.trakttv/Libraries/Linux/i386/ucs4/apsw.so: cannot open shared object file: No such file or directory
2016-05-19 21:14:48,316 - plugin.core.logger.handlers.error_reporter.ErrorReporter (-8c56df0) :  DEBUG (plugin.core.logger.handlers.error_reporter.ErrorReporter:610) - Sending message of length 1732 to threaded+requests+http://sentry.skipthe.net/api/1/store/
2016-05-19 21:14:48,433 - requests.packages.urllib3.connectionpool (-ef00b90) :  INFO (requests.packages.urllib3.connectionpool:207) - Starting new HTTP connection (1): sentry.skipthe.net
2016-05-19 21:14:49,031 - requests.packages.urllib3.connectionpool (-ef00b90) :  DEBUG (requests.packages.urllib3.connectionpool:387) - "POST /api/1/store/ HTTP/1.1" 401 None
2016-05-19 21:14:49,035 - sentry.errors                    (-ef00b90) :  ERROR (sentry.errors:571) - Unable to capture event: APIError(Invalid api key)
2016-05-19 21:14:49,037 - sentry.errors                    (-ef00b90) :  ERROR (sentry.errors:576) - Raven has been disabled (Unauthorized API Key)
2016-05-19 21:14:49,101 - sentry.errors                    (-ef00b90) :  ERROR (sentry.errors:590) - Failed to submit message: u"apsw: unavailable - Exception raised in 'test_import': /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-in Support/Data/com.plexapp.plugins.trakttv/Libraries/Linux/i386/ucs4/apsw.so: cannot open shared object file: No such file or directory"
2016-05-19 21:14:49,105 - plugin.core.helpers              (-8c56df0) :  INFO (plugin.core.helpers:19) - Using 'simplejson' module for JSON serialization
2016-05-19 21:14:49,903 - com.plexapp.plugins.trakttv      (-8c56df0) :  CRITICAL (com.plexapp.plugins.trakttv:615) - Exception starting plug-in (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-5089475/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/core.py", line 608, in start
    self.sandbox.execute(self.init_code)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-5089475/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 256, in execute
    exec(code) in self.environment
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code/__init__.py", line 44, in <module>
    import interface
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-5089475/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 333, in __import__
    return mod.load_module(_name)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-5089475/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 44, in load_module
    module = RestrictedModule(name, path, sandbox)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-5089475/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/loader.py", line 30, in __init__
    exec(code) in self.__dict__
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code/interface/__init__.py", line 4, in <module>
    import m_sync
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-5089475/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 333, in __import__
    return mod.load_module(_name)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-5089475/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 44, in load_module
    module = RestrictedModule(name, path, sandbox)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-5089475/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/loader.py", line 30, in __init__
    exec(code) in self.__dict__
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code/interface/m_sync.py", line 8, in <module>
    from plugin.managers.account import AccountManager
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-5089475/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 345, in __import__
    raise e
ImportError: /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-in Support/Data/com.plexapp.plugins.trakttv/Libraries/Linux/i386/ucs4/apsw.so: cannot open shared object file: No such file or directory
 ```

**Comment by fuzeman** [comment]
Looks like the plugin isn't detecting your system correctly:
```
Bits: '32bit', Machine: 'aarch64'
System: 'Linux', Architecture: 'i386'
```

-----------------------

You can try override the cpu architecture detection by doing the following:

1. Create the ```Plug-in Support\Data\com.plexapp.plugins.trakttv\advanced.ini``` file with the following contents:

    ```
    [libraries]
    cpu_architecture = armv7_hf
    ```

2. Restart Plex Media Server

**Comment by sandrosdj** [comment]
Adding _cpu_architecture = armv7_hf_ solved the problem. Thank you!

**Comment by fuzeman** [comment]
Linux AArch64 systems are now properly supported in [v1.1.0.6](https://github.com/trakt/Plex-Trakt-Scrobbler/releases/tag/v1.1.0.6).

**Comment by marine1988** [comment]
im having this problems with orange pi prime i dont have advanced.ini files
