### ISSUE TITLE
Plugin not working on Synology

### ISSUE THREAD

**Issue by Manfred73** [trakt/Plex-Trakt-Scrobbler#322]
I would like to use this plugin to sync my Kodi watched settings via trakt with Plex.

I installed the plugin as described here: https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Installation%20-%20Linux%20(Shell)

After restarting plex, the plugin is available under channels. I configured the settings for the plugin and entered a pin. However, after rescanning the libraries in plex, nothing shows up in the traktv plugin within Plex.

Version of trakt plugin: master - 694e2f82e7333775b10136df9da3fa762c9ed663
Operating System: Synology DS2415+, INTEL Atom C2538
Plex Media Server: 0.9.16.6.1993-5089475, firmware 5.0-4458, architecture x86 cedarview bromolow evansport avoton braswell, Web version 2.6.1

Find attached the log file from trakt:
[com.plexapp.plugins.trakttv.zip](https://github.com/trakt/Plex-Trakt-Scrobbler/files/276312/com.plexapp.plugins.trakttv.zip)

**Comment by fuzeman** [comment]
```
/volume1/@appstore/Plex Media Server/Resources/Plug-ins-5089475/Trakttv.bundle
```

Looks like you've installed the plugin into the system plug-ins directory, it should be installed under the user plug-ins directory at:
```
/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/
```

See [this page](https://forums.plex.tv/discussion/182086/how-to-install-plugin-on-synology-nas) for more details.

**Comment by Manfred73** [comment]
Installing it under 

> /volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/

indeed seems to give me more options like Sync.
However, the Sync options all give an error: Trakt account hasn't been authenticated (see below and debug log attached).

In the Trakt plugin settings I tried several times to use a new pin (https://trakt.tv/pin/478), but this didn't help. Am I missing something else here?

```
2016-05-29 09:38:10,704 - plugin.sync.main                 (-d5ee4c0) :  WARNING (plugin.sync.main:163) - Exception raised in run(): Trakt account hasn't been authenticated
Traceback (most recent call last):
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/sync/main.py", line 159, in run_wrapper
    self.run()
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/sync/main.py", line 245, in run
    'stop'
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/sync/main.py", line 262, in _trigger
    func()
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/elapsed/main.py", line 64, in inner
    return func(*args, **kwargs)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/sync/modes/full.py", line 23, in start
    self.trakt.refresh()
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/elapsed/main.py", line 64, in inner
    return func(*args, **kwargs)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/sync/core/task/state/trakt_.py", line 90, in refresh
    raise AccountAuthenticationError("Trakt account hasn't been authenticated")
AccountAuthenticationError: Trakt account hasn't been authenticated

```
[com.plexapp.plugins.trakttv.zip](https://github.com/trakt/Plex-Trakt-Scrobbler/files/288264/com.plexapp.plugins.trakttv.zip)

**Comment by fuzeman** [comment]
I'm seeing this in your log file:
```
Request failed: Forbidden - "Invalid API key or unapproved app" (code: 403)
```

It looks like you tried to authenticate before the plugin finished starting up, so this might of caused an issue with the authentication process. I would try to authenticate again, but make sure to wait a minute for the plugin to startup completely after starting Plex Media Server.

I will also have a look at what can be done in the plugin to make sure authentication is delayed until the plugin is ready.

**Comment by Manfred73** [comment]
I've also triggered a manual sync after the plugin has started, but that also produces the error "Trakt account hasn't been authenticated".
