### ISSUE TITLE
Not Syncing Watched Status

### ISSUE THREAD

**Issue by JonathanGorbutt** [trakt/Plex-Trakt-Scrobbler#349]
Hi,

I just noticed on Trakt some episodes I have watched are not been synced.... I even checked Plex to make sure they are set as watched and then did a manual sync and still the same issue

I have tried a Full Sync and a Push TV Shows, even after that the episodes still are not set as watched.

Even downloaded the Beta version of your scrobbler and same issue.

http://pastebin.com/c7tUgN98 <- LOGS

**Comment by barneh** [comment]
I installed Plex some days ago and added this plugin, and I have the same problem. No watch history of my TV-Series are synced to Plex :(

And from what I can see from @JonathanGorbutt log file, I got the same error, "[Errno 10035] A non-blocking socket operation could not be completed immediately"

**Comment by jdchandler** [comment]
Hey guys I have the exact same error and issue. I just got a trakt account and I am only interested in sending my watch status FROM plex TO trakt. So I have it all set to PUSH and nothing is syncing at all.

I have very similar output in my log. Snippet below:

```
error: [Errno 10035] A non-blocking socket operation could not be completed immediately
2016-08-15 09:40:30,418 - plugin.modules.migrations.account (8c4) :  INFO (plugin.modules.migrations.account:244) - Plex Token: environment
2016-08-15 09:40:30,471 - root                             (8c4) :  INFO (root:840) - 200 GET /video/trakt/:/prefs/set?sync_playback=1 (127.0.0.1) 60.00ms
2016-08-15 09:54:17,438 - root                             (12b8) :  DEBUG (root:265) - Exception in I/O handler for fd 1376
Traceback (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-35f0caa\Framework.bundle\Contents\Resources\Platforms\Shared\Libraries\tornado\ioloop.py", line 256, in start
    self._handlers[fd](fd, events)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-35f0caa\Framework.bundle\Contents\Resources\Platforms\Shared\Libraries\tornado\stack_context.py", line 128, in wrapped
    callback(*args, **kwargs)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-35f0caa\Framework.bundle\Contents\Resources\Platforms\Shared\Libraries\tornado\httpserver.py", line 219, in _handle_events
    connection, address = self._socket.accept()
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\socket.py", line 202, in accept
    sock, addr = self._sock.accept()
```

**Comment by jdchandler** [comment]
update - all the sudden everything went through..not sure if issue was on Trakts side

**Comment by barneh** [comment]
After reading up on the faq I find out that I had to do a pull to get my Trakt history into my Plex db. But it's strange that this didn't happen when I did a Full run?!?

**Comment by fuzeman** [comment]
`A non-blocking socket operation could not be completed immediately` is a non-fatal message logged by the HTTP server inside the Plex Plugin Framework and isn't an indication of any issue with the plugin.

---------

@JonathanGorbutt Could you set all the "Logging" options to "DEBUG", run another full sync and post the log file here. I can't really see what's happening without the debug messages..

----------

@jdchandler 
> update - all the sudden everything went through..not sure if issue was on Trakts side

Syncs can fail sometimes due to issues with the Trakt.tv API, so it's possible that was the case..

---------

@barneh 
> After reading up on the faq I find out that I had to do a pull to get my Trakt history into my Plex db. But it's strange that this didn't happen when I did a Full run?!?

"Full" syncs only import changes to your Trakt.tv profile since your last sync, sometimes changes can be missed if a sync fails though. Running a "Pull" will check every item, and import any changes that haven't been applied to your Plex database yet.
