### ISSUE TITLE
Synology NAS 1515+

### ISSUE THREAD

**Issue by ricox00** [trakt/Plex-Trakt-Scrobbler#353]
Hi,

I installed the trakt.tv plug in using the UAS2 on my Synology NAS. It installed with no issues but it does not appear on the channels for Plex. I installed other channels in this manner successfully. I uninstalled the trak.tv plug in and used WinSCP to transfer different versions of the plug in but have been unsuccessful. I can't seem to get it to work. Any help would be greatly appreciated. Thank you in advance.

**Comment by fuzeman** [comment]
Try the suggestions listed here first: https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/FAQ---Installation#1-why-isnt-this-plugin-visible-under-channels-on-my-server

If those suggestions don't work could you provide the full plugin log file, see [this page](https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Log-files) for more details.

**Comment by ricox00** [comment]
Thank you for your prompt response. I have been unable to get it appear with the above instructions. Here is the log information.

2016-08-30 06:39:33,460 (-8e6f900) :  INFO (core:349) - Starting framework core - Version: 2.6.3, Build: 35f0caa (Thu Jul 28 02:45:59 UTC 2016)
2016-08-30 06:39:33,460 (-8e6f900) :  DEBUG (core:361) - Using the elevated policy
2016-08-30 06:39:33,461 (-8e6f900) :  DEBUG (core:450) - Starting runtime component.
2016-08-30 06:39:33,464 (-8e6f900) :  DEBUG (core:450) - Starting caching component.
2016-08-30 06:39:33,465 (-8e6f900) :  DEBUG (core:450) - Starting data component.
2016-08-30 06:39:33,465 (-8e6f900) :  DEBUG (core:450) - Starting networking component.
2016-08-30 06:39:33,466 (-8e6f900) :  DEBUG (networking:288) - No cookie jar found
2016-08-30 06:39:33,468 (-8e6f900) :  DEBUG (networking:452) - Setting the default network timeout to 20.0
2016-08-30 06:39:33,470 (-8e6f900) :  DEBUG (core:450) - Starting localization component.
2016-08-30 06:39:33,470 (-8e6f900) :  INFO (localization:409) - Setting the default locale to en-us
2016-08-30 06:39:33,471 (-8e6f900) :  DEBUG (localization:427) - Loaded en strings
2016-08-30 06:39:33,472 (-8e6f900) :  DEBUG (core:450) - Starting messaging component.
2016-08-30 06:39:33,473 (-8e6f900) :  DEBUG (core:450) - Starting debugging component.
2016-08-30 06:39:33,473 (-8e6f900) :  DEBUG (core:450) - Starting services component.
2016-08-30 06:39:33,474 (-8e6f900) :  DEBUG (core:450) - Starting myplex component.
2016-08-30 06:39:33,474 (-b6ee4c0) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/system/messaging/clear_events/com.plexapp.plugins.trakttv'
2016-08-30 06:39:33,475 (-8e6f900) :  DEBUG (core:450) - Starting notifications component.
2016-08-30 06:39:33,897 (-8e6f900) :  DEBUG (accessor:68) - Creating a new model access point for provider com.plexapp.plugins.trakttv in namespace 'metadata'
2016-08-30 06:39:33,912 (-8e6f900) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes'
2016-08-30 06:39:39,179 (-b6ee4c0) :  DEBUG (services:265) - Plug-in is not daemonized - loading services from system
2016-08-30 06:39:39,180 (-8e6f900) :  DEBUG (runtime:1117) - Created a thread named 'load_all_services'
2016-08-30 06:39:39,182 (-8e6f900) :  DEBUG (runtime:1117) - Created a thread named 'get_server_info'
2016-08-30 06:39:39,183 (-b6ee4c0) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_'
2016-08-30 06:39:39,185 (-bcca4c0) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400'
2016-08-30 06:39:39,186 (-8e6f900) :  DEBUG (core:150) - Finished starting framework core
2016-08-30 06:39:39,188 (-8e6f900) :  DEBUG (core:560) - Loading plug-in code
2016-08-30 06:39:39,219 (-bcca4c0) :  DEBUG (core:538) - Machine identifier is cbc5110e2e767dc7da32315fb5a983726c3ef462
2016-08-30 06:39:39,220 (-bcca4c0) :  DEBUG (core:539) - Server version is 1.0.3.2461-35f0caa
2016-08-30 06:39:39,281 (-8e6f900) :  DEBUG (core:566) - Finished loading plug-in code
2016-08-30 06:39:39,915 (-8e6f900) :  DEBUG (fs_migrator:19) - Running migration: <fs_migrator.Clean object at 0x8a4656c>
2016-08-30 06:39:39,916 (-b6ee4c0) :  DEBUG (services:362) - Loaded services
2016-08-30 06:39:39,934 (-b9dc4c0) :  DEBUG (services:438) - No shared code to load
2016-08-30 06:39:39,947 (-8e6f900) :  DEBUG (fs_migrator:19) - Running migration: <fs_migrator.ForceLegacy object at 0x8a4658c>
2016-08-30 06:39:39,947 (-8e6f900) :  ERROR (fs_migrator:388) - Unable to find preferences file at "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-in Support/Preferences/com.plexapp.plugins.trakttv.xml", unable to run migration
2016-08-30 06:39:39,948 (-8e6f900) :  DEBUG (fs_migrator:19) - Running migration: <fs_migrator.SelectiveSync object at 0x8a465ac>
2016-08-30 06:39:39,949 (-8e6f900) :  ERROR (fs_migrator:46) - Unable to find preferences file at "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-in Support/Preferences/com.plexapp.plugins.trakttv.xml", unable to run migration
2016-08-30 06:39:40,674 - plugin.core.logger.handlers.error_reporter.ErrorReporter (-8e6f900) :  DEBUG (plugin.core.logger.handlers.error_reporter.ErrorReporter:201) - Configuring Raven for host: threaded+requests+http://6afe79a788d64af2ad3f0f5a7fc83912:fdcabc5f09aa4b7b93edfb21263bb33e@sentry.skipthe.net:/1
2016-08-30 06:39:40,676 - plugin.core.logger.main          (-8e6f900) :  DEBUG (plugin.core.logger.main:72) - Initialized logging (report: True, storage: False)
2016-08-30 06:39:40,677 - com.plexapp.plugins.trakttv      (-8e6f900) :  DEBUG (com.plexapp.plugins.trakttv:258) - Loaded preferences from DefaultPrefs.json
2016-08-30 06:39:40,679 - com.plexapp.plugins.trakttv      (-8e6f900) :  INFO (com.plexapp.plugins.trakttv:161) - No user preferences file exists
2016-08-30 06:39:40,681 - com.plexapp.plugins.trakttv      (-8e6f900) :  DEBUG (com.plexapp.plugins.trakttv:198) - Saved the user preferences
2016-08-30 06:39:40,682 - plugin.core.environment          (-8e6f900) :  WARNING (plugin.core.environment:116) - Unable to set locale to 'en_US': unsupported locale setting
Traceback (most recent call last):
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/core/environment.py", line 114, in setup_locale
    locale.setlocale(locale.LC_ALL, DEFAULT_LOCALE)
  File "/data/jenkins/pms-deps-universal-v2/BUILD_TAG/linux-synology-i686/output/pms-depends-linux-synology-i686-release-c0dbc55/lib/python2.7/locale.py", line 547, in setlocale
Error: unsupported locale setting
2016-08-30 06:39:40,698 - plugin.core.logger.handlers.error_reporter.ErrorReporter (-8e6f900) :  DEBUG (plugin.core.logger.handlers.error_reporter.ErrorReporter:610) - Sending message of length 1516 to threaded+requests+http://sentry.skipthe.net/api/1/store/
2016-08-30 06:39:40,729 - plugin.core.environment          (-8e6f900) :  INFO (plugin.core.environment:192) - Unable to detect system language, defaulting to the "en_US" locale
2016-08-30 06:39:40,776 - requests.packages.urllib3.connectionpool (-b9dc4c0) :  INFO (requests.packages.urllib3.connectionpool:213) - Starting new HTTP connection (1): sentry.skipthe.net
2016-08-30 06:39:40,782 - plugin.core.environment          (-8e6f900) :  INFO (plugin.core.environment:165) - Using languages: ['en_us', 'en'] (translation: <gettext.GNUTranslations instance at 0x8b599ec>)
2016-08-30 06:39:41,016 - plugin.core.configuration        (-8e6f900) :  DEBUG (plugin.core.configuration:33) - Parsing configuration file: 'Data/com.plexapp.plugins.trakttv/advanced.ini'
2016-08-30 06:39:41,092 - plugin.core.libraries.helpers.storage (-8e6f900) :  DEBUG (plugin.core.libraries.helpers.storage:83) - Copied 'Plug-ins/Trakttv.bundle/Contents/Libraries/Linux/i386/ucs2' to 'Plug-in Support/Data/com.plexapp.plugins.trakttv/Libraries/Linux/i386/ucs2'
2016-08-30 06:39:41,165 - plugin.core.libraries.helpers.storage (-8e6f900) :  DEBUG (plugin.core.libraries.helpers.storage:83) - Copied 'Plug-ins/Trakttv.bundle/Contents/Libraries/Linux/i386/ucs4' to 'Plug-in Support/Data/com.plexapp.plugins.trakttv/Libraries/Linux/i386/ucs4'
2016-08-30 06:39:41,166 - plugin.core.libraries.manager    (-8e6f900) :  INFO (plugin.core.libraries.manager:189) - Cached libraries to 'Plug-in Support/Data/com.plexapp.plugins.trakttv/Libraries'
2016-08-30 06:39:41,166 - plugin.core.libraries.manager    (-8e6f900) :  INFO (plugin.core.libraries.manager:36) - Using native libraries at 'Plug-in Support/Data/com.plexapp.plugins.trakttv/Libraries'
2016-08-30 06:39:41,167 - plugin.core.libraries.helpers.path (-8e6f900) :  DEBUG (plugin.core.libraries.helpers.path:45) - Removed path: 'Plug-ins/Trakttv.bundle/Contents/Libraries/Linux/i386'
2016-08-30 06:39:41,168 - plugin.core.libraries.manager    (-8e6f900) :  DEBUG (plugin.core.libraries.manager:198) - Bits: '32bit', Machine: 'x86_64'
2016-08-30 06:39:41,168 - plugin.core.libraries.manager    (-8e6f900) :  DEBUG (plugin.core.libraries.manager:207) - System: 'Linux', Architecture: 'i386'
2016-08-30 06:39:41,169 - plugin.core.libraries.helpers.path (-8e6f900) :  DEBUG (plugin.core.libraries.helpers.path:30) - Inserted path: 'Plug-in Support/Data/com.plexapp.plugins.trakttv/Libraries/Linux/i386'
2016-08-30 06:39:41,169 - plugin.core.libraries.manager    (-8e6f900) :  DEBUG (plugin.core.libraries.manager:241) - UCS: 'ucs4'
2016-08-30 06:39:41,170 - plugin.core.libraries.helpers.path (-8e6f900) :  DEBUG (plugin.core.libraries.helpers.path:30) - Inserted path: 'Plug-in Support/Data/com.plexapp.plugins.trakttv/Libraries/Linux/i386/ucs4'
2016-08-30 06:39:41,171 - plugin.core.libraries.helpers.arm (-8e6f900) :  DEBUG (plugin.core.libraries.helpers.arm:115) - Fetching processor information from "/proc/cpuinfo"...
2016-08-30 06:39:41,172 - plugin.core.libraries.helpers.arm (-8e6f900) :  INFO (plugin.core.libraries.helpers.arm:44) - Unable to retrieve processor identifier from "/proc/cpuinfo"
2016-08-30 06:39:41,173 - plugin.core.libraries.helpers.system (-8e6f900) :  INFO (plugin.core.libraries.helpers.system:198) - Executable at '' doesn't exist, using '/bin/ls' instead
2016-08-30 06:39:41,183 - plugin.core.libraries.helpers.system (-8e6f900) :  INFO (plugin.core.libraries.helpers.system:221) - Unable to find attributes section in ELF: '/bin/ls'
2016-08-30 06:39:41,193 - plugin.core.libraries.manager    (-8e6f900) :  DEBUG (plugin.core.libraries.manager:250) - CPU Type: None
2016-08-30 06:39:41,194 - plugin.core.libraries.manager    (-8e6f900) :  DEBUG (plugin.core.libraries.manager:251) - Page Size: '4k'
2016-08-30 06:39:41,195 - plugin.core.libraries.manager    (-8e6f900) :  INFO (plugin.core.libraries.manager:51) - [PATH] Plug-in Support/Data/com.plexapp.plugins.trakttv/Libraries/Linux/i386/ucs4
2016-08-30 06:39:41,195 - plugin.core.libraries.manager    (-8e6f900) :  INFO (plugin.core.libraries.manager:51) - [PATH] Plug-in Support/Data/com.plexapp.plugins.trakttv/Libraries/Linux/i386
2016-08-30 06:39:41,196 - plugin.core.libraries.manager    (-8e6f900) :  INFO (plugin.core.libraries.manager:51) - [PATH] Plug-ins/Trakttv.bundle/Contents/Libraries/Shared
2016-08-30 06:39:41,197 - plugin.core.libraries.manager    (-8e6f900) :  INFO (plugin.core.libraries.manager:56) - Testing native library support...
2016-08-30 06:39:41,197 - plugin.core.libraries.tests.core.base (-8e6f900) :  DEBUG (plugin.core.libraries.tests.core.base:96) - Starting test: plugin.core.libraries.tests.apsw_:test_import
2016-08-30 06:39:41,437 - plugin.core.libraries.manager    (-8e6f900) :  INFO (plugin.core.libraries.manager:102) - apsw: available (sqlite: 3010002, apsw: 3.10.2-r1)
2016-08-30 06:39:41,438 - plugin.core.libraries.tests.core.base (-8e6f900) :  DEBUG (plugin.core.libraries.tests.core.base:96) - Starting test: plugin.core.libraries.tests.cryptography_:test_import
2016-08-30 06:39:41,627 - root                             (-8e6f900) :  WARNING (root:1601) - cryptography: unavailable - libffi.so.6: cannot open shared object file: No such file or directory
2016-08-30 06:39:41,631 - plugin.core.logger.handlers.error_reporter.ErrorReporter (-8e6f900) :  DEBUG (plugin.core.logger.handlers.error_reporter.ErrorReporter:610) - Sending message of length 1104 to threaded+requests+http://sentry.skipthe.net/api/1/store/
2016-08-30 06:39:41,632 - plugin.core.libraries.tests.core.base (-8e6f900) :  DEBUG (plugin.core.libraries.tests.core.base:96) - Starting test: plugin.core.libraries.tests.llist_:test_import
2016-08-30 06:39:41,793 - plugin.core.libraries.manager    (-8e6f900) :  INFO (plugin.core.libraries.manager:109) - llist: available
2016-08-30 06:39:41,794 - plugin.core.libraries.tests.core.base (-8e6f900) :  DEBUG (plugin.core.libraries.tests.core.base:96) - Starting test: plugin.core.libraries.tests.openssl_:test_import
2016-08-30 06:39:42,005 - root                             (-8e6f900) :  WARNING (root:1601) - openssl: unavailable - libffi.so.6: cannot open shared object file: No such file or directory
2016-08-30 06:39:42,008 - plugin.core.logger.handlers.error_reporter.ErrorReporter (-8e6f900) :  DEBUG (plugin.core.logger.handlers.error_reporter.ErrorReporter:610) - Sending message of length 1096 to threaded+requests+http://sentry.skipthe.net/api/1/store/
2016-08-30 06:39:42,325 - plugin.core.helpers              (-8e6f900) :  INFO (plugin.core.helpers:19) - Using 'simplejson' module for JSON serialization
2016-08-30 06:39:42,898 - plugin.core.helpers.database     (-8e6f900) :  DEBUG (plugin.core.helpers.database:20) - Connected to database at '/volume1/Plex/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.trakttv.db'
2016-08-30 06:39:43,237 - pyemitter                        (-8e6f900) :  DEBUG (pyemitter:45) - [plex_activity.activity.Activity   ]:on(events: ['websocket.timeline.created'], func: <bound method Metadata.timeline_created of <plex_metadata.metadata.Metadata object at 0x91aca0c>>)
2016-08-30 06:39:43,237 - pyemitter                        (-8e6f900) :  DEBUG (pyemitter:45) - [plex_activity.activity.Activity   ]:on(events: ['websocket.timeline.deleted'], func: <bound method Metadata.timeline_deleted of <plex_metadata.metadata.Metadata object at 0x91aca0c>>)
2016-08-30 06:39:43,238 - pyemitter                        (-8e6f900) :  DEBUG (pyemitter:45) - [plex_activity.activity.Activity   ]:on(events: ['websocket.timeline.finished'], func: <bound method Metadata.timeline_finished of <plex_metadata.metadata.Metadata object at 0x91aca0c>>)
2016-08-30 06:39:43,404 - plex_database.core.database      (-8e6f900) :  DEBUG (plex_database.core.database:17) - Connecting to '/volume1/Plex/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.library.db'
2016-08-30 06:39:43,522 - com.plexapp.plugins.trakttv      (-8e6f900) :  CRITICAL (com.plexapp.plugins.trakttv:615) - Exception starting plug-in (most recent call last):
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-35f0caa/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/core.py", line 608, in start
    self.sandbox.execute(self.init_code)
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-35f0caa/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 256, in execute
    exec(code) in self.environment
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code/__init__.py", line 51, in <module>
    import interface
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-35f0caa/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 333, in __import__
    return mod.load_module(_name)
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-35f0caa/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 44, in load_module
    module = RestrictedModule(name, path, sandbox)
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-35f0caa/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/loader.py", line 30, in __init__
    exec(code) in self.__dict__
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code/interface/__init__.py", line 4, in <module>
    import m_sync
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-35f0caa/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 333, in __import__
    return mod.load_module(_name)
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-35f0caa/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 44, in load_module
    module = RestrictedModule(name, path, sandbox)
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-35f0caa/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/loader.py", line 30, in __init__
    exec(code) in self.__dict__
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code/interface/m_sync.py", line 11, in <module>
    from plugin.sync.main import Sync, QueueError
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-35f0caa/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 345, in __import__
    raise e
UnknownTimeZoneError: 'Timezone/Pacific'

2016-08-30 06:39:43,674 - plugin.core.logger.handlers.error_reporter.ErrorReporter (-8e6f900) :  DEBUG (plugin.core.logger.handlers.error_reporter.ErrorReporter:610) - Sending message of length 3388 to threaded+requests+http://sentry.skipthe.net/api/1/store/
2016-08-30 06:39:45,996 - requests.packages.urllib3.connectionpool (-b9dc4c0) :  DEBUG (requests.packages.urllib3.connectionpool:395) - "POST /api/1/store/ HTTP/1.1" 200 41
2016-08-30 06:39:46,003 - requests.packages.urllib3.connectionpool (-b9dc4c0) :  INFO (requests.packages.urllib3.connectionpool:213) - Starting new HTTP connection (1): sentry.skipthe.net
2016-08-30 06:39:51,242 - requests.packages.urllib3.connectionpool (-b9dc4c0) :  DEBUG (requests.packages.urllib3.connectionpool:395) - "POST /api/1/store/ HTTP/1.1" 200 41
2016-08-30 06:39:51,248 - requests.packages.urllib3.connectionpool (-b9dc4c0) :  INFO (requests.packages.urllib3.connectionpool:213) - Starting new HTTP connection (1): sentry.skipthe.net
2016-08-30 06:39:56,530 - requests.packages.urllib3.connectionpool (-b9dc4c0) :  DEBUG (requests.packages.urllib3.connectionpool:395) - "POST /api/1/store/ HTTP/1.1" 200 41
2016-08-30 06:39:56,535 - requests.packages.urllib3.connectionpool (-b9dc4c0) :  INFO (requests.packages.urllib3.connectionpool:213) - Starting new HTTP connection (1): sentry.skipthe.net
2016-08-30 06:40:01,823 - requests.packages.urllib3.connectionpool (-b9dc4c0) :  DEBUG (requests.packages.urllib3.connectionpool:395) - "POST /api/1/store/ HTTP/1.1" 200 41
