### ISSUE TITLE
Synology NAS 1515+

### ISSUE THREAD

**Issue by ricox00** [trakt/Plex-Trakt-Scrobbler#354]
I am not sure why it said I closed the previous post. But this is my log for the issue I was having before.

Thank you for your prompt response. I have been unable to get it appear with the above instructions. Here is the log information.

2016-08-30 06:39:33,460 (-8e6f900) : INFO (core:349) - Starting framework core - Version: 2.6.3, Build: 35f0caa (Thu Jul 28 02:45:59 UTC 2016)
 2016-08-30 06:39:33,460 (-8e6f900) : DEBUG (core:361) - Using the elevated policy
 2016-08-30 06:39:33,461 (-8e6f900) : DEBUG (core:450) - Starting runtime component.
 2016-08-30 06:39:33,464 (-8e6f900) : DEBUG (core:450) - Starting caching component.
 2016-08-30 06:39:33,465 (-8e6f900) : DEBUG (core:450) - Starting data component.
 2016-08-30 06:39:33,465 (-8e6f900) : DEBUG (core:450) - Starting networking component.
 2016-08-30 06:39:33,466 (-8e6f900) : DEBUG (networking:288) - No cookie jar found
 2016-08-30 06:39:33,468 (-8e6f900) : DEBUG (networking:452) - Setting the default network timeout to 20.0
 2016-08-30 06:39:33,470 (-8e6f900) : DEBUG (core:450) - Starting localization component.
 2016-08-30 06:39:33,470 (-8e6f900) : INFO (localization:409) - Setting the default locale to en-us
 2016-08-30 06:39:33,471 (-8e6f900) : DEBUG (localization:427) - Loaded en strings
 2016-08-30 06:39:33,472 (-8e6f900) : DEBUG (core:450) - Starting messaging component.
 2016-08-30 06:39:33,473 (-8e6f900) : DEBUG (core:450) - Starting debugging component.
 2016-08-30 06:39:33,473 (-8e6f900) : DEBUG (core:450) - Starting services component.
 2016-08-30 06:39:33,474 (-8e6f900) : DEBUG (core:450) - Starting myplex component.
 2016-08-30 06:39:33,474 (-b6ee4c0) : DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/system/messaging/clear_events/com.plexapp.plugins.trakttv'
 2016-08-30 06:39:33,475 (-8e6f900) : DEBUG (core:450) - Starting notifications component.
 2016-08-30 06:39:33,897 (-8e6f900) : DEBUG (accessor:68) - Creating a new model access point for provider com.plexapp.plugins.trakttv in namespace 'metadata'
 2016-08-30 06:39:33,912 (-8e6f900) : DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes'
 2016-08-30 06:39:39,179 (-b6ee4c0) : DEBUG (services:265) - Plug-in is not daemonized - loading services from system
 2016-08-30 06:39:39,180 (-8e6f900) : DEBUG (runtime:1117) - Created a thread named 'load_all_services'
 2016-08-30 06:39:39,182 (-8e6f900) : DEBUG (runtime:1117) - Created a thread named 'get_server_info'
 2016-08-30 06:39:39,183 (-b6ee4c0) : DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_'
 2016-08-30 06:39:39,185 (-bcca4c0) : DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400'
 2016-08-30 06:39:39,186 (-8e6f900) : DEBUG (core:150) - Finished starting framework core
 2016-08-30 06:39:39,188 (-8e6f900) : DEBUG (core:560) - Loading plug-in code
 2016-08-30 06:39:39,219 (-bcca4c0) : DEBUG (core:538) - Machine identifier is cbc5110e2e767dc7da32315fb5a983726c3ef462
 2016-08-30 06:39:39,220 (-bcca4c0) : DEBUG (core:539) - Server version is 1.0.3.2461-35f0caa
 2016-08-30 06:39:39,281 (-8e6f900) : DEBUG (core:566) - Finished loading plug-in code
 2016-08-30 06:39:39,915 (-8e6f900) : DEBUG (fs_migrator:19) - Running migration: 
 2016-08-30 06:39:39,916 (-b6ee4c0) : DEBUG (services:362) - Loaded services
 2016-08-30 06:39:39,934 (-b9dc4c0) : DEBUG (services:438) - No shared code to load
 2016-08-30 06:39:39,947 (-8e6f900) : DEBUG (fs_migrator:19) - Running migration: 
 2016-08-30 06:39:39,947 (-8e6f900) : ERROR (fs_migrator:388) - Unable to find preferences file at "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-in Support/Preferences/com.plexapp.plugins.trakttv.xml", unable to run migration
 2016-08-30 06:39:39,948 (-8e6f900) : DEBUG (fs_migrator:19) - Running migration: 
 2016-08-30 06:39:39,949 (-8e6f900) : ERROR (fs_migrator:46) - Unable to find preferences file at "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-in Support/Preferences/com.plexapp.plugins.trakttv.xml", unable to run migration
 2016-08-30 06:39:40,674 - plugin.core.logger.handlers.error_reporter.ErrorReporter (-8e6f900) : DEBUG (plugin.core.logger.handlers.error_reporter.ErrorReporter:201) - Configuring Raven for host: threaded+requests+http://6afe79a788d64af2ad3f0f5a7fc83912:fdcabc5f09aa4b7b93edfb21263bb33e@sentry.skipthe.net:/1
 2016-08-30 06:39:40,676 - plugin.core.logger.main (-8e6f900) : DEBUG (plugin.core.logger.main:72) - Initialized logging (report: True, storage: False)
 2016-08-30 06:39:40,677 - com.plexapp.plugins.trakttv (-8e6f900) : DEBUG (com.plexapp.plugins.trakttv:258) - Loaded preferences from DefaultPrefs.json
 2016-08-30 06:39:40,679 - com.plexapp.plugins.trakttv (-8e6f900) : INFO (com.plexapp.plugins.trakttv:161) - No user preferences file exists
 2016-08-30 06:39:40,681 - com.plexapp.plugins.trakttv (-8e6f900) : DEBUG (com.plexapp.plugins.trakttv:198) - Saved the user preferences
 2016-08-30 06:39:40,682 - plugin.core.environment (-8e6f900) : WARNING (plugin.core.environment:116) - Unable to set locale to 'en_US': unsupported locale setting
 Traceback (most recent call last):
 File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/core/environment.py", line 114, in setup_locale
 locale.setlocale(locale.LC_ALL, DEFAULT_LOCALE)
 File "/data/jenkins/pms-deps-universal-v2/BUILD_TAG/linux-synology-i686/output/pms-depends-linux-synology-i686-release-c0dbc55/lib/python2.7/locale.py", line 547, in setlocale
 Error: unsupported locale setting
 2016-08-30 06:39:40,698 - plugin.core.logger.handlers.error_reporter.ErrorReporter (-8e6f900) : DEBUG (plugin.core.logger.handlers.error_reporter.ErrorReporter:610) - Sending message of length 1516 to threaded+requests+http://sentry.skipthe.net/api/1/store/
 2016-08-30 06:39:40,729 - plugin.core.environment (-8e6f900) : INFO (plugin.core.environment:192) - Unable to detect system language, defaulting to the "en_US" locale
 2016-08-30 06:39:40,776 - requests.packages.urllib3.connectionpool (-b9dc4c0) : INFO (requests.packages.urllib3.connectionpool:213) - Starting new HTTP connection (1): sentry.skipthe.net
 2016-08-30 06:39:40,782 - plugin.core.environment (-8e6f900) : INFO (plugin.core.environment:165) - Using languages: 'en_us', 'en'
 2016-08-30 06:39:41,016 - plugin.core.configuration (-8e6f900) : DEBUG (plugin.core.configuration:33) - Parsing configuration file: 'Data/com.plexapp.plugins.trakttv/advanced.ini'
 2016-08-30 06:39:41,092 - plugin.core.libraries.helpers.storage (-8e6f900) : DEBUG (plugin.core.libraries.helpers.storage:83) - Copied 'Plug-ins/Trakttv.bundle/Contents/Libraries/Linux/i386/ucs2' to 'Plug-in Support/Data/com.plexapp.plugins.trakttv/Libraries/Linux/i386/ucs2'
 2016-08-30 06:39:41,165 - plugin.core.libraries.helpers.storage (-8e6f900) : DEBUG (plugin.core.libraries.helpers.storage:83) - Copied 'Plug-ins/Trakttv.bundle/Contents/Libraries/Linux/i386/ucs4' to 'Plug-in Support/Data/com.plexapp.plugins.trakttv/Libraries/Linux/i386/ucs4'
 2016-08-30 06:39:41,166 - plugin.core.libraries.manager (-8e6f900) : INFO (plugin.core.libraries.manager:189) - Cached libraries to 'Plug-in Support/Data/com.plexapp.plugins.trakttv/Libraries'
 2016-08-30 06:39:41,166 - plugin.core.libraries.manager (-8e6f900) : INFO (plugin.core.libraries.manager:36) - Using native libraries at 'Plug-in Support/Data/com.plexapp.plugins.trakttv/Libraries'
 2016-08-30 06:39:41,167 - plugin.core.libraries.helpers.path (-8e6f900) : DEBUG (plugin.core.libraries.helpers.path:45) - Removed path: 'Plug-ins/Trakttv.bundle/Contents/Libraries/Linux/i386'
 2016-08-30 06:39:41,168 - plugin.core.libraries.manager (-8e6f900) : DEBUG (plugin.core.libraries.manager:198) - Bits: '32bit', Machine: 'x86_64'
 2016-08-30 06:39:41,168 - plugin.core.libraries.manager (-8e6f900) : DEBUG (plugin.core.libraries.manager:207) - System: 'Linux', Architecture: 'i386'
 2016-08-30 06:39:41,169 - plugin.core.libraries.helpers.path (-8e6f900) : DEBUG (plugin.core.libraries.helpers.path:30) - Inserted path: 'Plug-in Support/Data/com.plexapp.plugins.trakttv/Libraries/Linux/i386'
 2016-08-30 06:39:41,169 - plugin.core.libraries.manager (-8e6f900) : DEBUG (plugin.core.libraries.manager:241) - UCS: 'ucs4'
 2016-08-30 06:39:41,170 - plugin.core.libraries.helpers.path (-8e6f900) : DEBUG (plugin.core.libraries.helpers.path:30) - Inserted path: 'Plug-in Support/Data/com.plexapp.plugins.trakttv/Libraries/Linux/i386/ucs4'
 2016-08-30 06:39:41,171 - plugin.core.libraries.helpers.arm (-8e6f900) : DEBUG (plugin.core.libraries.helpers.arm:115) - Fetching processor information from "/proc/cpuinfo"...
 2016-08-30 06:39:41,172 - plugin.core.libraries.helpers.arm (-8e6f900) : INFO (plugin.core.libraries.helpers.arm:44) - Unable to retrieve processor identifier from "/proc/cpuinfo"
 2016-08-30 06:39:41,173 - plugin.core.libraries.helpers.system (-8e6f900) : INFO (plugin.core.libraries.helpers.system:198) - Executable at '' doesn't exist, using '/bin/ls' instead
 2016-08-30 06:39:41,183 - plugin.core.libraries.helpers.system (-8e6f900) : INFO (plugin.core.libraries.helpers.system:221) - Unable to find attributes section in ELF: '/bin/ls'
 2016-08-30 06:39:41,193 - plugin.core.libraries.manager (-8e6f900) : DEBUG (plugin.core.libraries.manager:250) - CPU Type: None
 2016-08-30 06:39:41,194 - plugin.core.libraries.manager (-8e6f900) : DEBUG (plugin.core.libraries.manager:251) - Page Size: '4k'
 2016-08-30 06:39:41,195 - plugin.core.libraries.manager (-8e6f900) : INFO (plugin.core.libraries.manager:51) - [PATH] Plug-in Support/Data/com.plexapp.plugins.trakttv/Libraries/Linux/i386/ucs4
 2016-08-30 06:39:41,195 - plugin.core.libraries.manager (-8e6f900) : INFO (plugin.core.libraries.manager:51) - [PATH] Plug-in Support/Data/com.plexapp.plugins.trakttv/Libraries/Linux/i386
 2016-08-30 06:39:41,196 - plugin.core.libraries.manager (-8e6f900) : INFO (plugin.core.libraries.manager:51) - [PATH] Plug-ins/Trakttv.bundle/Contents/Libraries/Shared
 2016-08-30 06:39:41,197 - plugin.core.libraries.manager (-8e6f900) : INFO (plugin.core.libraries.manager:56) - Testing native library support...
 2016-08-30 06:39:41,197 - plugin.core.libraries.tests.core.base (-8e6f900) : DEBUG (plugin.core.libraries.tests.core.base:96) - Starting test: plugin.core.libraries.tests.apsw_:test_import
 2016-08-30 06:39:41,437 - plugin.core.libraries.manager (-8e6f900) : INFO (plugin.core.libraries.manager:102) - apsw: available (sqlite: 3010002, apsw: 3.10.2-r1)
 2016-08-30 06:39:41,438 - plugin.core.libraries.tests.core.base (-8e6f900) : DEBUG (plugin.core.libraries.tests.core.base:96) - Starting test: plugin.core.libraries.tests.cryptography_:test_import
 2016-08-30 06:39:41,627 - root (-8e6f900) : WARNING (root:1601) - cryptography: unavailable - libffi.so.6: cannot open shared object file: No such file or directory
 2016-08-30 06:39:41,631 - plugin.core.logger.handlers.error_reporter.ErrorReporter (-8e6f900) : DEBUG (plugin.core.logger.handlers.error_reporter.ErrorReporter:610) - Sending message of length 1104 to threaded+requests+http://sentry.skipthe.net/api/1/store/
 2016-08-30 06:39:41,632 - plugin.core.libraries.tests.core.base (-8e6f900) : DEBUG (plugin.core.libraries.tests.core.base:96) - Starting test: plugin.core.libraries.tests.llist_:test_import
 2016-08-30 06:39:41,793 - plugin.core.libraries.manager (-8e6f900) : INFO (plugin.core.libraries.manager:109) - llist: available
 2016-08-30 06:39:41,794 - plugin.core.libraries.tests.core.base (-8e6f900) : DEBUG (plugin.core.libraries.tests.core.base:96) - Starting test: plugin.core.libraries.tests.openssl_:test_import
 2016-08-30 06:39:42,005 - root (-8e6f900) : WARNING (root:1601) - openssl: unavailable - libffi.so.6: cannot open shared object file: No such file or directory
 2016-08-30 06:39:42,008 - plugin.core.logger.handlers.error_reporter.ErrorReporter (-8e6f900) : DEBUG (plugin.core.logger.handlers.error_reporter.ErrorReporter:610) - Sending message of length 1096 to threaded+requests+http://sentry.skipthe.net/api/1/store/
 2016-08-30 06:39:42,325 - plugin.core.helpers (-8e6f900) : INFO (plugin.core.helpers:19) - Using 'simplejson' module for JSON serialization
 2016-08-30 06:39:42,898 - plugin.core.helpers.database (-8e6f900) : DEBUG (plugin.core.helpers.database:20) - Connected to database at '/volume1/Plex/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.trakttv.db'
 2016-08-30 06:39:43,237 - pyemitter (-8e6f900) : DEBUG (pyemitter:45) - [plex_activity.activity.Activity ]:on(events: ['websocket.timeline.created'], func: >)
 2016-08-30 06:39:43,237 - pyemitter (-8e6f900) : DEBUG (pyemitter:45) - [plex_activity.activity.Activity ]:on(events: ['websocket.timeline.deleted'], func: >)
 2016-08-30 06:39:43,238 - pyemitter (-8e6f900) : DEBUG (pyemitter:45) - [plex_activity.activity.Activity ]:on(events: ['websocket.timeline.finished'], func: >)
 2016-08-30 06:39:43,404 - plex_database.core.database (-8e6f900) : DEBUG (plex_database.core.database:17) - Connecting to '/volume1/Plex/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.library.db'
 2016-08-30 06:39:43,522 - com.plexapp.plugins.trakttv (-8e6f900) : CRITICAL (com.plexapp.plugins.trakttv:615) - Exception starting plug-in (most recent call last):
 File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-35f0caa/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/core.py", line 608, in start
 self.sandbox.execute(self.init_code)
 File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-35f0caa/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 256, in execute
 exec(code) in self.environment
 File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code/init.py", line 51, in 
 import interface
 File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-35f0caa/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 333, in import
 return mod.load_module(name)
 File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-35f0caa/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 44, in load_module
 module = RestrictedModule(name, path, sandbox)
 File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-35f0caa/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/loader.py", line 30, in __init_
 exec(code) in self.dict
 File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code/interface/init.py", line 4, in 
 import m_sync
 File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-35f0caa/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 333, in import
 return mod.load_module(name)
 File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-35f0caa/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 44, in load_module
 module = RestrictedModule(name, path, sandbox)
 File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-35f0caa/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/loader.py", line 30, in __init_
 exec(code) in self.dict
 File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Code/interface/m_sync.py", line 11, in 
 from plugin.sync.main import Sync, QueueError
 File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-35f0caa/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 345, in import
 raise e
 UnknownTimeZoneError: 'Timezone/Pacific'

2016-08-30 06:39:43,674 - plugin.core.logger.handlers.error_reporter.ErrorReporter (-8e6f900) : DEBUG (plugin.core.logger.handlers.error_reporter.ErrorReporter:610) - Sending message of length 3388 to threaded+requests+http://sentry.skipthe.net/api/1/store/
 2016-08-30 06:39:45,996 - requests.packages.urllib3.connectionpool (-b9dc4c0) : DEBUG (requests.packages.urllib3.connectionpool:395) - "POST /api/1/store/ HTTP/1.1" 200 41
 2016-08-30 06:39:46,003 - requests.packages.urllib3.connectionpool (-b9dc4c0) : INFO (requests.packages.urllib3.connectionpool:213) - Starting new HTTP connection (1): sentry.skipthe.net
 2016-08-30 06:39:51,242 - requests.packages.urllib3.connectionpool (-b9dc4c0) : DEBUG (requests.packages.urllib3.connectionpool:395) - "POST /api/1/store/ HTTP/1.1" 200 41
 2016-08-30 06:39:51,248 - requests.packages.urllib3.connectionpool (-b9dc4c0) : INFO (requests.packages.urllib3.connectionpool:213) - Starting new HTTP connection (1): sentry.skipthe.net
 2016-08-30 06:39:56,530 - requests.packages.urllib3.connectionpool (-b9dc4c0) : DEBUG (requests.packages.urllib3.connectionpool:395) - "POST /api/1/store/ HTTP/1.1" 200 41
 2016-08-30 06:39:56,535 - requests.packages.urllib3.connectionpool (-b9dc4c0) : INFO (requests.packages.urllib3.connectionpool:213) - Starting new HTTP connection (1): sentry.skipthe.net
 2016-08-30 06:40:01,823 - requests.packages.urllib3.connectionpool (-b9dc4c0) : DEBUG (requests.packages.urllib3.connectionpool:395) - "POST /api/1/store/ HTTP/1.1" 200 41

**Comment by fuzeman** [comment]
Just pushed a possible fix to the "issue/354" branch, download it from [here](https://github.com/fuzeman/Plex-Trakt-Scrobbler/archive/issue/354.zip), copy it into your "Plug-ins" directory and restart Plex Media Server to ensure the plugin is restarted correctly.

Please let me know if this works or not, post the plugin log file again if it still isn't showing up in Plex/Web.

**Comment by ricox00** [comment]
I can see it now in the plug ins. It didn't at first. I redid the process again and deleted all the logs from trakt and it appeared. Thanks for the great support. If you have a link for me to support your project please post it, I would like to donate. Thank you.

**Comment by fuzeman** [comment]
Great :smile:, will make sure that fix is included in the next plugin release.

----------

> Thanks for the great support. If you have a link for me to support your project please post it, I would like to donate. Thank you.

[Gratipay (weekly micro-payments)](https://gratipay.com/trakt-for-plex)
[PayPal (single donation)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=853QCH9BP7LE2)

Let me know if you have any other issues with the plugin, will be happy to help.

**Comment by ricox00** [comment]
Thanks I will.

**Comment by ricox00** [comment]
Hey Dean,


    Funny thing,


I think although It Trakt wasn't appearing it was syncing my collection but not views in the background. 


Get Outlook for Android






On Wed, Aug 31, 2016 at 7:08 PM -0500, "Dean Gardiner" <notifications@github.com> wrote:












Great 😄, will make sure that fix is included in the next plugin release.






Thanks for the great support. If you have a link for me to support your project please post it, I would like to donate. Thank you.




Gratipay (weekly micro-payments)

PayPal (single donation)



Let me know if you have any other issues with the plugin, will be happy to help.
