### ISSUE TITLE
database or disk full exception on Sync

### ISSUE THREAD

**Issue by miracle152004** [trakt/Plex-Trakt-Scrobbler#357]
Hi I am currently using the latest version of this addin.
And have updated to the latest version of plex.
Everytime I try to sync with plex I get an "database or disk full" error.

I attached the latest logfile for analysis.

[com.plexapp.system - Kopie.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/453586/com.plexapp.system.-.Kopie.txt)

Could you please take a look what causes this issue?
There are still 120GB of free disk space on the hard drive.

Thanks

Best regards
miracle152004

**Comment by fuzeman** [comment]
Not really sure why APSW/SQLite is returning that error if you still have disk space.. maybe the cache databases are corrupt?

----------

I would first try deleting the cache databases (`plex.db` and `trakt.db`) at:
```
C:\Users\<username>\AppData\Local\Plex Media Server\Plug-in Support\Caches\com.plexapp.plugins.trakttv
```

**Note:** you might need to shutdown Plex Media Server, delete the cache databases, and then start Plex Media Server up again.

**Comment by miracle152004** [comment]
Hi,
tested it, made no difference still getting the error.

**Comment by miracle152004** [comment]
I also tried moving the whole plex folder to a different drive through the server settings. 
Which also does not work and creates the following additional error:
`2016-09-07 07:46:48,219 - plugin.sync.main                 (294) :  ERROR (plugin.sync.main:172) - Unable to run final sync tasks: path is on drive c:, start on drive T:
Traceback (most recent call last):
  File "T:\Plex\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\sync\main.py", line 170, in run_wrapper
    self.finish()
  File "T:\Plex\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\sync\main.py", line 205, in finish
    current.finish()
  File "T:\Plex\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\sync\core\task\main.py", line 128, in finish
    self.store_exception(self.result, exc_info)
  File "T:\Plex\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\sync\core\task\main.py", line 143, in store_exception
    exception, error = ExceptionManager.create.from_exc_info(exc_info)
  File "T:\Plex\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\managers\exception.py", line 35, in from_exc_info
    traceback=ErrorHasher.exc_traceback(exc_info[2]),
  File "T:\Plex\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\core\helpers\error.py", line 24, in exc_traceback
    for (filename, line_num, name, line) in tb_list
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-6f64a8d\Framework.bundle\Contents\Resources\Versions\2\Python\subsystem\ospathfix.py", line 208, in os_path_relpath
    return os.path._relpath(uni(path), uni(start))
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\ntpath.py", line 512, in relpath
    % (path_prefix, start_prefix))
ValueError: path is on drive c:, start on drive T`

**Comment by miracle152004** [comment]
I found a similar issue here:
[https://github.com/rembo10/headphones/issues/122](https://github.com/rembo10/headphones/issues/122)

Which talks about compatbility issues in python6
I do not know if this is relevant or not.
