### ISSUE TITLE
Plugin Will Not Start (Mac OSX)

### ISSUE THREAD

**Issue by silvamerica** [trakt/Plex-Trakt-Scrobbler#363]
After copying the bundle into ~/Library/Application Support/Plex Media Server/Plug-Ins and starting Plex Media Server up, nothing shows up in the Channels section. This is all that shows up in the Plex Media Server.log:

```
Oct 02, 2016 15:32:32.186 [0x1132fb000] ERROR - Timeout or error reading status line from plug-in pipe [com.plexapp.plugins.trakttv], we're killing it.
Oct 02, 2016 15:32:32.186 [0x1132fb000] ERROR - Error received reading configuration for com.plexapp.plugins.trakttv
```

Here is com.plexapp.plugins.trakttv.log:

```
2016-10-02 15:33:08,685 (7fff7dc3a300) :  INFO (core:349) - Starting framework core - Version: 2.6.3, Build: 24ffd60 (Mon Sep 12 15:26:58 UTC 2016)
2016-10-02 15:33:08,685 (7fff7dc3a300) :  DEBUG (core:361) - Using the elevated policy
2016-10-02 15:33:08,686 (7fff7dc3a300) :  DEBUG (core:450) - Starting runtime component.
2016-10-02 15:33:08,688 (7fff7dc3a300) :  DEBUG (core:450) - Starting caching component.
2016-10-02 15:33:08,688 (7fff7dc3a300) :  DEBUG (core:450) - Starting data component.
2016-10-02 15:33:08,689 (7fff7dc3a300) :  DEBUG (core:450) - Starting networking component.
2016-10-02 15:33:08,690 (7fff7dc3a300) :  DEBUG (networking:284) - Loaded HTTP cookies
2016-10-02 15:33:08,690 (7fff7dc3a300) :  DEBUG (networking:452) - Setting the default network timeout to 20.0
2016-10-02 15:33:08,701 (7fff7dc3a300) :  DEBUG (core:450) - Starting localization component.
2016-10-02 15:33:08,701 (7fff7dc3a300) :  INFO (localization:409) - Setting the default locale to en-us
2016-10-02 15:33:08,701 (7fff7dc3a300) :  DEBUG (localization:427) - Loaded en strings
2016-10-02 15:33:08,702 (7fff7dc3a300) :  DEBUG (core:450) - Starting messaging component.
2016-10-02 15:33:08,703 (10dc84000) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/system/messaging/clear_events/com.plexapp.plugins.trakttv'
2016-10-02 15:33:08,702 (7fff7dc3a300) :  DEBUG (core:450) - Starting debugging component.
2016-10-02 15:33:08,704 (7fff7dc3a300) :  DEBUG (core:450) - Starting services component.
2016-10-02 15:33:08,704 (7fff7dc3a300) :  DEBUG (core:450) - Starting myplex component.
2016-10-02 15:33:08,705 (7fff7dc3a300) :  DEBUG (core:450) - Starting notifications component.
2016-10-02 15:33:08,978 (7fff7dc3a300) :  DEBUG (accessor:68) - Creating a new model access point for provider com.plexapp.plugins.trakttv in namespace 'metadata'
2016-10-02 15:33:08,984 (7fff7dc3a300) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes'
2016-10-02 15:33:09,521 (10dc84000) :  DEBUG (services:265) - Plug-in is not daemonized - loading services from system
2016-10-02 15:33:09,522 (7fff7dc3a300) :  DEBUG (runtime:1117) - Created a thread named 'load_all_services'
2016-10-02 15:33:09,523 (10dc84000) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_'
2016-10-02 15:33:09,524 (7fff7dc3a300) :  DEBUG (runtime:1117) - Created a thread named 'get_server_info'
2016-10-02 15:33:09,525 (7fff7dc3a300) :  DEBUG (core:150) - Finished starting framework core
2016-10-02 15:33:09,525 (10e50a000) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400'
2016-10-02 15:33:09,525 (7fff7dc3a300) :  DEBUG (core:560) - Loading plug-in code
2016-10-02 15:33:09,554 (10e50a000) :  DEBUG (core:538) - Machine identifier is 0136c43a762baec30c258a2578cc9486740567d4
2016-10-02 15:33:09,555 (10e50a000) :  DEBUG (core:539) - Server version is 1.1.4.2757-24ffd60
2016-10-02 15:33:09,600 (7fff7dc3a300) :  DEBUG (core:566) - Finished loading plug-in code
2016-10-02 15:33:09,910 (7fff7dc3a300) :  DEBUG (fs_migrator:19) - Running migration: <fs_migrator.Clean object at 0x10e18cc90>
2016-10-02 15:33:09,933 (7fff7dc3a300) :  DEBUG (fs_migrator:19) - Running migration: <fs_migrator.ForceLegacy object at 0x10e18ccd0>
2016-10-02 15:33:09,934 (7fff7dc3a300) :  DEBUG (fs_migrator:19) - Running migration: <fs_migrator.SelectiveSync object at 0x10e18cd10>
2016-10-02 15:33:10,054 (10dc84000) :  DEBUG (services:362) - Loaded services
2016-10-02 15:33:10,062 (10e107000) :  DEBUG (services:438) - No shared code to load
2016-10-02 15:33:10,277 - plugin.core.configuration        (7fff7dc3a300) :  DEBUG (plugin.core.configuration:33) - Parsing configuration file: 'Data/com.plexapp.plugins.trakttv/advanced.ini'
2016-10-02 15:33:10,289 - plugin.core.libraries.helpers.system (7fff7dc3a300) :  INFO (plugin.core.libraries.helpers.system:312) - Unable to retrieve ELF attributes on Mac OSX (not supported)
2016-10-02 15:33:10,291 - plugin.core.logger.handlers.error_reporter.ErrorReporter (7fff7dc3a300) :  DEBUG (plugin.core.logger.handlers.error_reporter.ErrorReporter:201) - Configuring Raven for host: threaded+requests+http://240c00f6a02542f8900d8a6a1aba365a:7432061e2ac54ed0aabe4ec3fe3ea0d9@sentry.skipthe.net:/1
2016-10-02 15:33:10,292 - plugin.core.logger.main          (7fff7dc3a300) :  DEBUG (plugin.core.logger.main:72) - Initialized logging (report: True, storage: False)
2016-10-02 15:33:10,294 - com.plexapp.plugins.trakttv      (7fff7dc3a300) :  DEBUG (com.plexapp.plugins.trakttv:258) - Loaded preferences from DefaultPrefs.json
2016-10-02 15:33:10,296 - com.plexapp.plugins.trakttv      (7fff7dc3a300) :  DEBUG (com.plexapp.plugins.trakttv:178) - Loaded the user preferences for com.plexapp.plugins.trakttv
2016-10-02 15:33:10,297 - plugin.core.environment          (7fff7dc3a300) :  WARNING (plugin.core.environment:116) - Unable to set locale to 'en_US': _locale emulation only supports "C" locale
Traceback (most recent call last):
  File "/Users/pon/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/core/environment.py", line 114, in setup_locale
    locale.setlocale(locale.LC_ALL, DEFAULT_LOCALE)
  File "/Volumes/CI-OSX/jenkins/pms-deps-universal-v2/BUILD_TAG/darwin-x86_64/output/pms-depends-darwin-x86_64-release-08b2c10/lib/python2.7/locale.py", line 547, in setlocale
  File "/Volumes/CI-OSX/jenkins/pms-deps-universal-v2/BUILD_TAG/darwin-x86_64/output/pms-depends-darwin-x86_64-release-08b2c10/lib/python2.7/locale.py", line 88, in setlocale
ValueError: _locale emulation only supports "C" locale
2016-10-02 15:33:10,312 - plugin.core.logger.handlers.error_reporter.ErrorReporter (7fff7dc3a300) :  DEBUG (plugin.core.logger.handlers.error_reporter.ErrorReporter:610) - Sending message of length 1660 to threaded+requests+http://sentry.skipthe.net/api/1/store/
2016-10-02 15:33:10,338 - plugin.core.environment          (7fff7dc3a300) :  INFO (plugin.core.environment:192) - Unable to detect system language, defaulting to the "en_US" locale
2016-10-02 15:33:10,345 - plugin.core.environment          (7fff7dc3a300) :  INFO (plugin.core.environment:165) - Using languages: ['en_us', 'en'] (translation: <gettext.GNUTranslations instance at 0x10dadf7e8>)
2016-10-02 15:33:10,361 - requests.packages.urllib3.connectionpool (10e64a000) :  INFO (requests.packages.urllib3.connectionpool:214) - Starting new HTTP connection (1): sentry.skipthe.net
2016-10-02 15:33:10,437 - plugin.core.libraries.manager    (7fff7dc3a300) :  INFO (plugin.core.libraries.manager:189) - Cached libraries to 'Plug-in Support/Data/com.plexapp.plugins.trakttv/Libraries'
2016-10-02 15:33:10,437 - plugin.core.libraries.manager    (7fff7dc3a300) :  INFO (plugin.core.libraries.manager:36) - Using native libraries at 'Plug-in Support/Data/com.plexapp.plugins.trakttv/Libraries'
2016-10-02 15:33:10,438 - plugin.core.libraries.helpers.path (7fff7dc3a300) :  DEBUG (plugin.core.libraries.helpers.path:45) - Removed path: 'Plug-ins/Trakttv.bundle/Contents/Libraries/MacOSX/i386'
2016-10-02 15:33:10,455 - plugin.core.libraries.manager    (7fff7dc3a300) :  DEBUG (plugin.core.libraries.manager:198) - Bits: '64bit', Machine: 'x86_64'
2016-10-02 15:33:10,468 - requests.packages.urllib3.connectionpool (10e64a000) :  DEBUG (requests.packages.urllib3.connectionpool:401) - "POST /api/1/store/ HTTP/1.1" 200 41
2016-10-02 15:33:10,471 - plugin.core.libraries.manager    (7fff7dc3a300) :  DEBUG (plugin.core.libraries.manager:207) - System: 'MacOSX', Architecture: 'x86_64'
2016-10-02 15:33:10,471 - plugin.core.libraries.helpers.path (7fff7dc3a300) :  DEBUG (plugin.core.libraries.helpers.path:30) - Inserted path: 'Plug-in Support/Data/com.plexapp.plugins.trakttv/Libraries/MacOSX/x86_64'
2016-10-02 15:33:10,472 - plugin.core.libraries.manager    (7fff7dc3a300) :  DEBUG (plugin.core.libraries.manager:241) - UCS: 'ucs4'
2016-10-02 15:33:10,472 - plugin.core.libraries.helpers.path (7fff7dc3a300) :  DEBUG (plugin.core.libraries.helpers.path:30) - Inserted path: 'Plug-in Support/Data/com.plexapp.plugins.trakttv/Libraries/MacOSX/x86_64/ucs4'
2016-10-02 15:33:10,472 - plugin.core.libraries.helpers.arm (7fff7dc3a300) :  INFO (plugin.core.libraries.helpers.arm:111) - Unable to retrieve information from "/proc/cpuinfo", path doesn't exist
2016-10-02 15:33:10,473 - plugin.core.libraries.helpers.arm (7fff7dc3a300) :  INFO (plugin.core.libraries.helpers.arm:44) - Unable to retrieve processor identifier from "/proc/cpuinfo"
2016-10-02 15:33:10,473 - plugin.core.libraries.helpers.system (7fff7dc3a300) :  INFO (plugin.core.libraries.helpers.system:312) - Unable to retrieve ELF attributes on Mac OSX (not supported)
2016-10-02 15:33:10,475 - plugin.core.libraries.manager    (7fff7dc3a300) :  DEBUG (plugin.core.libraries.manager:250) - CPU Type: None
2016-10-02 15:33:10,475 - plugin.core.libraries.manager    (7fff7dc3a300) :  DEBUG (plugin.core.libraries.manager:251) - Page Size: '4k'
2016-10-02 15:33:10,475 - plugin.core.libraries.manager    (7fff7dc3a300) :  INFO (plugin.core.libraries.manager:51) - [PATH] Plug-in Support/Data/com.plexapp.plugins.trakttv/Libraries/MacOSX/x86_64/ucs4
2016-10-02 15:33:10,476 - plugin.core.libraries.manager    (7fff7dc3a300) :  INFO (plugin.core.libraries.manager:51) - [PATH] Plug-in Support/Data/com.plexapp.plugins.trakttv/Libraries/MacOSX/x86_64
2016-10-02 15:33:10,476 - plugin.core.libraries.manager    (7fff7dc3a300) :  INFO (plugin.core.libraries.manager:51) - [PATH] Plug-ins/Trakttv.bundle/Contents/Libraries/Shared
2016-10-02 15:33:10,479 - plugin.core.libraries.manager    (7fff7dc3a300) :  INFO (plugin.core.libraries.manager:56) - Testing native library support...
2016-10-02 15:33:10,479 - plugin.core.libraries.tests.core.base (7fff7dc3a300) :  DEBUG (plugin.core.libraries.tests.core.base:96) - Starting test: plugin.core.libraries.tests.apsw_:test_import
2016-10-02 15:33:10,662 - plugin.core.libraries.manager    (7fff7dc3a300) :  INFO (plugin.core.libraries.manager:102) - apsw: available (sqlite: 3010002, apsw: 3.10.2-r1)
2016-10-02 15:33:10,663 - plugin.core.libraries.tests.core.base (7fff7dc3a300) :  DEBUG (plugin.core.libraries.tests.core.base:96) - Starting test: plugin.core.libraries.tests.cryptography_:test_import
2016-10-02 15:33:10,824 - plugin.core.libraries.manager    (7fff7dc3a300) :  INFO (plugin.core.libraries.manager:107) - cryptography: available (1.2.2)
2016-10-02 15:33:10,825 - plugin.core.libraries.tests.core.base (7fff7dc3a300) :  DEBUG (plugin.core.libraries.tests.core.base:96) - Starting test: plugin.core.libraries.tests.llist_:test_import
2016-10-02 15:33:10,963 - plugin.core.libraries.manager    (7fff7dc3a300) :  INFO (plugin.core.libraries.manager:109) - llist: available
2016-10-02 15:33:10,964 - plugin.core.libraries.tests.core.base (7fff7dc3a300) :  DEBUG (plugin.core.libraries.tests.core.base:96) - Starting test: plugin.core.libraries.tests.openssl_:test_import
```

**Comment by fuzeman** [comment]
Couldn't reproduce this issue with:
 - **OS X:** 10.9.5
 - **Plex Media Server:** 1.1.4.2757-24ffd60
 - **Trakt.tv (for Plex):** 1.1.0.6

------------------

 - Are you using the latest version of the plugin (v1.1.0.6)?
 - Which version of OS X are you currently using?
