### ISSUE TITLE
Unable to process plex preference change for 'pin'

### ISSUE THREAD

**Issue by Lukeid** [trakt/Plex-Trakt-Scrobbler#390]
Hello,

Im trying to use Trakt plugin, but I can not authenticate with the PIN.
I set the pin and pres save button from setting and this is the generated log:
```
2017-01-13 20:33:22,069 - root                             (312bd460) :  INFO (root:840) - 200 GET /:/plugins/com.plexapp.plugins.trakttv/prefs (127.0.0.1) 154.61ms
2017-01-13 20:33:49,512 - plugin.modules.migrations.account (312bd460) :  INFO (plugin.modules.migrations.account:1141) - Plex Token: anonymous
2017-01-13 20:33:49,605 - plugin.modules.migrations.account (312bd460) :  WARNING (plugin.modules.migrations.account:1153) - Unable to refresh trakt account (not authenticated?)
Traceback (most recent call last):
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/modules/migrations/account.py", line 82, in create_administrator_account
    t_refreshed = t_account.refresh(force=t_created)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/models/m_trakt/account.py", line 106, in refresh
    with self.authorization().http(retry=force):
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/models/m_trakt/account.py", line 74, in authorization
    raise AccountAuthenticationError("Trakt account hasn't been authenticated")
AccountAuthenticationError: Trakt account hasn't been authenticated
2017-01-13 20:33:50,024 - plugin.preferences.main          (312bd460) :  WARNING (plugin.preferences.main:1153) - Unable to process plex preference change for 'pin'
Traceback (most recent call last):
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/preferences/main.py", line 112, in on_plex_changed
    value = option.on_plex_changed(value, account=account)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/preferences/options/pin.py", line 32, in on_plex_changed
    if not TraktAccountManager.update.from_pin(trakt_account, value):
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/managers/m_trakt/account.py", line 124, in from_pin
    if not TraktOAuthCredentialManager.update.from_pin(oauth, pin, save=False):
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/managers/m_trakt/credential.py", line 73, in from_pin
    authorization = Trakt['oauth'].token_exchange(pin, 'urn:ietf:wg:oauth:2.0:oob')
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/trakt/interfaces/oauth/__init__.py", line 64, in token_exchange
    authenticated=False
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/trakt/core/http.py", line 140, in post
    return self.request('POST', path, params, data, **kwargs)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/trakt/core/http.py", line 95, in request
    return self.send(prepared)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/trakt/core/http.py", line 113, in send
    response = self.session.send(request, timeout=timeout)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/raven/breadcrumbs.py", line 297, in send
    resp = real_send(self, request, *args, **kwargs)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
SSLError: SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
2017-01-13 20:33:50,175 - root                             (312bd460) :  INFO (root:840) - 200 GET /:/plugins/com.plexapp.plugins.trakttv/prefs/set?pin=244c5d2a (127.0.0.1) 692.52ms
```

I'm using Plex Server in a Synology NAS.

What should I do?

Thank you very much.
 Lukeid

**Comment by fuzeman** [comment]
Possibly related to https://github.com/fuzeman/trakt.py/issues/52, try the latest development release of the plugin which includes the fix here: [develop.zip](https://github.com/trakt/Plex-Trakt-Scrobbler/archive/develop.zip)

**Comment by Lukeid** [comment]
Yes, It seems to work now.

Thank you very much. :)
