### ISSUE TITLE
Global Filter doesnt accept to save with special characters

### ISSUE THREAD

**Issue by saitoh183** [trakt/Plex-Trakt-Scrobbler#391]
Here is the error:

```
2017-01-15 00:05:20,756 - root                             (e98) :  DEBUG (root:265) - Exception in I/O handler for fd 1436
Traceback (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-b38628e\Framework.bundle\Contents\Resources\Platforms\Shared\Libraries\tornado\ioloop.py", line 256, in start
    self._handlers[fd](fd, events)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-b38628e\Framework.bundle\Contents\Resources\Platforms\Shared\Libraries\tornado\stack_context.py", line 128, in wrapped
    callback(*args, **kwargs)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-b38628e\Framework.bundle\Contents\Resources\Platforms\Shared\Libraries\tornado\httpserver.py", line 219, in _handle_events
    connection, address = self._socket.accept()
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\socket.py", line 206, in accept
    sock, addr = self._sock.accept()
error: [Errno 10035] A non-blocking socket operation could not be completed immediately
2017-01-15 00:05:20,756 - com.plexapp.plugins.trakttv      (17a4) :  DEBUG (com.plexapp.plugins.trakttv:717) - Handling request GET /video/trakt/:/prefs
2017-01-15 00:05:20,759 - com.plexapp.plugins.trakttv      (17a4) :  DEBUG (com.plexapp.plugins.trakttv:814) - Found route matching /video/trakt/:/prefs
2017-01-15 00:05:20,773 - com.plexapp.plugins.trakttv      (17a4) :  DEBUG (com.plexapp.plugins.trakttv:88) - Sending packed state data (108 bytes)
2017-01-15 00:05:20,775 - com.plexapp.plugins.trakttv      (17a4) :  DEBUG (com.plexapp.plugins.trakttv:924) - Response: [200] MediaContainer, 4842 bytes
2017-01-15 00:05:20,776 - root                             (17a4) :  INFO (root:840) - 200 GET /video/trakt/:/prefs (127.0.0.1) 18.00ms
2017-01-15 00:05:25,805 - plugin.modules.sessions.main     (954) :  DEBUG (plugin.modules.sessions.main:1147) - 1 active session(s): {u'100:1': <Session session_key: u'100:1', account_id: 5, rating_key: 123998, seen_at: datetime.datetime(2017, 1, 15, 5, 5, 25, 805000)>}
2017-01-15 00:05:35,812 - plugin.modules.sessions.main     (954) :  DEBUG (plugin.modules.sessions.main:1147) - 1 active session(s): {u'100:1': <Session session_key: u'100:1', account_id: 5, rating_key: 123998, seen_at: datetime.datetime(2017, 1, 15, 5, 5, 35, 813000)>}
2017-01-15 00:05:45,819 - plugin.modules.sessions.main     (954) :  DEBUG (plugin.modules.sessions.main:1147) - 1 active session(s): {u'100:1': <Session session_key: u'100:1', account_id: 5, rating_key: 123998, seen_at: datetime.datetime(2017, 1, 15, 5, 5, 45, 819000)>}
2017-01-15 00:05:46,250 - root                             (e98) :  DEBUG (root:265) - Exception in I/O handler for fd 1436
Traceback (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-b38628e\Framework.bundle\Contents\Resources\Platforms\Shared\Libraries\tornado\ioloop.py", line 256, in start
    self._handlers[fd](fd, events)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-b38628e\Framework.bundle\Contents\Resources\Platforms\Shared\Libraries\tornado\stack_context.py", line 128, in wrapped
    callback(*args, **kwargs)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-b38628e\Framework.bundle\Contents\Resources\Platforms\Shared\Libraries\tornado\httpserver.py", line 219, in _handle_events
    connection, address = self._socket.accept()
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\socket.py", line 206, in accept
    sock, addr = self._sock.accept()
error: [Errno 10035] A non-blocking socket operation could not be completed immediately
2017-01-15 00:05:46,252 - com.plexapp.plugins.trakttv      (6e8) :  DEBUG (com.plexapp.plugins.trakttv:717) - Handling request GET /video/trakt/:/prefs/set?filter_sections=TV%20Shows%2CMovies%2CUFC%2CAnime%2CMovies%2FFilms%20%28Fra%2FEng%29%2CSeries%20Francais%2CS%C3%A9ries%20Fran%C3%A7ais
2017-01-15 00:05:46,253 - com.plexapp.plugins.trakttv      (6e8) :  DEBUG (com.plexapp.plugins.trakttv:814) - Found route matching /video/trakt/:/prefs/set
2017-01-15 00:05:46,257 - com.plexapp.plugins.trakttv      (6e8) :  CRITICAL (com.plexapp.plugins.trakttv:574) - Exception (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-b38628e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\runtime.py", line 843, in handle_request
    result = f(**d)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-b38628e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\handlers\runtime.py", line 166, in set_prefs
    self._core.sandbox.preferences.get().update_user_values(**kwargs)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-b38628e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\code\preferences.py", line 218, in update_user_values
    self._save_user_file()
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-b38628e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\code\preferences.py", line 193, in _save_user_file
    el.append(self._core.data.xml.element(name, self._user_values_dict.get(name, pref.encode_value(pref.default_value))))
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-b38628e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\data.py", line 130, in element
    return self._construct_el(etree.Element(name), text, kwargs)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-b38628e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\data.py", line 124, in _construct_el
    el.text = text
  File "lxml.etree.pyx", line 916, in lxml.etree._Element.text.__set__ (..\src\lxml\lxml.etree.c:36134)
  File "apihelpers.pxi", line 721, in lxml.etree._setNodeText (..\src\lxml\lxml.etree.c:17141)
  File "apihelpers.pxi", line 1366, in lxml.etree._utf8 (..\src\lxml\lxml.etree.c:22211)
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters

2017-01-15 00:05:46,260 - plugin.core.logger.handlers.error_storage (6e8) :  WARNING (plugin.core.logger.handlers.error_storage:1171) - Unable to store exception message: path is on drive C:, start on drive P:
Traceback (most recent call last):
  File "P:\Data\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\core\logger\handlers\error_storage.py", line 24, in emit
    ExceptionManager.create.from_message(record.message)
  File "P:\Data\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\managers\exception.py", line 94, in from_message
    traceback=self.strip_traceback(match.group('traceback')),
  File "P:\Data\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\managers\exception.py", line 131, in strip_traceback
    path = os.path.relpath(line[path_start:path_end], PMS_PATH)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-b38628e\Framework.bundle\Contents\Resources\Versions\2\Python\subsystem\ospathfix.py", line 208, in os_path_relpath
    return os.path._relpath(uni(path), uni(start))
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\ntpath.py", line 529, in relpath
    % (path_prefix, start_prefix))
ValueError: path is on drive C:, start on drive P:
2017-01-15 00:05:46,266 - com.plexapp.plugins.trakttv      (6e8) :  DEBUG (com.plexapp.plugins.trakttv:88) - Sending packed state data (108 bytes)
2017-01-15 00:05:46,266 - com.plexapp.plugins.trakttv      (6e8) :  DEBUG (com.plexapp.plugins.trakttv:924) - Response: [500] 2121 bytes
2017-01-15 00:05:46,266 - root                             (6e8) :  ERROR (root:840) - 500 GET /video/trakt/:/prefs/set?filter_sections=TV%20Shows%2CMovies%2CUFC%2CAnime%2CMovies%2FFilms%20%28Fra%2FEng%29%2CSeries%20Francais%2CS%C3%A9ries%20Fran%C3%A7ais (127.0.0.1) 16.00ms
2017-01-15 00:05:46,269 - plugin.core.logger.handlers.error_reporter.ErrorReporterClient (6e8) :  DEBUG (plugin.core.logger.handlers.error_reporter.ErrorReporterClient:713) - Sending message of length 907 to https://sentry.skipthe.net/api/1/store/
2017-01-15 00:05:46,270 - requests.packages.urllib3.connectionpool (2924) :  DEBUG (requests.packages.urllib3.connectionpool:810) - Starting new HTTPS connection (1): sentry.skipthe.net
2017-01-15 00:05:46,704 - requests.packages.urllib3.connectionpool (2924) :  DEBUG (requests.packages.urllib3.connectionpool:401) - https://sentry.skipthe.net:443 "POST /api/1/store/ HTTP/1.1" 200 41
```

The name of the library i was trying to add was "Séries Français" if i change it to "Series Francais", it saves

**Comment by fuzeman** [comment]
Similar to issue #256, it's an issue with the Plex Plugin Framework.

The plugin does support matching `c` with `ç`, so you should be able to still define filters for libraries with Unicode characters.

**Comment by saitoh183** [comment]
When I add it , it says unable to save configuration. but if I close and re-open, it is there. But when I go into track to sync, the library doesn't appear in the list

**Comment by gdolla** [comment]
What special characters are missing?

**Comment by saitoh183** [comment]
well that is the thing...its not that they are missing its that when i add a library that contains special characters, it doesnt want to save. So when i go into trakt to try and sync the library, it doesnt appear

I try to add Films Français:
![image](https://cloud.githubusercontent.com/assets/1534197/22005651/1eab38ec-dc33-11e6-968d-6c5ec624e6d3.png)

Doesnt save so i press cancel but i go back in the settings and it is there:

![image](https://cloud.githubusercontent.com/assets/1534197/22005694/59ed3d92-dc33-11e6-91d6-83a4bbc8ac98.png)

Then i go into Trakt and the library isnt there:

![image](https://cloud.githubusercontent.com/assets/1534197/22005721/98c1ef0e-dc33-11e6-9247-0f1b21d0b9b9.png)

**Comment by fuzeman** [comment]
> Doesnt save so i press cancel but i go back in the settings and it is there

I think this is just Plex/Web keeping your previously entered value, the plugin settings haven't actually been written to disk.

-------------

Try use the closest ASCII representation of your library titles in the `Global Filter - Libraries` field, for example:
 - `Series Francais` instead of `Séries Français`
 - `Films Francais` instead of `Films Français`

**Comment by saitoh183** [comment]
Switching ASCII representation does work but i want to avoid doing this because it forces a rescan of the library and on my local machine that is ok but on my remote plex server with data in google drive...the scan time will be days with my library size because the content is on Gdrive

**Comment by fuzeman** [comment]
I mean define them in their ASCII representation just in the Trakt.tv plugin settings, you don't need to change the actual folders or library titles in Plex.

The plugin filters support matching `Series Francais` against an actual library named `Séries Français`

**Comment by saitoh183** [comment]
Ah!
ok i will try that
