### ISSUE TITLE
OSError after each start. No scrobbling

### ISSUE THREAD

**Issue by nFec** [trakt/Plex-Trakt-Scrobbler#393]
Hi there,

Since around 90 days there is no scrobbling anymore. I just updated to the newest freenas-plex plugin and reinstalled the trakt-scrobbler. Still, after each restart of Plex I see the same errors on the Trakt channel:
![image](https://cloud.githubusercontent.com/assets/3140706/22106938/8268cce0-de4b-11e6-92af-21d2a1f745b7.png)

I enabled DEBUG logging for all items in the plugin settings, but there was no difference to be found.

Any pointers? Note that on the same system it had worked before. No changes that I am aware of.

Thank you
nFec

**Comment by fuzeman** [comment]
The error in the screenshot is related to the legacy activity source (for very old Plex clients), and probably isn't the cause of your scrobbling issues.

Could you attach the latest plugin log file (after playing something off your server for a couple of minutes)? see [this page](https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Log-files) for more details.

**Comment by nFec** [comment]
[com.plexapp.plugins.trakttv.log.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/718823/com.plexapp.plugins.trakttv.log.txt)

There you go.

**Comment by fuzeman** [comment]
Looks like it was scrobbling:
```
Sending action u'scrobble/start' (account: <Account name: u'till2'>, interface: u'scrobble', method: u'start')
request: {u'progress': 1.56, u'episode': {u'season': 2, u'number': 10, u'title': u'Second Coming'}, u'show': {u'title': u'Ash vs Evil Dead', u'ids': {u'tvdb': 296295}, u'year': 2016}}
```
```
Sending action u'scrobble/pause' (account: <Account name: u'till2'>, interface: u'scrobble', method: u'pause')
request: {u'progress': 1.75, u'episode': {u'season': 2, u'number': 10, u'title': u'Second Coming'}, u'show': {u'title': u'Ash vs Evil Dead', u'ids': {u'tvdb': 296295}, u'year': 2016}}
```
```
Sending action u'scrobble/stop' (account: <Account name: u'till2'>, interface: u'scrobble', method: u'stop')
request: {u'progress': 1.75, u'episode': {u'season': 2, u'number': 10, u'title': u'Second Coming'}, u'show': {u'title': u'Ash vs Evil Dead', u'ids': {u'tvdb': 296295}, u'year': 2016}}
```
```
Sending action u'scrobble/start' (account: <Account name: u'till2'>, interface: u'scrobble', method: u'start')
request: {u'progress': 0.0, u'episode': {u'season': 2, u'number': 10, u'title': u'Second Coming'}, u'show': {u'title': u'Ash vs Evil Dead', u'ids': {u'tvdb': 296295}, u'year': 2016}}
```
```
Sending action u'scrobble/pause' (account: <Account name: u'till2'>, interface: u'scrobble', method: u'pause')
request: {u'progress': 14.88, u'episode': {u'season': 2, u'number': 10, u'title': u'Second Coming'}, u'show': {u'title': u'Ash vs Evil Dead', u'ids': {u'tvdb': 296295}, u'year': 2016}}
```

Does this look correct?

--------------------

The plugin log file did eventually end with:
```
Exception raised in "websocket" activity source: [Errno 61] Connection refused
Traceback (most recent call last):
  File "/var/db/plexdata/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plex_activity/sources/base.py", line 22, in _run_wrapper
    self.run()
  File "/var/db/plexdata/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plex_activity/sources/s_websocket/main.py", line 96, in run
    self.connect()
  File "/var/db/plexdata/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plex_activity/sources/s_websocket/main.py", line 74, in connect
    self.ws = websocket.create_connection(uri)
  File "/var/db/plexdata/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/websocket/_core.py", line 487, in create_connection
    websock.connect(url, **options)
  File "/var/db/plexdata/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/websocket/_core.py", line 211, in connect
    options.pop('socket', None))
  File "/var/db/plexdata/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/websocket/_http.py", line 71, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "/var/db/plexdata/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/websocket/_http.py", line 127, in _open_socket
    raise err
error: [Errno 61] Connection refused
```

Which would of resulted in no watching activity being received from Plex Media Server after 2017-01-20 09:36:58,024. Does this match what you were experiencing with the plugin?

If this error is the cause, changes can be made to the websocket reconnection functionality to try resolve this issue.

**Comment by nFec** [comment]
That looks about right, it does seem like sometimes views are scrobbled correctly, and other times not. E.g. Episode 4 and 6 of some show showing up unwatched but ep 5 as watched.

So the plugin can't open the socket once, and then gives up? This for sure would be worth a try.

**Comment by fuzeman** [comment]
I've just pushed some improvements to the development branch ([develop.zip](https://github.com/trakt/Plex-Trakt-Scrobbler/archive/develop.zip)), let me know if this fixes your scrobbling issues.

----------

> So the plugin can't open the socket once, and then gives up? This for sure would be worth a try.

There was a flaw in the reconnection logic which meant connections were only retried once, this has been fixed so that connections will be retried 10 times with a slowly increasing delay.
