### ISSUE TITLE
Sync to trakt.tv stop working

### ISSUE THREAD

**Issue by kiborgai** [trakt/Plex-Trakt-Scrobbler#444]
I using this super useful tool several years. Bet suddenly, about two weeks ago, it not syncing any more.
I tried re-authenticate, reinstall. But it's not helped.

There is log:

`error: [Errno 10035] A non-blocking socket operation could not be completed immediately
2017-05-25 11:51:12,941 - plugin.sync.main                 (1b8c) :  INFO (plugin.sync.main:1159) - (0) Started
2017-05-25 11:51:12,948 - plugin.sync.modes.core.base.mode (1b8c) :  INFO (plugin.sync.modes.core.base.mode:1159) - Executing construct() on child: <plugin.sync.modes.fast_pull.movies.Movies object at 0x07102A30>
2017-05-25 11:51:12,967 - plugin.sync.modes.core.base.mode (1b8c) :  INFO (plugin.sync.modes.core.base.mode:1159) - Executing construct() on child: <plugin.sync.modes.fast_pull.shows.Shows object at 0x07102230>
2017-05-25 11:51:12,984 - plugin.sync.modes.core.base.mode (1b8c) :  INFO (plugin.sync.modes.core.base.mode:1159) - Executing construct() on child: <plugin.sync.modes.push.movies.Movies object at 0x07102B30>
2017-05-25 11:51:13,003 - plugin.sync.modes.core.base.mode (1b8c) :  INFO (plugin.sync.modes.core.base.mode:1159) - Executing construct() on child: <plugin.sync.modes.push.shows.Shows object at 0x07102CD0>
2017-05-25 11:51:13,523 - trakt_sync.cache.sources.sync    (1b8c) :  INFO (trakt_sync.cache.sources.sync:1159) - Fetching "sync/watched/shows"
2017-05-25 11:51:13,911 - root                             (3014) :  INFO (root:840) - 302 GET /video/trakt/sync/synchronize?account_id=1&t=1495702270.31 (127.0.0.1) 1100.00ms
2017-05-25 11:51:13,921 - root                             (35d8) :  DEBUG (root:265) - Exception in I/O handler for fd 1384
Traceback (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-995f1dead\Framework.bundle\Contents\Resources\Platforms\Shared\Libraries\tornado\ioloop.py", line 256, in start
    self._handlers[fd](fd, events)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-995f1dead\Framework.bundle\Contents\Resources\Platforms\Shared\Libraries\tornado\stack_context.py", line 128, in wrapped
    callback(*args, **kwargs)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-995f1dead\Framework.bundle\Contents\Resources\Platforms\Shared\Libraries\tornado\httpserver.py", line 219, in _handle_events
    connection, address = self._socket.accept()
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\socket.py", line 206, in accept
    sock, addr = self._sock.accept()
error: [Errno 10035] A non-blocking socket operation could not be completed immediately
2017-05-25 11:51:14,288 - root                             (2c68) :  INFO (root:840) - 200 GET /video/trakt/sync?account_id=1 (127.0.0.1) 361.00ms
2017-05-25 11:51:14,598 - plugin.sync.main                 (1b8c) :  WARNING (plugin.sync.main:1171) - Exception raised in sync task: A load persistent id instruction was encountered,
but no persistent_load function was specified.
Traceback (most recent call last):
  File "C:\Users\kiborg\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\sync\main.py", line 173, in run_wrapper
    self.run()
  File "C:\Users\kiborg\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\sync\main.py", line 260, in run
    'stop'
  File "C:\Users\kiborg\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\sync\main.py", line 277, in _trigger
    func()
  File "C:\Users\kiborg\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\elapsed\main.py", line 64, in inner
    return func(*args, **kwargs)
  File "C:\Users\kiborg\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\sync\modes\full.py", line 23, in start
    self.trakt.refresh()
  File "C:\Users\kiborg\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\elapsed\main.py", line 64, in inner
    return func(*args, **kwargs)
  File "C:\Users\kiborg\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\sync\core\task\state\trakt_.py", line 110, in refresh
    self.changes = list(self.changes)
  File "C:\Users\kiborg\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\trakt_sync\cache\main.py", line 39, in refresh
    for result in source.refresh(username):
  File "C:\Users\kiborg\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\trakt_sync\cache\sources\sync.py", line 84, in refresh
    changes = self.diff(m, d, collection['store'], store)
  File "C:\Users\kiborg\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\trakt_sync\cache\sources\sync.py", line 138, in diff
    result = self._show_differ.run(base, current, handlers=[data_name])
  File "C:\Users\kiborg\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\trakt_sync\differ\show.py", line 35, in run
    actions = self.process_common(base[key], current[key], handlers=handlers)
  File "C:\Users\kiborg\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\trakt_sync\cache\backends\stash_.py", line 43, in __getitem__
    return self.stash.__getitem__(key)
  File "C:\Users\kiborg\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\stash\main.py", line 90, in __getitem__
    return self.algorithm[key]
  File "C:\Users\kiborg\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\stash\algorithms\lru.py", line 72, in __getitem__
    return self.load(key)
  File "C:\Users\kiborg\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\stash\algorithms\lru.py", line 226, in load
    self[key] = self.archive[key]
  File "C:\Users\kiborg\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\stash\archives\a_apsw.py", line 158, in __getitem__
    return self.loads(row[0])
  File "C:\Users\kiborg\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\stash\archives\core\base.py", line 17, in loads
    return self.serializer.loads(value)
  File "C:\Users\kiborg\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\stash\serializers\s_pickle.py", line 43, in loads
    return pickle.load(value)
UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.
2017-05-25 11:51:15,625 - plugin.core.backup.sources.database (1b8c) :  INFO (plugin.core.backup.sources.database:1159) - [trakt\1] Backing up database to u'C:\\Users\\kiborg\\AppData\\Local\\Plex Media Server\\Plug-in Support\\Data\\com.plexapp.plugins.trakttv\\Backups\\trakt\\1.bgr\\2017\\05\\25_115115_28690.db'
2017-05-25 11:51:15,944 - plugin.sync.main                 (1b8c) :  INFO (plugin.sync.main:1159) - (0) Done
2017-05-25 11:51:16,667 - root                             (35d8) :  DEBUG (root:265) - Exception in I/O handler for fd 1384
Traceback (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-995f1dead\Framework.bundle\Contents\Resources\Platforms\Shared\Libraries\tornado\ioloop.py", line 256, in start
    self._handlers[fd](fd, events)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-995f1dead\Framework.bundle\Contents\Resources\Platforms\Shared\Libraries\tornado\stack_context.py", line 128, in wrapped
    callback(*args, **kwargs)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-995f1dead\Framework.bundle\Contents\Resources\Platforms\Shared\Libraries\tornado\httpserver.py", line 219, in _handle_events
    connection, address = self._socket.accept()
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\socket.py", line 206, in accept
    sock, addr = self._sock.accept()
`

**Comment by luke-barnett** [comment]
I believe I'm getting the same issue. I have a new plex installation that I'm wanting to pull my watched status' down from trakt to.

Authenticated, and it is syncing tv shows correctly, however it is not syncing movies. Will try to pull up the logs to confirm if it's the same issue.

**Comment by kenaconlon** [comment]
Im having the same issue its reporting tv shows but not movies.   Im getting that same error in my log.   If youve figured out a way to rectify this please post it here.

**Comment by DenniWittig** [comment]
No synching of watch status whatsoever. No idea how to fix it. Last update on trakt of watch status was on june 1st.

**Comment by wah0808** [comment]
I'm experiencing the same thing, no syncing of watched shows.  It 'claims' to be syncing in the status window however none of the information shows up in Trakt.

**Comment by samshoo** [comment]
+1

**Comment by DenniWittig** [comment]
Completely removing the plug-in and reinstalling it fixed it for me.

**Comment by wah0808** [comment]
@DenniWittig That was the first thing I tried, I get the error "This channel could not be uninstalled"

**Comment by wah0808** [comment]
Well, I removed the files and re-cloned it... that worked.  Should have done this the first time.

**Comment by wkupike2000** [comment]
I'm having the same issues. I closed Plex, deleted the Plugins Folder for it and then redownloaded it and restarted Plex.  Same issues.  Attaching screenshot of errors I see in Plex for it. Any ideas??

![trakt](https://user-images.githubusercontent.com/20891065/30211844-82fc4b38-9470-11e7-867d-830c368b45c0.PNG)

**Comment by dege13** [comment]
I have the same issue as the log entries in the original report. Tried reinstalling the plugin several times.

`2017-10-19 08:44:33,898 - root                             (2b24) :  INFO (root:840) - 304 GET /video/trakt (127.0.0.1) 23.00ms
2017-10-19 08:44:33,956 - root                             (11f8) :  DEBUG (root:265) - Exception in I/O handler for fd 1168
Traceback (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-1bf240a65\Framework.bundle\Contents\Resources\Platforms\Shared\Libraries\tornado\ioloop.py", line 256, in start
    self._handlers[fd](fd, events)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-1bf240a65\Framework.bundle\Contents\Resources\Platforms\Shared\Libraries\tornado\stack_context.py", line 128, in wrapped
    callback(*args, **kwargs)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-1bf240a65\Framework.bundle\Contents\Resources\Platforms\Shared\Libraries\tornado\httpserver.py", line 219, in _handle_events
    connection, address = self._socket.accept()
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\socket.py", line 206, in accept
    sock, addr = self._sock.accept()
error: [Errno 10035] A non-blocking socket operation could not be completed immediately
2017-10-19 08:44:33,957 - com.plexapp.plugins.trakttv      (2aa4) :  DEBUG (com.plexapp.plugins.trakttv:717) - Handling request GET /video/trakt/sync
2017-10-19 08:44:33,960 - com.plexapp.plugins.trakttv      (2aa4) :  DEBUG (com.plexapp.plugins.trakttv:814) - Found route matching /video/trakt/sync
`
