### ISSUE TITLE
CorruptError: database disk image is malformed

### ISSUE THREAD

**Issue by ulti21** [trakt/Plex-Trakt-Scrobbler#448]
Hi, 

I have been getting this error over and over for around a week or so, deleting plex.db does not help nor does a fresh installation.

I am running trakt through Plex version 1.7.5.4035 on a Synology NAS

Log file shows - 

2017-07-01 22:47:30,897 - root                             (7fc73f7fe700) :  INFO (root:840) - 304 GET /video/trakt/messages/view?error_id=2 (127.0.0.1) 34.64ms
2017-07-01 22:47:30,977 - plugin.sync.main                 (7fc727fff700) :  WARNING (plugin.sync.main:1171) - Exception raised in sync task: CorruptError: database disk image is malformed
Traceback (most recent call last):
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/sync/main.py", line 173, in run_wrapper
    self.run()
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/sync/main.py", line 260, in run
    'stop'
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/sync/main.py", line 277, in _trigger
    func()
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/elapsed/main.py", line 64, in inner
    return func(*args, **kwargs)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/sync/modes/full.py", line 36, in run
    self.modes[SyncMode.FastPull].execute_children('run')
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/sync/modes/core/base/mode.py", line 136, in execute_children
    func()
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/elapsed/main.py", line 64, in inner
    return func(*args, **kwargs)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/sync/modes/fast_pull/movies.py", line 66, in run
    for mo_id, guid, p_movie in self.p_movies:
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plex_database/library.py", line 333, in movies_iterator
    for row in self._tuple_iterator(query):
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plex_database/library.py", line 75, in _tuple_iterator
    row = result.iterate()
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/peewee.py", line 1919, in iterate
    row = self.cursor.fetchone()
  File "src/cursor.c", line 236, in resetcursor
CorruptError: CorruptError: database disk image is malformed
2017-07-01 22:47:31,242 - root                             (7fc73f7fe700) :  INFO (root:840) - 200 GET /video/trakt/messages/view?error_id=2 (127.0.0.1) 53.68ms
2017-07-01 22:47:31,685 - plugin.core.backup.sources.database (7fc727fff700) :  INFO (plugin.core.backup.sources.database:1159) - [trakt/1] Backing up database to '/config/Library/Application Support/Plex Media Server/Plug-in Support/Data/com.plexapp.plugins.trakttv/Backups/trakt/1.bgr/2017/07/01_224731_27.db'
2017-07-01 22:47:31,840 - plugin.sync.main                 (7fc727fff700) :  INFO (plugin.sync.main:1159) - (0) Done
2017-07-01 22:47:34,775 - sentry.errors                    (7fc73d2f8700) :  ERROR (sentry.errors:665) - Sentry responded with an API error: RateLimited(Creation of this event was denied due to rate limiting)
2017-07-01 22:47:34,775 - sentry.errors.uncaught           (7fc73d2f8700) :  ERROR (sentry.errors.uncaught:696) - [u'Exception raised in sync task: CorruptError: database disk image is malformed', u'  File "plugin/sync/main.py", line 173, in run_wrapper', u'  File "plugin/sync/main.py", line 260, in run', u'  File "plugin/sync/main.py", line 277, in _trigger', u'  File "elapsed/main.py", line 64, in inner', u'  File "plugin/sync/modes/full.py", line 36, in run', u'  File "plugin/sync/modes/core/base/mode.py", line 136, in execute_children', u'  File "elapsed/main.py", line 64, in inner', u'  File "plugin/sync/modes/fast_pull/movies.py", line 66, in run', u'  File "plex_database/library.py", line 333, in movies_iterator', u'  File "plex_database/library.py", line 75, in _tuple_iterator', u'  File "Shared/peewee.py", line 1919, in iterate', u'  File "src/cursor.c", line 236, in resetcursor']

Can anyone advise anything else to try?

Thanks

**Comment by kramden88** [comment]
Reviving this thread for anyone else who encounters this problem. Quit Plex then navigate to the db file in the log config/Library/Application Support/Plex Media Server/Plug-in Support/Data/com.plexapp.plugins.trakttv.db, delete it, relaunch Plex, reauthenticate trakt.tv by pasting a new code in the plugin settings, the run a sync by clicking on the plugin icon.
