### ISSUE TITLE
Exception in Logfile

### ISSUE THREAD

**Issue by bassrock** [trakt/Plex-Trakt-Scrobbler#467]
I'm seeing the following error constantly in my log file:

```

2017-10-25 13:31:27,418 - plex_database.library (80c624a00) : WARNING (plex_database.library:1171) - Unable to retrieve row: 'utf8' codec can't decode byte 0xe8 in position 50: invalid continuation byte

Traceback (most recent call last):
    File "/usr/local/plexdata-plexpass/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plex_database/library.py", line 75, in _tuple_iterator
    row = result.iterate()
    File "/usr/local/plexdata-plexpass/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/peewee.py", line 1919, in iterate
    row = self.cursor.fetchone()

UnicodeDecodeError: 'utf8' codec can't decode byte 0xe8 in position 50: invalid continuation byte

2017-10-25 13:31:28,861 - plex_database.library (80c624a00) : WARNING (plex_database.library:1171) - Unable to retrieve row: 'utf8' codec can't decode byte 0xe9 in position 87: invalid continuation byte
Traceback (most recent call last):
    File "/usr/local/plexdata-plexpass/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plex_database/library.py", line 75, in _tuple_iterator
    row = result.iterate()
    File "/usr/local/plexdata-plexpass/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/peewee.py", line 1919, in iterate
    row = self.cursor.fetchone()

```

Is this an issue?

**Comment by rectifyer** [comment]
Does v1.3.3 fix this?
