### ISSUE TITLE
Authentication update

### ISSUE THREAD

**Issue by AlexMarcoDAngelo** [trakt/Plex-Trakt-Scrobbler#479]
Trakt changed their authentication and now when try using the plugin I get:
**[Sentry] Connection refused (code:111)
[Trakt.tv] OAuth must be provided (code: 401)**

So effectively now the plugin doesn't work!

**Comment by rectifyer** [comment]
Nothing has changed in regards to Trakt authentication that would break this plugin. Are you able to connect with Trakt and the Trakt API ok outside of this plugin? or using another app?

**Comment by AlexMarcoDAngelo** [comment]
Yes I have several other apps registered and working (see attached image)

​
The plugin is registered in Trakt (see attached image)

​
Getting authentication errors from in the plugin about oAuth (see attached
image)

​

I know they changed the authentication model recently because another app I
was using - Media Center Master - stopped working and the developer made
the changes to work with the new Trakt authentication model last week...

But if you are saying there are no changes - than why I am getting those
errors?

**Comment by AlexMarcoDAngelo** [comment]
[http://tarahosting.com/trakt.png](url)

**Comment by rectifyer** [comment]
In regards to Media Center Master, they were using a very old authentication that hasn't been support in about 2 years, and that was removed about 9 months ago. I'm not sure why they only just updated it.

This plex plugin uses an authentication called PIN authentication. It is not a supported authentication anymore, but it will still continue to work indefinitely and we haven't stopped it from working. Have you tried to re-authenticate your plugin? It sounds like that might fix it.

**Comment by AlexMarcoDAngelo** [comment]
Yes, I tried several times.. Including reinstalling the plug in,
reauthorizing.. Every goes with no issues until the synch when getting the
errors.. So strange.. I used it fine back when my Plex was on Windows.. Now
it is on WD PR4100 PRO... Tried both first manual install  then removed and
installed it trough the UAS store.. Same exact issue.. So strange..

**Comment by GenerlAce** [comment]
im having the same issue. this is what i get no matter what i do. https://imgur.com/a/2L0UZ

**Comment by rdemendoza** [comment]
+1

**Comment by stephanterning** [comment]
+1, same issue. tried reinstall and went through the pin setup, still not working

[Trakt.tv] Oauth must be provided (code: 401)

**Comment by rdemendoza** [comment]
Even with from a new IP address :
`sentry.errors                    (7fbbc0db7700) :  ERROR (sentry.errors:671) - Sentry responded with an error: MaxRetryError: HTTPSConnectionPool(host='sentry.skipthe.net', port=443): Max retries exceeded with url: /api/1/store/ (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fbbc0e3c910>: Failed to establish a new connection: [Errno 111] Connection refused')) (url: https://sentry.skipthe.net/api/1/store/)
Traceback (most recent call last):
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/raven/transport/threaded_requests.py", line 26, in send_sync
    super(ThreadedRequestsHTTPTransport, self).send(data, headers)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/raven/transport/requests.py", line 41, in send
    timeout=self.timeout
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/raven/breadcrumbs.py", line 297, in send
    resp = real_send(self, request, *args, **kwargs)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: MaxRetryError: HTTPSConnectionPool(host='sentry.skipthe.net', port=443): Max retries exceeded with url: /api/1/store/ (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fbbc0e3c910>: Failed to establish a new connection: [Errno 111] Connection refused'))`

**Comment by rdemendoza** [comment]
Seems sentry.skipthe.net is dead so no new authentications.

**Comment by shwetkprabhat** [comment]
Yeah same error using plex inc docker - but looks like the issue is closed.

**Comment by GenerlAce** [comment]
working now for me! try it again everyone.

**Comment by stephanterning** [comment]
Yes! Works for me now as well. Thank you! (I updated from 1.3.2 to 1.3.3)
