### ISSUE TITLE
A non-blocking socket operation could not be completed immediately

### ISSUE THREAD

**Issue by scphantm** [trakt/Plex-Trakt-Scrobbler#486]
Finally after a much needed update, (thank you very much) this is usable again.  (again, thank you).  An initial sync is still taking a very long time, hopefully it will beat the last record of 3 hours (when it had that url for the site that disappeared in it).  I looked at the logs just to see if everything was nice and saw some exceptions in it.  Im attaching the log file.

[com.plexapp.plugins.trakttv.log](https://github.com/trakt/Plex-Trakt-Scrobbler/files/1813635/com.plexapp.plugins.trakttv.log)

**Comment by scphantm** [comment]
Got a hard failure 

[com.plexapp.plugins.trakttv.log](https://github.com/trakt/Plex-Trakt-Scrobbler/files/1813670/com.plexapp.plugins.trakttv.log)

**Comment by stumpylog** [comment]
I am also observing this issue, with the same traceback on error.

```
Traceback (most recent call last):
  File "D:\ProgramFiles\PlexMediaServer\Resources\Plug-ins-b4605f76e\Framework.bundle\Contents\Resources\Platforms\Shared\Libraries\tornado\ioloop.py", line 256, in start
    self._handlers[fd](fd, events)
  File "D:\ProgramFiles\PlexMediaServer\Resources\Plug-ins-b4605f76e\Framework.bundle\Contents\Resources\Platforms\Shared\Libraries\tornado\stack_context.py", line 128, in wrapped
    callback(*args, **kwargs)
  File "D:\ProgramFiles\PlexMediaServer\Resources\Plug-ins-b4605f76e\Framework.bundle\Contents\Resources\Platforms\Shared\Libraries\tornado\httpserver.py", line 219, in _handle_events
    connection, address = self._socket.accept()
  File "D:\ProgramFiles\PlexMediaServer\python27.zip\socket.py", line 206, in accept
    sock, addr = self._sock.accept()
error: [Errno 10035] A non-blocking socket operation could not be completed immediately
```

PMS Version: 1.13.1.5063
Trakt Plugin Version: 1.3.3

**Comment by PnoT** [comment]
I'm getting this behavior as well.  Any progress on tracking this down or a fix?

**Comment by iaing80** [comment]
Guessing there was no fix for this issue as still open from 2018?
Also seeing this error and getting no update in trakt.tv.

**Comment by belqit** [comment]
still no fix for this?
