### ISSUE TITLE
SQLError: no such column: t1.progress

### ISSUE THREAD

**Issue by marcoacarvalho** [trakt/Plex-Trakt-Scrobbler#528]
After compiling apsw as stated at https://github.com/trakt/Plex-Trakt-Scrobbler/issues/521#issuecomment-473983442 on a Raspberry Pi 2 B running Archlinux|ARM I'm getting the following error:

```
2019-04-10 10:03:16,820 - plugin.managers.action           (6f9fc460) :  WARNING (plugin.managers.action:122) - Unable to retrieve action from queue - SQLError: no such column: t1.progress
Traceback (most recent call last):
  File "/var/lib/plex/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/managers/action.py", line 115, in run
    action = ActionQueue.get()
  File "/var/lib/plex/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/peewee.py", line 4099, in get
    return sq.get()
  File "/var/lib/plex/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/peewee.py", line 2725, in get
    return clone.execute().next()
  File "/var/lib/plex/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/peewee.py", line 2769, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/var/lib/plex/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/peewee.py", line 2455, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/var/lib/plex/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/playhouse/apsw_ext.py", line 103, in execute_sql
    self._execute_sql(cursor, sql, params)
  File "/var/lib/plex/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/playhouse/apsw_ext.py", line 95, in _execute_sql
    cursor.execute(sql, params or ())
  File "/var/lib/plex/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/exception_wrappers/database/apsw/raw.py", line 25, in execute
    return self.__cursor.execute(*args, **kwargs)
  File "src/cursor.c", line 1019, in APSWCursor_execute.sqlite3_prepare
  File "src/statementcache.c", line 386, in sqlite3_prepare
SQLError: SQLError: no such column: t1.progress
```

**Comment by srod** [comment]
The same for me on a Pi 3B+, and this error message:

`Exception: SQLError: no such column: t1.deleted`

**Comment by RazielMalah** [comment]
Have a same issue:
`2019-04-19 00:00:42,248 - plugin.managers.action           (700fd470) :  WARNING (plugin.managers.action:122) - Unable to retrieve action from queue - SQLError: no such column: t1.progress
Traceback (most recent call last):
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/managers/action.py", line 115, in run
    action = ActionQueue.get()
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/peewee.py", line 4099, in get
    return sq.get()
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/peewee.py", line 2725, in get
    return clone.execute().next()
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/peewee.py", line 2769, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/peewee.py", line 2455, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/playhouse/apsw_ext.py", line 103, in execute_sql
    self._execute_sql(cursor, sql, params)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/playhouse/apsw_ext.py", line 95, in _execute_sql
    cursor.execute(sql, params or ())
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/exception_wrappers/database/apsw/raw.py", line 25, in execute
    return self.__cursor.execute(*args, **kwargs)
  File "src/cursor.c", line 1019, in APSWCursor_execute.sqlite3_prepare
  File "src/statementcache.c", line 386, in sqlite3_prepare
SQLError: SQLError: no such column: t1.progress
`

**Comment by pauloolileal** [comment]
I was able to figure out the problem. For some reason, the plugin database is being created without any structure. To remedy the problem I installed on another operating system (in the case of Windows), copied the database and applied to my Raspsberry Pi b3 +. Worked perfectly.

I replaced the database on this path: "/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.trakttv.db"

**Comment by Raph521** [comment]
> I was able to figure out the problem. For some reason, the plugin database is being created without any structure. To remedy the problem I installed on another operating system (in the case of Windows), copied the database and applied to my Raspsberry Pi b3 +. Worked perfectly.
> 
> I replaced the database on this path: "/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.trakttv.db"

Interesting @pauloolileal , did you replace just the .db file or replace the .db-wal and .db-shm files, too?

**Comment by Craicerjack** [comment]
@Raph521  I had to copy all three files over to get it working. NIghtmare for one plugin.

**Comment by Raph521** [comment]
@Craicerjack @pauloolileal Thanks for the help, that did the trick!

**Comment by marine1988** [comment]
im having the same problem is the any fix coming to this plugin?

**Comment by zpon** [comment]
I'm seeing this as well (raspberry pi 3), it would be nice with fix. Let me know if I can provide any info.

**Comment by christiga** [comment]
Same error here, any info ?

**Comment by jackiass** [comment]
+1 here on RPi3

**Comment by mediumwalter** [comment]
+1 on RPi4

**Comment by lucaspir7** [comment]
> 
> 
> I was able to figure out the problem. For some reason, the plugin database is being created without any structure. To remedy the problem I installed on another operating system (in the case of Windows), copied the database and applied to my Raspsberry Pi b3 +. Worked perfectly.
> 
> I replaced the database on this path: "/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.trakttv.db"

Can you upload the database files?

**Comment by mediumwalter** [comment]
> > I was able to figure out the problem. For some reason, the plugin database is being created without any structure. To remedy the problem I installed on another operating system (in the case of Windows), copied the database and applied to my Raspsberry Pi b3 +. Worked perfectly.
> > I replaced the database on this path: "/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.trakttv.db"
> 
> Can you upload the database files?

I got it to work! Try mine out

[trakt-db.zip](https://github.com/trakt/Plex-Trakt-Scrobbler/files/3387780/trakt-db.zip)

**Comment by ramiel** [comment]
Any news on this?

**Comment by fpatrick** [comment]
> > > I was able to figure out the problem. For some reason, the plugin database is being created without any structure. To remedy the problem I installed on another operating system (in the case of Windows), copied the database and applied to my Raspsberry Pi b3 +. Worked perfectly.
> > > I replaced the database on this path: "/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.trakttv.db"
> > 
> > 
> > Can you upload the database files?
> 
> I got it to work! Try mine out
> 
> [trakt-db.zip](https://github.com/trakt/Plex-Trakt-Scrobbler/files/3387780/trakt-db.zip)

Thanks!!! Finally work out after I replace with your db and deleting trakt .db-wal and .db-shm files.

**Comment by shotfirer** [comment]
Same issue here, after using the scrobbler for years I had to reinstall, and now stuck with this stupid problem. Replacing the db doesn't help. Any other ideas?
