### ISSUE TITLE
Plex-Trakt-Scrobbler not working anymore since a week

### ISSUE THREAD

**Issue by Altaess** [trakt/Plex-Trakt-Scrobbler#556]
Hello,

I use the plugin since 6 months ago and it worked pretty good.

But since 1 week, the plugin don't work anymore (i see the plugin in plugin section, but there is no more sync working). 
I don't know what to do, and how check what is going wrong.

My Plex Server is running on Windows 10 64bits.

Any idea?
Thank you

**Comment by Altaess** [comment]
Here you can see log file : 

`2020-04-17 16:00:30,388 - plex_activity.activity           (219c) :  INFO (plex_activity.activity:48) - Finished starting 2 method(s): "websocket", "logging"
2020-04-17 16:00:30,417 - plex_activity.sources.s_logging.main (1b14) :  INFO (plex_activity.sources.s_logging.main:107) - Opened file path: "C:\Users\Plex\AppData\Local\Plex Media Server\Logs\Plex Media Server.log"
2020-04-17 16:00:35,112 - com.plexapp.plugins.trakttv      (7e8) :  INFO (com.plexapp.plugins.trakttv:131) - Saved the dictionary file
2020-04-17 16:02:00,493 - root                             (1590) :  INFO (root:828) - 200 GET /video/trakt/:/prefs (127.0.0.1) 47.00ms
2020-04-17 16:02:42,400 - root                             (1e40) :  INFO (root:828) - 200 GET /video/trakt/:/prefs (127.0.0.1) 29.00ms
2020-04-17 16:05:37,654 - root                             (138c) :  INFO (root:828) - 200 GET /video/trakt/:/prefs (127.0.0.1) 33.00ms
2020-04-17 16:12:02,838 - plugin.sync.triggers.library_update (1f74) :  INFO (plugin.sync.triggers.library_update:94) - Scanner started at: datetime.datetime(2020, 4, 17, 14, 9, 59, 893000, tzinfo=tzutc())
2020-04-17 16:12:02,841 - plugin.sync.triggers.library_update (1f74) :  ERROR (plugin.sync.triggers.library_update:84) - Unable to queue sync: 'APSWDatabaseWrapper' object has no attribute 'timeout'
Traceback (most recent call last):
  File "C:\Users\Plex\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\sync\triggers\library_update.py", line 82, in _run
    self._queue()
  File "C:\Users\Plex\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\sync\triggers\library_update.py", line 104, in _queue
    for account in accounts:
  File "C:\Users\Plex\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 2776, in __iter__
    return iter(self.execute())
  File "C:\Users\Plex\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 2769, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "C:\Users\Plex\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 2455, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "C:\Users\Plex\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 3150, in execute_sql
    cursor = self.get_cursor()
  File "C:\Users\Plex\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 3116, in get_cursor
    return self.get_conn().cursor()
  File "C:\Users\Plex\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 3109, in get_conn
    self.connect()
  File "C:\Users\Plex\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 3089, in connect
    **self.connect_kwargs)
  File "C:\Users\Plex\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\exception_wrappers\database\apsw\peewee.py", line 19, in _connect
    if self.timeout is not None:
AttributeError: 'APSWDatabaseWrapper' object has no attribute 'timeout'
2020-04-17 16:12:42,190 - com.plexapp.plugins.trakttv      (2250) :  CRITICAL (com.plexapp.plugins.trakttv:574) - Exception when constructing response (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\runtime.py", line 951, in construct_response
    el = result._to_xml()
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\objectkit.py", line 667, in _to_xml
    el = Framework.modelling.objects.ModelInterfaceObjectContainer._to_xml(self)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\modelling\objects.py", line 382, in _to_xml
    root = Container._to_xml(self)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\modelling\objects.py", line 139, in _to_xml
    self._append_children(root, self._objects)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\modelling\objects.py", line 145, in _append_children
    el = obj._to_xml()
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\objectkit.py", line 80, in _to_xml
    el = ObjectWithHTTPHeaders._to_xml(self)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\objectkit.py", line 59, in _to_xml
    el = Framework.modelling.objects.Object._to_xml(self)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\modelling\objects.py", line 84, in _to_xml
    self._set_attribute(root, name, self._attributes[name])
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\modelling\objects.py", line 73, in _set_attribute
    self._core.log_exception("Exception setting attribute '%s' of object %s to %s (type: %s)", name, str(self), str(value), str(type(value)))
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\core.py", line 574, in log_exception
    self.log.critical(self.traceback(fmt % tuple(args)))
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\logging\__init__.py", line 1219, in critical
    self._log(CRITICAL, msg, args, **kwargs)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\logging\__init__.py", line 1293, in _log
    self.handle(record)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\logging\__init__.py", line 1303, in handle
    self.callHandlers(record)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\logging\__init__.py", line 1343, in callHandlers
    hdlr.handle(record)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\logging\__init__.py", line 766, in handle
    self.emit(record)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\core.py", line 89, in emit
    self._core.sandbox.context.log.append(self.format(record))
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\logging\__init__.py", line 741, in format
    return fmt.format(record)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\core.py", line 77, in format
    record.__dict__[key] = uni(record.__dict__[key])
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\subsystem\ospathfix.py", line 51, in uni
    return unicode(s.decode('utf-8'))
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 210: invalid continuation byte

2020-04-17 16:12:42,193 - root                             (2250) :  ERROR (root:828) - 500 GET /video/trakt (127.0.0.1) 39.00ms
2020-04-17 16:12:42,344 - com.plexapp.plugins.trakttv      (22d0) :  CRITICAL (com.plexapp.plugins.trakttv:574) - Exception when constructing response (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\runtime.py", line 951, in construct_response
    el = result._to_xml()
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\objectkit.py", line 667, in _to_xml
    el = Framework.modelling.objects.ModelInterfaceObjectContainer._to_xml(self)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\modelling\objects.py", line 382, in _to_xml
    root = Container._to_xml(self)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\modelling\objects.py", line 139, in _to_xml
    self._append_children(root, self._objects)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\modelling\objects.py", line 145, in _append_children
    el = obj._to_xml()
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\objectkit.py", line 80, in _to_xml
    el = ObjectWithHTTPHeaders._to_xml(self)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\objectkit.py", line 59, in _to_xml
    el = Framework.modelling.objects.Object._to_xml(self)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\modelling\objects.py", line 84, in _to_xml
    self._set_attribute(root, name, self._attributes[name])
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\modelling\objects.py", line 73, in _set_attribute
    self._core.log_exception("Exception setting attribute '%s' of object %s to %s (type: %s)", name, str(self), str(value), str(type(value)))
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\core.py", line 574, in log_exception
    self.log.critical(self.traceback(fmt % tuple(args)))
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\logging\__init__.py", line 1219, in critical
    self._log(CRITICAL, msg, args, **kwargs)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\logging\__init__.py", line 1293, in _log
    self.handle(record)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\logging\__init__.py", line 1303, in handle
    self.callHandlers(record)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\logging\__init__.py", line 1343, in callHandlers
    hdlr.handle(record)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\logging\__init__.py", line 766, in handle
    self.emit(record)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\core.py", line 89, in emit
    self._core.sandbox.context.log.append(self.format(record))
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\logging\__init__.py", line 741, in format
    return fmt.format(record)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\core.py", line 77, in format
    record.__dict__[key] = uni(record.__dict__[key])
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\subsystem\ospathfix.py", line 51, in uni
    return unicode(s.decode('utf-8'))
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 210: invalid continuation byte

2020-04-17 16:12:42,346 - root                             (22d0) :  ERROR (root:828) - 500 GET /video/trakt (127.0.0.1) 37.00ms
2020-04-17 16:12:42,519 - com.plexapp.plugins.trakttv      (840) :  CRITICAL (com.plexapp.plugins.trakttv:574) - Exception when constructing response (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\runtime.py", line 951, in construct_response
    el = result._to_xml()
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\objectkit.py", line 667, in _to_xml
    el = Framework.modelling.objects.ModelInterfaceObjectContainer._to_xml(self)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\modelling\objects.py", line 382, in _to_xml
    root = Container._to_xml(self)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\modelling\objects.py", line 139, in _to_xml
    self._append_children(root, self._objects)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\modelling\objects.py", line 145, in _append_children
    el = obj._to_xml()
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\objectkit.py", line 80, in _to_xml
    el = ObjectWithHTTPHeaders._to_xml(self)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\objectkit.py", line 59, in _to_xml
    el = Framework.modelling.objects.Object._to_xml(self)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\modelling\objects.py", line 84, in _to_xml
    self._set_attribute(root, name, self._attributes[name])
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\modelling\objects.py", line 73, in _set_attribute
    self._core.log_exception("Exception setting attribute '%s' of object %s to %s (type: %s)", name, str(self), str(value), str(type(value)))
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\core.py", line 574, in log_exception
    self.log.critical(self.traceback(fmt % tuple(args)))
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\logging\__init__.py", line 1219, in critical
    self._log(CRITICAL, msg, args, **kwargs)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\logging\__init__.py", line 1293, in _log
    self.handle(record)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\logging\__init__.py", line 1303, in handle
    self.callHandlers(record)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\logging\__init__.py", line 1343, in callHandlers
    hdlr.handle(record)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\logging\__init__.py", line 766, in handle
    self.emit(record)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\core.py", line 89, in emit
    self._core.sandbox.context.log.append(self.format(record))
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\logging\__init__.py", line 741, in format
    return fmt.format(record)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\core.py", line 77, in format
    record.__dict__[key] = uni(record.__dict__[key])
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ccb6eb67e\Framework.bundle\Contents\Resources\Versions\2\Python\subsystem\ospathfix.py", line 51, in uni
    return unicode(s.decode('utf-8'))
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 210: invalid continuation byte

2020-04-17 16:12:42,523 - root                             (840) :  ERROR (root:828) - 500 GET /video/trakt (127.0.0.1) 37.00ms`

**Comment by SvenVR73** [comment]
I have the same issue that I get Unable to queue sync: 'APSWDatabaseWrapper' object has no attribute 'timeout' ...

What did you do to fix this ?
