### ISSUE TITLE
Disk IO error with 

### ISSUE THREAD

**Issue by harshil-goel** [trakt/Plex-Trakt-Scrobbler#569]
I keep getting this error and trakt scrobbing stopped working since. 
```
Traceback (most recent call last):
File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/exception_wrappers/database/apsw/raw.py", line 25, in execute
  return self.__cursor.execute(*args, **kwargs)
File "src/cursor.c", line 1019, in APSWCursor_execute.sqlite3_prepare
File "src/statementcache.c", line 386, in sqlite3_prepare
IOError: IOError: disk I/O error
```

**Comment by harshil-goel** [comment]
I deleted the database, reinstalled the plugin and it worked.
