### ISSUE TITLE
Critical Error: Unable to import the playhouse.apsw_ext library (Failed to map segment from shared object) in Docker

### ISSUE THREAD

**Issue by MxFlix** [trakt/Plex-Trakt-Scrobbler#572]
I am running Plex via docker. I installed the Trakt plugin via the UAS, and when trying to access it via Kitana (also via docker), I get this error:
`Critical Error: Unable to import the playhouse.apsw_ext library (Failed to map segment from shared object)`

I have looked through other similar issues, but none of the solutions helped me. The drive on which plex and the config files are on is not mounted via noexec and the permissions for all files thereon are 777. I have also tried copying the apsw.so file [provided here](https://github.com/trakt/Plex-Trakt-Scrobbler/issues/521#issuecomment-476844277) into the subfolders of `Plug-in Support/Data/com.plexapp.plugins.trakttv/Libraries/Linux/x86_64/` (in fact, there were already apsw.so files in there, which I backed up and replaced, but this had no effect on the error).

The relevant log output is as follows:
```
2020-08-21 18:32:58,744 - plugin                           (7f1f75ffb700) :  INFO (plugin:19) - Started 0 modules: 
2020-08-21 18:32:58,745 - plugin.modules.core.manager      (7f1f75ffb700) :  INFO (plugin.modules.core.manager:74) - Module startup has been cancelled due to a critical plugin error
2020-08-21 18:32:58,746 - plugin.preferences.main          (7f1f75ffb700) :  WARNING (plugin.preferences.main:43) - Unable to retrieve option 'activity.mode': 'APSWDatabaseWrapper' object has no attribute 'timeout'
Traceback (most recent call last):
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/preferences/main.py", line 39, in get
    option = option_cls.get(account)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/preferences/options/core/base/simple.py", line 48, in get
    'value': self._pack(self.default),
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/peewee.py", line 4106, in get_or_create
    return sq.get(), False
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/peewee.py", line 2725, in get
    return clone.execute().next()
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/peewee.py", line 2769, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/peewee.py", line 2455, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/peewee.py", line 3150, in execute_sql
    cursor = self.get_cursor()
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/peewee.py", line 3116, in get_cursor
    return self.get_conn().cursor()
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/peewee.py", line 3109, in get_conn
    self.connect()
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/peewee.py", line 3089, in connect
    **self.connect_kwargs)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/exception_wrappers/database/apsw/peewee.py", line 19, in _connect
    if self.timeout is not None:
AttributeError: 'APSWDatabaseWrapper' object has no attribute 'timeout'
```

Can anyone help me out?

**Comment by stoneC0der** [comment]
I have the same problem, for me it started after updating to macOS 11.2 or updating Plex not really sure but everything was fine on 11.0.1.
I tried reinstalling the plugin nothing.

I am thinking about downgrading Plex to the last know working version (not really sure which one) by doing a clean install and reinstall the plugin to see if the issue will be solve.

Did you find a working fix?
