### ISSUE TITLE
Unable to open database file

### ISSUE THREAD

**Issue by IkkiNit** [trakt/Plex-Trakt-Scrobbler#590]
Hello,

I'm just installing the Trakttv bundle manually like in the manual and I have those errors when trying to configure the plugin:

2021-01-11 11:32:41,030 - exception_wrappers.database.apsw.base (1b78) :  INFO (exception_wrappers.database.apsw.base:34) - Exception raised in apsw: CantOpenError: unable to open database file
Traceback (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-3c3adfcb4\Trakttv.bundle\Contents\Libraries\Shared\exception_wrappers\database\apsw\peewee.py", line 17, in _connect
    conn = APSWConnectionWrapper(database, **kwargs)
CantOpenError: CantOpenError: unable to open database file
2021-01-11 11:32:41,032 - plugin.core.message              (1b78) :  CRITICAL (plugin.core.message:77) - Unable to open plugin database (unable to open database file)
Traceback (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-3c3adfcb4\Trakttv.bundle\Contents\Libraries\Shared\exception_wrappers\database\apsw\peewee.py", line 17, in _connect
    conn = APSWConnectionWrapper(database, **kwargs)
CantOpenError: CantOpenError: unable to open database file
2021-01-11 11:32:45,571 - com.plexapp.plugins.trakttv      (6d4) :  INFO (com.plexapp.plugins.trakttv:131) - Saved the dictionary file

Do you know what's wrong ?

I have those errors before maybe it can be because of that:

2021-01-11 11:32:37,259 (d24) :  ERROR (logkit:22) - Unable to find preferences file at "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-in Support\Preferences\com.plexapp.plugins.trakttv.xml", unable to run migration
2021-01-11 11:32:37,259 (d24) :  DEBUG (logkit:13) - Running migration: <SelectiveSync object at 0x0531D4D0>
2021-01-11 11:32:37,259 (d24) :  ERROR (logkit:22) - Unable to find preferences file at "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-in Support\Preferences\com.plexapp.plugins.trakttv.xml", unable to run migration

**Comment by IkkiNit** [comment]
I was in a wrong Plugins folder
