### ISSUE TITLE
New Windows install won't work

### ISSUE THREAD

**Issue by Mongjohn** [trakt/Plex-Trakt-Scrobbler#595]
I have a Windows 10 PMS install with the Trakt.tv plugin working, but am trying migrate to a Server 2019.

However, even on a fresh Windows Server 2019 AND Windows 10 Pro installation, the plugin won't scrobble and the log is full of ​errors.

The errors start at the following line, and continues on from there:
```
2021-04-17 16:31:41,680 - plugin.core.libraries.manager    (1eac) :  INFO (plugin.core.libraries.manager:60) - Testing native library support...
2021-04-17 16:31:41,680 - plugin.core.libraries.tests.core.base (1eac) :  DEBUG (plugin.core.libraries.tests.core.base:96) - Starting test: plugin.core.libraries.tests.apsw_:test_import
2021-04-17 16:31:41,809 - plugin.core.libraries.tests.core.base (1eac) :  INFO (plugin.core.libraries.tests.core.base:124) - DLL load failed: The specified module could not be found. - Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\core\libraries\tests\core\host.py", line 128, in <module>
    result = run()
  File "C:\Users\Administrator\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\core\libraries\tests\core\host.py", line 121, in run
    return func()
  File "C:\Users\Administrator\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\core\libraries\tests\apsw_.py", line 9, in test_import
    import apsw
ImportError: DLL load failed: The specified module could not be found.
```

For reference, the same lines on the working Windows 10 install reads:
```
2021-04-17 16:35:20,489 - plugin.core.libraries.manager    (500) :  INFO (plugin.core.libraries.manager:60) - Testing native library support...
2021-04-17 16:35:20,489 - plugin.core.libraries.tests.core.base (500) :  DEBUG (plugin.core.libraries.tests.core.base:96) - Starting test: plugin.core.libraries.tests.apsw_:test_import
2021-04-17 16:35:20,631 - plugin.core.libraries.manager    (500) :  INFO (plugin.core.libraries.manager:106) - apsw: available (sqlite: 3015000, apsw: 3.15.0-r1)
```

Anyone got a clue why this isn't working?

**Comment by Mongjohn** [comment]
Installed Kitana and accessing the plugin through that gives the error:
`Critical Error: Unable to import the playhouse.apsw_ext library (DLL load failed: The specified module could not be found.)`

**Comment by Mongjohn** [comment]
Installing Visual C++ Redistributable Packages for Visual Studio 2013 seems to have fixed it. Finally!
